# Generated by Django 4.2.1 on 2023-07-04 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formulate_plan", "0008_rename_is_prioritization_workproject_is_prioritized"),
        ("project_planning", "0025_projectproposedtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanStartDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StartPmsProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectExecution",
            fields=[
                (
                    "workproject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="formulate_plan.workproject",
                    ),
                ),
                (
                    "work_proposer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("उपभोक्ता समिति / टोल", "उपभोक्ता समिति / टोल"),
                            ("वडा", "वडा"),
                            ("न.पा./गा.पा.", "न.पा./गा.पा."),
                            ("अन्य", "अन्य"),
                        ],
                        max_length=55,
                        null=True,
                    ),
                ),
                ("is_multi_year_plan", models.BooleanField(default=False)),
                ("first_year", models.IntegerField(blank=True, null=True)),
                ("second_year", models.IntegerField(blank=True, null=True)),
                ("third_year", models.IntegerField(blank=True, null=True)),
                ("forth_year", models.IntegerField(blank=True, null=True)),
                ("fifth_year", models.IntegerField(blank=True, null=True)),
                ("other", models.IntegerField(blank=True, null=True)),
                ("latitude", models.CharField(blank=True, max_length=100, null=True)),
                ("longitude", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "appropriated_amount",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("overhead", models.CharField(blank=True, max_length=20, null=True)),
                ("contingency", models.CharField(blank=True, max_length=20, null=True)),
                ("mu_aa_ka", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "public_charity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "maintenance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "disaster_mgmt_fund",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "total_estimate",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "self_payment",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_executing", models.BooleanField(default=True)),
                (
                    "plan_start_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.planstartdecision",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.program",
                    ),
                ),
                (
                    "project_nature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.projectnature",
                    ),
                ),
                (
                    "project_priority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.prioritytype",
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.projecttype",
                    ),
                ),
                (
                    "start_pms_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.startpmsprocess",
                    ),
                ),
                (
                    "strategic_sign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.strategicsign",
                    ),
                ),
                (
                    "subject_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.subjectarea",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("formulate_plan.workproject",),
        ),
    ]
