# Generated by Django 4.2.3 on 2023-07-10 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0025_projectproposedtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0024_estimate_abstract_of_cost_estimate_district_rate_and_more"),
        ("employee", "0007_cumulativedetail_cif_certificate_no"),
        ("plan_execution", "0005_remove_bailtype_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenderPurchaseBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectTender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "first_published_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "first_published_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bids_purchase_last_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bids_purchase_last_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bids_purchase_time", models.TimeField(blank=True, null=True)),
                (
                    "bids_enrollment_last_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bids_enrollment_last_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bids_enrollment_time", models.TimeField(blank=True, null=True)),
                (
                    "bids_open_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bids_open_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bids_open_time", models.TimeField(blank=True, null=True)),
                (
                    "invoice_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "invoice_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "news_paper_address",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "printing_press",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("paper_page_no", models.IntegerField(blank=True, null=True)),
                ("info_publication_no", models.IntegerField(blank=True, null=True)),
                (
                    "info_publication_price",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "publication_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "publication_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "voucher_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "voucher_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("voucher_no", models.CharField(blank=True, max_length=50, null=True)),
                ("address1", models.CharField(blank=True, max_length=50, null=True)),
                ("address2", models.CharField(blank=True, max_length=50, null=True)),
                ("address3", models.CharField(blank=True, max_length=50, null=True)),
                ("address4", models.CharField(blank=True, max_length=50, null=True)),
                ("address5", models.CharField(blank=True, max_length=50, null=True)),
                ("address6", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "representative_invoice_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "representative_invoice_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "representative_invoice_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "representative_send_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "representative_send_time",
                    models.TimeField(blank=True, max_length=50, null=True),
                ),
                (
                    "representative_send_address",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "representative1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "representative2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "representative3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "representative4",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "representative5",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "representative6",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("print_custom_report", models.BooleanField(default=False)),
                (
                    "bids_enrollment_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pt_beb_branch",
                        to="plan_execution.tenderpurchasebranch",
                    ),
                ),
                (
                    "bids_purchase_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pt_bpb_branch",
                        to="plan_execution.tenderpurchasebranch",
                    ),
                ),
                (
                    "contact_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pt_cb_branch",
                        to="plan_execution.tenderpurchasebranch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_paper_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.newspaper",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_tender",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectMobilization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("percent", models.IntegerField(blank=True, null=True)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "accounting_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.accountingtopic",
                    ),
                ),
                (
                    "body",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.sourcereceipt",
                    ),
                ),
                (
                    "budget_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.budgetsource",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectFinishedBailReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("comment_no", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.CharField(blank=True, max_length=100, null=True)),
                ("date_eng", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "executive_decision",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("print_custom_report", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectDeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "deadline_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "deadline_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "decision_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "decision_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("reason", models.CharField(blank=True, max_length=250, null=True)),
                ("remark", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectDarbhauBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("bid_sale_no", models.IntegerField(blank=True, null=True)),
                ("bid_enrollment_no", models.IntegerField(blank=True, null=True)),
                ("legal_bid", models.IntegerField(blank=True, null=True)),
                (
                    "comment_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "comment_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("comment_no", models.IntegerField(blank=True, null=True)),
                (
                    "comment_approved_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "comment_approved_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "proprietor_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "submitter_opinion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "accountant_opinion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_head_opinion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "office_head_decision",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "executive_decision",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.organization",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.position",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectBidCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("is_legal", models.BooleanField(default=False)),
                (
                    "bail_type",
                    models.CharField(
                        blank=True,
                        choices=[("बैंक", "बैंक"), ("नगद", "नगद")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("bail_amount", models.IntegerField(blank=True, null=True)),
                ("bank_guarantee_no", models.IntegerField(blank=True, null=True)),
                ("start_date", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "start_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("end_date", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "end_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bank_guarantee_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("बिड बन्ड ", "बिड बन्ड "),
                            ("पर्फरमेन्स बन्ड", "पर्फरमेन्स बन्ड"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("total_amount", models.IntegerField(blank=True, null=True)),
                ("mu_aa_ka", models.CharField(blank=True, max_length=50, null=True)),
                ("total", models.IntegerField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("attached_documents_list", models.CharField(max_length=155)),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.bfi",
                    ),
                ),
                (
                    "builder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.organization",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "contractor_invoiced_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contractor_invoiced_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contractor_invoiced_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contractor_remarks_1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contractor_remarks_2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("required_bail_amount", models.IntegerField(blank=True, null=True)),
                (
                    "required_performance_bond_amount",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "required_bail_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "required_bail_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "firm_address",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "firm_contact_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "grand_father_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("father_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contracting_party_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "contract_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contract_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "work_finished_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "work_finished_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("exist_bail_amount", models.IntegerField(blank=True, null=True)),
                (
                    "exist_performance_bond_amount",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "exist_bail_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "exist_bail_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("exist_bank_guarantee_no", models.IntegerField(blank=True, null=True)),
                ("end_date", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "end_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contractors_witness",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mandate_invoice_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mandate_invoice_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mandate_invoice_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pa_sa", models.CharField(blank=True, max_length=50, null=True)),
                ("remark_1", models.CharField(blank=True, max_length=50, null=True)),
                ("remark_2", models.CharField(blank=True, max_length=50, null=True)),
                ("remark_3", models.CharField(blank=True, max_length=50, null=True)),
                ("remark_4", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "officer_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "officer_position",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("print_custom_name", models.BooleanField(default=False)),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.bfi",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cw_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_cwp",
                        to="employee.position",
                    ),
                ),
                (
                    "firm_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.organization",
                    ),
                ),
                (
                    "office_witness_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_w1",
                        to="employee.employee",
                    ),
                ),
                (
                    "office_witness_1_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_ow1",
                        to="employee.position",
                    ),
                ),
                (
                    "office_witness_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_w2",
                        to="employee.employee",
                    ),
                ),
                (
                    "office_witness_2_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_ow2",
                        to="employee.position",
                    ),
                ),
                (
                    "office_witness_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_w3",
                        to="employee.employee",
                    ),
                ),
                (
                    "office_witness_3_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_ow3",
                        to="employee.position",
                    ),
                ),
                (
                    "office_witness_4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_w4",
                        to="employee.employee",
                    ),
                ),
                (
                    "office_witness_4_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_ow4",
                        to="employee.position",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentExitBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("exit_date", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "exit_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("u_sa_maag_amount", models.IntegerField(blank=True, null=True)),
                (
                    "check_pass_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "check_pass_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "disbursement_assessment_amount",
                    models.IntegerField(blank=True, null=True),
                ),
                ("check_pass_amount", models.IntegerField(blank=True, null=True)),
                ("contentment_amount", models.IntegerField(blank=True, null=True)),
                ("mu_aa_ka", models.IntegerField(blank=True, null=True)),
                (
                    "marmat_sambhar_fund_amount",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "env_disaster_fund_amount",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "public_participation_percent",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "public_participation_amount",
                    models.IntegerField(blank=True, null=True),
                ),
                ("reinstatement_tex", models.IntegerField(blank=True, null=True)),
                ("advance_income_tex", models.IntegerField(blank=True, null=True)),
                (
                    "withdrawal_eligible_amount",
                    models.IntegerField(blank=True, null=True),
                ),
                ("remark", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="peb_approve_emp",
                        to="employee.employee",
                    ),
                ),
                (
                    "approved_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="peb_approve_position",
                        to="employee.position",
                    ),
                ),
                (
                    "check_pass_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                    ),
                ),
                (
                    "check_pass_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.position",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.installment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_execution.projectexecution",
                    ),
                ),
                (
                    "ready_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="peb_ready_emp",
                        to="employee.employee",
                    ),
                ),
                (
                    "ready_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="peb_ready_position",
                        to="employee.position",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="peb_submit_emp",
                        to="employee.employee",
                    ),
                ),
                (
                    "submitted_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="peb_submit_position",
                        to="employee.position",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeasuringBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "measuring_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("page_no", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "measuring_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "measuring_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "total_amount",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "previous_measuring_book_amount",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "this_measuring_book_amount",
                    models.IntegerField(blank=True, null=True),
                ),
                ("result_obtained_so_far", models.IntegerField(blank=True, null=True)),
                ("rate_in_list", models.IntegerField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("breath", models.IntegerField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.projectactivity",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mb_approved_emp",
                        to="employee.employee",
                    ),
                ),
                (
                    "approved_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mb_ab_position",
                        to="employee.position",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mb_checked_emp",
                        to="employee.employee",
                    ),
                ),
                (
                    "checked_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mb_cb_position",
                        to="employee.position",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.organization",
                    ),
                ),
                (
                    "contractor_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cp_position",
                        to="employee.position",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "measured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mb_measured_emp",
                        to="employee.employee",
                    ),
                ),
                (
                    "measured_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mb_position",
                        to="employee.position",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpenseTypeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.expansetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EstimationSubmitAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("is_estimate_submitted", models.BooleanField(default=False)),
                (
                    "estimate_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "estimate_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_cited", models.BooleanField(default=False)),
                ("cited_date", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cited_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_recommended", models.BooleanField(default=False)),
                (
                    "recommended_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "recommended_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_accounting_opinion_submitted", models.BooleanField(default=False)),
                (
                    "accounting_opinion_submitted_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "accounting_opinion_submitted_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "accounting_opinion",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "approved_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "approved_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "approve_opinion",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "accounting_opinion_submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_accounting_opinion_submitted_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "accounting_opinion_submitted_by_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_accounting_opinion_submitted_by_post",
                        to="employee.position",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_esa_approved_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "approved_by_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_esa_post",
                        to="employee.position",
                    ),
                ),
                (
                    "cited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_cited_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "cited_by_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_cited_by_post",
                        to="employee.position",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estimated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_estimated_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "estimated_by_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_estimated_by_post",
                        to="employee.position",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_estimation_as",
                        to="plan_execution.projectexecution",
                    ),
                ),
                (
                    "recommended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_recommended_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "recommended_by_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_recommended_by_post",
                        to="employee.position",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BailType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
