# Generated by Django 4.2.3 on 2023-07-14 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0008_country_language_nationality_taxpayer_religion_and_more"),
        ("project_planning", "0025_projectproposedtype"),
        (
            "plan_execution",
            "0006_accountingtopic_installment_tenderpurchasebranch_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumerFormulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("print_custom_report", models.BooleanField(default=False)),
                (
                    "first_time_publish",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "first_time_publish_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("form_amount", models.CharField(blank=True, max_length=50, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("chairman", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "established_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "report_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "report_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("invoice_no", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "project_current_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "previous_work",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "detail_from_office_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "detail_from_office_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "office_lecture",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("opinion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "positive_effect",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("other", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "project_related_other",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "consumer_committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.consumercommittee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emp_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.position",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
