# Generated by Django 4.2.3 on 2023-07-14 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_execution", "0007_consumerformulation"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumerformulation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_execution.projectexecution",
            ),
        ),
    ]
