# Generated by Django 4.2.3 on 2023-07-15 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("formulate_plan", "0008_rename_is_prioritization_workproject_is_prioritized"),
        ("project_planning", "0025_projectproposedtype"),
        ("employee", "0008_country_language_nationality_taxpayer_religion_and_more"),
        ("base_model", "0007_documenttype"),
        ("plan_execution", "0008_consumerformulation_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingMaterialDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("material", models.CharField(blank=True, max_length=255, null=True)),
                ("result", models.CharField(blank=True, max_length=255, null=True)),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.budgetsource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstallmentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                ("date_eng", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.CharField(blank=True, max_length=255, null=True)),
                ("percent", models.CharField(blank=True, max_length=255, null=True)),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.installment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaintenanceArrangement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.CharField(blank=True, max_length=255, null=True)),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonitoringCommitteeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "member_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("phone_no", models.CharField(blank=True, max_length=15, null=True)),
                ("present", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitor_member_position",
                        to="employee.position",
                    ),
                ),
                (
                    "member_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.position",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserCommitteeMonitoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("project_amount", models.IntegerField(blank=True, null=True)),
                ("assessment_amount", models.IntegerField(blank=True, null=True)),
                (
                    "amount_payable_as_per_assessment",
                    models.IntegerField(blank=True, null=True),
                ),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                ("date_eng", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "meeting_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("proposal_1", models.CharField(blank=True, max_length=255, null=True)),
                ("proposal_2", models.CharField(blank=True, max_length=255, null=True)),
                ("proposal_3", models.CharField(blank=True, max_length=255, null=True)),
                ("print_custom_report", models.BooleanField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monitor_committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.monitoringcommitteedetail",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "revision_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "revision_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("process_start_ward", models.IntegerField(blank=True, null=True)),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "project_name_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "work_proposer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("उपभोक्ता समिति / टोल", "उपभोक्ता समिति / टोल"),
                            ("वडा", "वडा"),
                            ("न.पा./गा.पा.", "न.पा./गा.पा."),
                            ("अन्य", "अन्य"),
                        ],
                        max_length=55,
                        null=True,
                    ),
                ),
                ("first_trimester", models.IntegerField(blank=True, null=True)),
                ("second_trimester", models.IntegerField(blank=True, null=True)),
                ("third_trimester", models.IntegerField(blank=True, null=True)),
                ("fourth_trimester", models.IntegerField(blank=True, null=True)),
                ("is_multi_year_plan", models.BooleanField(default=False)),
                ("first_year", models.IntegerField(blank=True, null=True)),
                ("second_year", models.IntegerField(blank=True, null=True)),
                ("third_year", models.IntegerField(blank=True, null=True)),
                ("forth_year", models.IntegerField(blank=True, null=True)),
                ("fifth_year", models.IntegerField(blank=True, null=True)),
                ("other", models.IntegerField(blank=True, null=True)),
                ("latitude", models.CharField(blank=True, max_length=100, null=True)),
                ("longitude", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "appropriated_amount",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("overhead", models.CharField(blank=True, max_length=20, null=True)),
                ("contingency", models.CharField(blank=True, max_length=20, null=True)),
                ("mu_aa_ka", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "public_charity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "maintenance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "disaster_mgmt_fund",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "total_estimate",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "self_payment",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=100, null=True)),
                ("karmagat", models.IntegerField(blank=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base_model.address",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "priority_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.prioritytype",
                    ),
                ),
                (
                    "project_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.projectlevel",
                    ),
                ),
                (
                    "project_nature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.projectnature",
                    ),
                ),
                (
                    "project_start_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.projectstartdecision",
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.projecttype",
                    ),
                ),
                (
                    "strategic_sign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.strategicsign",
                    ),
                ),
                (
                    "subject_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.subjectarea",
                    ),
                ),
                (
                    "work_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="formulate_plan.projectworktype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProbabilityStudyApprove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "consumer_benefits",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "engineer_survey_to_start_future",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recommender_opinion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "approvers_opinion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approved_amount_percent", models.IntegerField(blank=True, null=True)),
                ("decision", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "submission_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "submission_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("check_date", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "check_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recommendation_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recommendation_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "approved_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "approved_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "to_approve_submission_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "to_approve_submission_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "to_approve_check_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "to_approve_check_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "to_approve_recommendation_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "to_approve_recommendation_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "to_approve_approved_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "to_approve_approved_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("invoice_no", models.CharField(blank=True, max_length=255, null=True)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("pa_na", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emp_approved_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "approved_date_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_date_by_position_emp",
                        to="employee.position",
                    ),
                ),
                (
                    "check_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emp_check_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "check_date_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="check_date_by_position_emp",
                        to="employee.position",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "final_report_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="final_report_approved_by_emp",
                        to="employee.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_execution.projectexecution",
                    ),
                ),
                (
                    "project_selection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.selectionfeasibility",
                    ),
                ),
                (
                    "recommendation_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emp_recommendation_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "recommendation_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_by_position_emp",
                        to="employee.position",
                    ),
                ),
                (
                    "submission_date_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emp_submission_date_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "submission_date_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.position",
                    ),
                ),
                (
                    "to_approve_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emp_to_approve_approved_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "to_approve_approved_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="to_approve_approved_by_position_emp",
                        to="employee.position",
                    ),
                ),
                (
                    "to_approve_check_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emp_to_approve_check_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "to_approve_check_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="to_approve_check_by_position_emp",
                        to="employee.position",
                    ),
                ),
                (
                    "to_approve_recommendation_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emp_to_approve_recommendation_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "to_approve_recommendation_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="to_approve_recommendation_by_position_emp",
                        to="employee.position",
                    ),
                ),
                (
                    "to_approve_submission_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emp_to_approve_submission_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "to_approve_submission_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="to_approve_submission_by_position_emp",
                        to="employee.position",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OpeningContractAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("cha_no", models.CharField(blank=True, max_length=255, null=True)),
                ("pa_no", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                ("date_eng", models.CharField(blank=True, max_length=255, null=True)),
                ("account_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bodarth", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contract_ch_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contract_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contract_pa_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bodarth_1", models.CharField(blank=True, max_length=255, null=True)),
                ("bodarth_2", models.CharField(blank=True, max_length=255, null=True)),
                ("day", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contract_account_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("print_custom_report", models.BooleanField(default=False)),
                (
                    "project_contract_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_contract_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_contract_start_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_contract_start_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_completion_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_completion_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contract_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "present_benefit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "absent_benefit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_start_experience",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_experience",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "arrangements_for_taking_care_of_repairs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "repairs_by_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "committee_witness",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user_committee_secretary",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mandate_ch_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mandate_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mandate_date_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mandate_pa_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mandate_bodarth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mandate_employee",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mandate_employee_position",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ward_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.bfi",
                    ),
                ),
                (
                    "building_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.buildingmaterialdetail",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installment_detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.installmentdetail",
                    ),
                ),
                (
                    "maintenance_arrangement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.maintenancearrangement",
                    ),
                ),
                (
                    "office_side_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_side_1_emp",
                        to="employee.employee",
                    ),
                ),
                (
                    "office_side_1_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_side_1_position",
                        to="employee.position",
                    ),
                ),
                (
                    "office_side_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_side_2_emp",
                        to="employee.employee",
                    ),
                ),
                (
                    "office_side_2_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_side_2_position",
                        to="employee.position",
                    ),
                ),
                (
                    "office_side_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_side_3_emp",
                        to="employee.employee",
                    ),
                ),
                (
                    "office_side_3_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_side_3_position",
                        to="employee.position",
                    ),
                ),
                (
                    "office_side_4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_side_4_emp",
                        to="employee.employee",
                    ),
                ),
                (
                    "office_side_4_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_side_4_position",
                        to="employee.position",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
