# Generated by Django 4.2.3 on 2023-07-15 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_execution", "0009_buildingmaterialdetail_installmentdetail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttender",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_tender",
                to="plan_execution.projectexecution",
            ),
        ),
    ]
