# Generated by Django 4.2.3 on 2023-07-15 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_country_language_nationality_taxpayer_religion_and_more"),
        ("plan_execution", "0010_alter_projecttender_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectrevision",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plan_execution.projectexecution",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="member_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.positionlevel",
            ),
        ),
    ]
