# Generated by Django 4.2.3 on 2023-07-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulate_plan", "0008_rename_is_prioritization_workproject_is_prioritized"),
        ("plan_execution", "0011_projectrevision_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectrevision",
            name="work_group",
        ),
        migrations.AddField(
            model_name="projectrevision",
            name="work_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="formulate_plan.workclass",
            ),
        ),
    ]
