# Generated by Django 4.2.3 on 2023-07-16 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_country_language_nationality_taxpayer_religion_and_more"),
        ("project_planning", "0025_projectproposedtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan_execution", "0012_remove_projectrevision_work_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCommitteeDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("document", models.FileField(upload_to="user_committee_docs/")),
                (
                    "document_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "document_size",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserCommitteeProjectWorkComplete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("ch_no", models.CharField(blank=True, max_length=100, null=True)),
                ("pa_no", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "project_complete_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "project_complete_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("account_no", models.CharField(blank=True, max_length=100, null=True)),
                ("bodarth", models.CharField(blank=True, max_length=100, null=True)),
                ("print_custom_report", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ucp_approved_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "approved_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ucp_approved_by_position",
                        to="employee.position",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.bfi",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.projectexecution",
                    ),
                ),
                (
                    "project_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.usercommitteedocuments",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ucp_submitted_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "submitted_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ucp_submitted_by_position",
                        to="employee.position",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
