# Generated by Django 4.2.3 on 2023-07-20 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_alter_taxpayer_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0026_unit_code"),
        ("plan_execution", "0013_usercommitteedocuments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositMandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "mandate_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("तोक आदेशबाट", "तोक आदेशबाट"),
                            ("विनियोजित बजेटबाट", "विनियोजित बजेटबाट"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                ("order_date_eng", models.DateField(blank=True, null=True)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("invoice_date_eng", models.DateField(blank=True, null=True)),
                ("invoice_no", models.CharField(blank=True, max_length=32, null=True)),
                ("latter_no", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "work_complete_date",
                    models.DateField(blank=True, max_length=32, null=True),
                ),
                (
                    "work_complete_date_eng",
                    models.DateField(blank=True, max_length=32, null=True),
                ),
                (
                    "report_custom_print",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("opinion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nominated_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dm_nominated_employees",
                        to="employee.employee",
                    ),
                ),
                (
                    "nominated_employee_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dm_nominated_employees_position",
                        to="employee.position",
                    ),
                ),
                (
                    "order_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dm_order_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "order_by_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dm_order_by_position",
                        to="employee.position",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
