# Generated by Django 4.2.3 on 2023-07-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_execution", "0014_depositmandate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositmandate",
            name="report_custom_print",
            field=models.BooleanField(default=False),
        ),
    ]
