# Generated by Django 4.2.3 on 2023-07-22 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0011_alter_taxpayer_gender"),
        ("plan_execution", "0016_alter_depositmandate_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionalCollaborationNominatedStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("remarks", models.CharField(blank=True, max_length=100, null=True)),
                ("serial_number", models.IntegerField(blank=True, null=True)),
                (
                    "employee_name_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "employee_position_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "employee_name_remarks",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.position",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstitutionalCollaborationMandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "opinion_detail",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("invoice_number", models.DateField(blank=True, null=True)),
                ("invoice_number_eng", models.DateField(blank=True, null=True)),
                ("project_complete_date", models.DateField(blank=True, null=True)),
                ("project_complete_date_eng", models.DateField(blank=True, null=True)),
                (
                    "mandate_invoice_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mandate_letter",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
