# Generated by Django 4.2.3 on 2023-07-22 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_execution", "0017_institutionalcollaborationnominatedstaff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionalcollaborationmandate",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plan_execution.projectexecution",
            ),
        ),
    ]
