# Generated by Django 4.2.3 on 2023-07-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_execution", "0019_projectreportfinishedandupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectreportfinishedandupdate",
            name="karmagat",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
