# Generated by Django 4.2.1 on 2023-07-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_execution', '0022_templatefieldmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateFieldMapping',
        ),
    ]
