# Generated by Django 4.2.3 on 2023-07-29 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_execution", "0023_delete_templatefieldmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfinishedbailreturn",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_work_finish",
                to="plan_execution.projectexecution",
            ),
        ),
    ]
