# Generated by Django 4.2.3 on 2023-08-06 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan_execution", "0025_alter_openingcontractaccount_installment_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("task", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("सुचारु नभएको", "सुचारु नभएको"),
                            ("चालु अवस्था", "चालु अवस्था"),
                            ("सम्पन्न भएको", "सम्पन्न भएको"),
                        ],
                        default="सुचारु नभएको",
                        max_length=200,
                    ),
                ),
                ("weight", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
