# Generated by Django 4.1 on 2023-08-31 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan_execution", "0028_officialprocess"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectExecutionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=500, null=True)),
                ("document", models.FileField(upload_to="project_execution/")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_execution_document",
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
