# Generated by Django 4.1 on 2023-08-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_execution", "0029_projectexecutiondocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectexecutiondocument",
            name="doc_size",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="projectexecutiondocument",
            name="doc_type",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="projectexecutiondocument",
            name="name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
