# Generated by Django 4.2.1 on 2023-10-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0032_alter_projectbidcollection_bail_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="officialprocess",
            name="status_of_model",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="accountingtopic",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="bailtype",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="benefiteddetail",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="budgetallocationdetail",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="buildingmaterialdetail",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="depositmandate",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="estimationsubmitacceptance",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="expensetypedetail",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="installment",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="installmentdetail",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="institutionalcollaborationmandate",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="institutionalcollaborationnominatedstaff",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="maintenancearrangement",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="measuringbook",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="openingcontractaccount",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="paymentexitbill",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="planstartdecision",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="probabilitystudyapprove",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectbidcollection",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectdarbhaubid",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectdeadline",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectexecutiondocument",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectfinishedbailreturn",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectmobilization",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectphysicaldescription",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="projectunitdetail",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="startpmsprocess",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="tenderpurchasebranch",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="usercommitteedocuments",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="usercommitteeprojectworkcomplete",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
