# Generated by Django 4.2.1 on 2023-10-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0040_alter_accounttitlemanagement_parent"),
        ("plan_execution", "0033_officialprocess_status_of_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetallocationdetail",
            name="expense_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocated_budget_details",
                to="project_planning.accounttitlemanagement",
            ),
        ),
    ]
