# Generated by Django 4.2.1 on 2023-11-19 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0054_alter_project_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan_execution", "0035_populate_startpms_process"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCommentRemarkFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="project_comment_remarks/")),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.BooleanField(blank=True, default=True)),
            ],
            options={
                "verbose_name": "Project Comment Remark File",
                "verbose_name_plural": "Project Comment Remark Files",
            },
        ),
        migrations.CreateModel(
            name="ProjectComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_draft", models.BooleanField(default=False)),
                ("is_signed", models.BooleanField(default=False)),
                (
                    "process_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "send_for",
                    models.CharField(
                        choices=[
                            ("P", "Preparation"),
                            ("V", "Verification"),
                            ("A", "Authorization"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "remark_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="project_comment",
                        to="plan_execution.projectcommentremarkfile",
                    ),
                ),
                (
                    "request_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "send_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_comment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "start_pms_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.startpmsprocess",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
