# Generated by Django 4.2.1 on 2023-11-21 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan_execution", "0037_alter_projectcomment_process_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcomment",
            name="last_status_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectcomment",
            name="last_status_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_status_updated_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectcomment",
            name="project_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_execution.projectexecution",
            ),
        ),
        migrations.AlterField(
            model_name="projectcomment",
            name="process_name",
            field=models.CharField(
                choices=[
                    ("म्याद थप", "म्याद थप"),
                    ("निकासा", "निकासा"),
                    ("इस्टिमेट पेश/स्वीकृत सम्बन्धि", "इस्टिमेट पेश/स्वीकृत सम्बन्धि"),
                    ("मोबिलैजेशन", "मोबिलैजेशन"),
                    ("योजना संशोधन", "योजना संशोधन"),
                    ("कार्य सम्पन्न विवरण", "कार्य सम्पन्न विवरण"),
                    ("नापी किताब सम्बन्धि", "नापी किताब सम्बन्धि"),
                    ("टेन्डर सम्बन्धि", "टेन्डर सम्बन्धि"),
                    ("बोलपत्र संकलन", "बोलपत्र संकलन"),
                    ("दरभाउ पत्र/बोलपत्र स्वीकृत", "दरभाउ पत्र/बोलपत्र स्वीकृत"),
                    ("सम्झौता सम्बन्धि", "सम्झौता सम्बन्धि"),
                    ("निकासा विल भुक्तानी सम्बन्धि", "निकासा विल भुक्तानी सम्बन्धि"),
                    ("उपभोक्ता छनौट/गठन", "उपभोक्ता छनौट/गठन"),
                    ("सम्भाव्यता अध्ययन/स्वीकृत", "सम्भाव्यता अध्ययन/स्वीकृत"),
                    ("सम्झौता/खाता खोलिदिन सम्बन्धि", "सम्झौता/खाता खोलिदिन सम्बन्धि"),
                    ("अनुगमन", "अनुगमन"),
                    ("टिप्पणी र आदेश", "टिप्पणी र आदेश"),
                    ("अमानत कार्यादेश", "अमानत कार्यादेश"),
                    ("कार्य सम्पन्न तथा फरफारक", "कार्य सम्पन्न तथा फरफारक"),
                    ("मनोनित कर्मचारी", "मनोनित कर्मचारी"),
                    ("कार्यादेश", "कार्यादेश"),
                ],
                default="नापी किताब सम्बन्धि",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="IndividualProjectComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("comment_date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "commented_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individual_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_comments",
                        to="plan_execution.projectcomment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="projectcommentremarkfile",
            name="individual_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="individual_comment_files",
                to="plan_execution.individualprojectcomment",
            ),
        ),
    ]
