# Generated by Django 4.2.1 on 2023-11-21 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0039_update_project_comment_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectcomment",
            name="project",
        ),
    ]
