# Generated by Django 4.2.1 on 2023-11-21 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan_execution", "0040_remove_projectcomment_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectcomment",
            old_name="project_execution",
            new_name="project",
        ),
        migrations.AddField(
            model_name="projectcomment",
            name="allowed_to_comment",
            field=models.ManyToManyField(
                blank=True,
                related_name="commentable_project_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
