# Generated by Django 4.2.1 on 2023-11-21 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0041_rename_project_execution_projectcomment_project_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectcomment",
            old_name="allowed_to_comment",
            new_name="users_allowed_to_comment",
        ),
    ]
