# Generated by Django 4.2.1 on 2023-11-23 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employee", "0016_alter_country_code_alter_country_created_by_and_more"),
        ("project_planning", "0041_alter_accounttitlemanagement_code_and_more"),
        ("project", "0055_alter_district_code_alter_district_created_by_and_more"),
        ("plan_execution", "0043_update_users_allowed_to_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingtopic",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="accountingtopic",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="accountingtopic",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="accountingtopic",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="accountingtopic",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="accountingtopic",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="accountingtopic",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="accountingtopic",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="bailtype",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="bailtype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="bailtype",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="bailtype",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="bailtype",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="bailtype",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="bailtype",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="bailtype",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="benefiteddetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="benefiteddetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="benefiteddetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="budgetallocationdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="budgetallocationdetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="budgetallocationdetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmaterialdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmaterialdetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmaterialdetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="ठेगाना",
                max_length=100,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="chairman",
            field=models.CharField(
                blank=True,
                help_text="अध्यक्ष",
                max_length=100,
                null=True,
                verbose_name="Chairman",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=100,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="consumer_committee",
            field=models.ForeignKey(
                blank=True,
                help_text="उपभोक्ता समिति",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.consumercommittee",
                verbose_name="Consumer Committee",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="detail_from_office_date",
            field=models.CharField(
                blank=True,
                help_text="कार्यालयबाट विवरण मिति",
                max_length=255,
                null=True,
                verbose_name="Detail From Office Date",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="detail_from_office_date_eng",
            field=models.CharField(
                blank=True,
                help_text="कार्यालयबाट विवरण मिति (AD)",
                max_length=255,
                null=True,
                verbose_name="Detail From Office Date (AD)",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="emp_name",
            field=models.ForeignKey(
                blank=True,
                help_text="कर्मचारी",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="established_date",
            field=models.CharField(
                blank=True,
                help_text="स्थापना मिति",
                max_length=100,
                null=True,
                verbose_name="Established Date",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="first_time_publish",
            field=models.CharField(
                blank=True,
                help_text="पहिलो पटक प्रकाशित मिति",
                max_length=50,
                null=True,
                verbose_name="First Published Date",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="first_time_publish_eng",
            field=models.CharField(
                blank=True,
                help_text="पहिलो पटक प्रकाशित मिति (AD)",
                max_length=50,
                null=True,
                verbose_name="First Published Date (AD)",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="form_amount",
            field=models.CharField(
                blank=True,
                help_text="फारम दस्तुर रकम",
                max_length=50,
                null=True,
                verbose_name="Form Amount",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="invoice_no",
            field=models.CharField(
                blank=True,
                help_text="बिल नं",
                max_length=100,
                null=True,
                verbose_name="Invoice No",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="office_lecture",
            field=models.CharField(
                blank=True,
                help_text="कार्यालय बैठक",
                max_length=255,
                null=True,
                verbose_name="Office Lecture",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="opinion",
            field=models.CharField(
                blank=True,
                help_text="अभिप्राय",
                max_length=255,
                null=True,
                verbose_name="Opinion",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="other",
            field=models.CharField(
                blank=True,
                help_text="अन्य",
                max_length=255,
                null=True,
                verbose_name="Other",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="फोन",
                max_length=100,
                null=True,
                verbose_name="Phone",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="position",
            field=models.ForeignKey(
                blank=True,
                help_text="पद",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.position",
                verbose_name="Position",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="positive_effect",
            field=models.CharField(
                blank=True,
                help_text="सकारात्मक प्रभाव",
                max_length=255,
                null=True,
                verbose_name="Positive Effect",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="previous_work",
            field=models.CharField(
                blank=True,
                help_text="अघिल्लो कार्य",
                max_length=255,
                null=True,
                verbose_name="Previous Work",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="print_custom_report",
            field=models.BooleanField(
                default=False,
                help_text="कस्टम रिपोर्ट प्रिन्ट गर्नुहोस्",
                verbose_name="Custom Report Print",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना कार्यान्वयन",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_execution.projectexecution",
                verbose_name="Project Execution",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="project_current_status",
            field=models.CharField(
                blank=True,
                help_text="योजना चालु अवस्था",
                max_length=200,
                null=True,
                verbose_name="Project Current Status",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="project_related_other",
            field=models.CharField(
                blank=True,
                help_text="योजना सम्बन्धी अन्य",
                max_length=255,
                null=True,
                verbose_name="Project Related Other",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="report_date",
            field=models.CharField(
                blank=True,
                help_text="प्रतिवेदन मिति",
                max_length=100,
                null=True,
                verbose_name="Report Date",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="report_date_eng",
            field=models.CharField(
                blank=True,
                help_text="प्रतिवेदन मिति (AD)",
                max_length=100,
                null=True,
                verbose_name="Report Date (AD)",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="depositmandate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="depositmandate",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="depositmandate",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="estimationsubmitacceptance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="estimationsubmitacceptance",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="estimationsubmitacceptance",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="expensetypedetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="expensetypedetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="expensetypedetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="individualprojectcomment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="individualprojectcomment",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="individualprojectcomment",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="individualprojectcomment",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="installment",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="installment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="installment",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="installment",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="installment",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="installment",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="installment",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="installment",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="installmentdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="installmentdetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="installmentdetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalcollaborationmandate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalcollaborationmandate",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalcollaborationmandate",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalcollaborationnominatedstaff",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="institutionalcollaborationnominatedstaff",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="institutionalcollaborationnominatedstaff",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancearrangement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancearrangement",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancearrangement",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="measuringbook",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="measuringbook",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="measuringbook",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="officialprocess",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="officialprocess",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="officialprocess",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="openingcontractaccount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="openingcontractaccount",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="openingcontractaccount",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="paymentexitbill",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="paymentexitbill",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="paymentexitbill",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="planstartdecision",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="planstartdecision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="planstartdecision",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="planstartdecision",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="planstartdecision",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="planstartdecision",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="planstartdecision",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="planstartdecision",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="probabilitystudyapprove",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="probabilitystudyapprove",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="probabilitystudyapprove",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectbidcollection",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projectbidcollection",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectbidcollection",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectcomment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projectcomment",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectcomment",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectdarbhaubid",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projectdarbhaubid",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectdarbhaubid",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectdeadline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projectdeadline",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectdeadline",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="appropriated_amount",
            field=models.CharField(
                blank=True,
                help_text="अवस्थित रकम",
                max_length=100,
                null=True,
                verbose_name="Appropriated Amount",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="contingency",
            field=models.CharField(
                blank=True,
                help_text="आकस्मिक",
                max_length=20,
                null=True,
                verbose_name="Contingency",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="disaster_mgmt_fund",
            field=models.CharField(
                blank=True,
                help_text="प्रकोप व्यवस्थापन कोष",
                max_length=100,
                null=True,
                verbose_name="Disaster Management Fund",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="fifth_year",
            field=models.IntegerField(
                blank=True, help_text="पाँचौ वर्ष", null=True, verbose_name="Fifth Year"
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="first_trimester",
            field=models.IntegerField(
                blank=True,
                help_text="प्रथम त्रैमासिक",
                null=True,
                verbose_name="First Trimester",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="first_year",
            field=models.IntegerField(
                blank=True, help_text="प्रथम वर्ष", null=True, verbose_name="First Year"
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="forth_year",
            field=models.IntegerField(
                blank=True, help_text="चौथो वर्ष", null=True, verbose_name="Fourth Year"
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="fourth_trimester",
            field=models.IntegerField(
                blank=True,
                help_text="चौथो त्रैमासिक",
                null=True,
                verbose_name="Fourth Trimester",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="is_executing",
            field=models.BooleanField(
                default=True, help_text="कार्यान्वयन गर्दै", verbose_name="Executing"
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="is_multi_year_plan",
            field=models.BooleanField(
                default=False,
                help_text="बहु वर्षीय योजना",
                verbose_name="Multi Year Plan",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="latitude",
            field=models.CharField(
                blank=True,
                help_text="अक्षांश",
                max_length=100,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="longitude",
            field=models.CharField(
                blank=True,
                help_text="देशान्तर",
                max_length=100,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="maintenance",
            field=models.CharField(
                blank=True,
                help_text="रखरखाव",
                max_length=100,
                null=True,
                verbose_name="Maintenance",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="mu_aa_ka",
            field=models.CharField(
                blank=True,
                help_text="मु आ क",
                max_length=20,
                null=True,
                verbose_name="Mu Aa Ka",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="other",
            field=models.IntegerField(
                blank=True, help_text="अन्य", null=True, verbose_name="Other"
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="overhead",
            field=models.CharField(
                blank=True,
                help_text="ओभरहेड",
                max_length=20,
                null=True,
                verbose_name="Overhead",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="plan_start_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना सुरु गर्ने निर्णय",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plan_execution.planstartdecision",
                verbose_name="Plan Start Decision",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="कार्यक्रम",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.program",
                verbose_name="Program",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="project",
            field=models.OneToOneField(
                blank=True,
                help_text="योजना",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="project_nature",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना प्रकृति",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.projectnature",
                verbose_name="Project Nature",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="project_priority",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना प्राथमिकता",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.prioritytype",
                verbose_name="Project Priority",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="project_type",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.projecttype",
                verbose_name="Project Type",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="public_charity",
            field=models.CharField(
                blank=True,
                help_text="सार्वजनिक दान",
                max_length=100,
                null=True,
                verbose_name="Public Charity",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="second_trimester",
            field=models.IntegerField(
                blank=True,
                help_text="दोस्रो त्रैमासिक",
                null=True,
                verbose_name="Second Trimester",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="second_year",
            field=models.IntegerField(
                blank=True,
                help_text="दोस्रो वर्ष",
                null=True,
                verbose_name="Second Year",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="self_payment",
            field=models.CharField(
                blank=True,
                help_text="स्वयं भुक्तानी",
                max_length=100,
                null=True,
                verbose_name="Self Payment",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="start_pms_process",
            field=models.ForeignKey(
                blank=True,
                help_text="सञ्चालन प्रकृया",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plan_execution.startpmsprocess",
                verbose_name="Operating Procedures",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="strategic_sign",
            field=models.ForeignKey(
                blank=True,
                help_text="रणनीतिक चिन्ह",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.strategicsign",
                verbose_name="Strategic Sign",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="subject_area",
            field=models.ForeignKey(
                blank=True,
                help_text="विषयगत कार्यक्षेत्र",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.subjectarea",
                verbose_name="Subject Area",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="third_trimester",
            field=models.IntegerField(
                blank=True,
                help_text="तेस्रो त्रैमासिक",
                null=True,
                verbose_name="Third Trimester",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="third_year",
            field=models.IntegerField(
                blank=True,
                help_text="तेस्रो वर्ष",
                null=True,
                verbose_name="Third Year",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="total_estimate",
            field=models.CharField(
                blank=True,
                help_text="कुल अनुमान",
                max_length=100,
                null=True,
                verbose_name="Total Estimate",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecution",
            name="work_proposer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("उपभोक्ता समिति / टोल", "उपभोक्ता समिति / टोल"),
                    ("वडा", "वडा"),
                    ("न.पा./गा.पा.", "न.पा./गा.पा."),
                    ("अन्य", "अन्य"),
                ],
                help_text="कार्य प्रस्तावक प्रकार",
                max_length=55,
                null=True,
                verbose_name="Work Proposer Type",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecutiondocument",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecutiondocument",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecutiondocument",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectexecutiondocument",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecutiondocument",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecutiondocument",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectfinishedbailreturn",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projectfinishedbailreturn",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectfinishedbailreturn",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectmobilization",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projectmobilization",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectmobilization",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectphysicaldescription",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="projectphysicaldescription",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projectphysicaldescription",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectphysicaldescription",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="projectphysicaldescription",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="projectphysicaldescription",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="projectphysicaldescription",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectunitdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="projectunitdetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="projectunitdetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="startpmsprocess",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="startpmsprocess",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="startpmsprocess",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="startpmsprocess",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="startpmsprocess",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="startpmsprocess",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="startpmsprocess",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="startpmsprocess",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="tenderpurchasebranch",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="tenderpurchasebranch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="tenderpurchasebranch",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="tenderpurchasebranch",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="tenderpurchasebranch",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="tenderpurchasebranch",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="tenderpurchasebranch",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="tenderpurchasebranch",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteedocuments",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteedocuments",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteedocuments",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteeprojectworkcomplete",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteeprojectworkcomplete",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteeprojectworkcomplete",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
    ]
