# Generated by Django 4.2.1 on 2023-11-27 07:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0043_alter_projecttype_parent_alter_subjectarea_parent"),
        ("employee", "0016_alter_country_code_alter_country_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "base_model",
            "0012_alter_address_created_by_alter_address_created_date_and_more",
        ),
        ("formulate_plan", "0015_alter_budgetassurance_amount_and_more"),
        ("plan_execution", "0045_measuringbook_height_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmobilization",
            name="accounting_topic",
        ),
        migrations.RemoveField(
            model_name="projectmobilization",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="projectmobilization",
            name="body",
        ),
        migrations.RemoveField(
            model_name="projectmobilization",
            name="budget_source",
        ),
        migrations.RemoveField(
            model_name="projectmobilization",
            name="remark",
        ),
        migrations.AddField(
            model_name="projectmobilization",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="ठेगाना",
                max_length=100,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="projectmobilization",
            name="comment_no",
            field=models.CharField(
                blank=True,
                help_text="टिप्पणी नं.",
                max_length=50,
                null=True,
                verbose_name="Comment No.",
            ),
        ),
        migrations.AddField(
            model_name="projectmobilization",
            name="date",
            field=models.CharField(
                blank=True,
                help_text="मिति",
                max_length=50,
                null=True,
                verbose_name="Date",
            ),
        ),
        migrations.AddField(
            model_name="projectmobilization",
            name="date_eng",
            field=models.CharField(
                blank=True,
                help_text="मिति (इ.स.)",
                max_length=50,
                null=True,
                verbose_name="Date (AD)",
            ),
        ),
        migrations.AddField(
            model_name="projectmobilization",
            name="mobilization_amount",
            field=models.IntegerField(
                blank=True,
                help_text="योजना संचालन रकम",
                null=True,
                verbose_name="Mobilization Amount",
            ),
        ),
        migrations.AddField(
            model_name="projectmobilization",
            name="print_custom_report",
            field=models.BooleanField(
                default=False,
                help_text="कस्टम रिपोर्ट प्रिन्ट गर्नुहोस्",
                verbose_name="Print Custom Report",
            ),
        ),
        migrations.AddField(
            model_name="projectmobilization",
            name="project_amount",
            field=models.IntegerField(
                blank=True,
                help_text="योजना रकम",
                null=True,
                verbose_name="Project Amount",
            ),
        ),
        migrations.AddField(
            model_name="projectmobilization",
            name="remarks",
            field=models.CharField(
                blank=True,
                help_text="कैफियत",
                max_length=200,
                null=True,
                verbose_name="Remarks",
            ),
        ),
        migrations.AddField(
            model_name="projectrevision",
            name="contingency_percent",
            field=models.CharField(
                blank=True,
                help_text="आकस्मिक प्रतिशत",
                max_length=20,
                null=True,
                verbose_name="Contingency Percent",
            ),
        ),
        migrations.AddField(
            model_name="projectrevision",
            name="maintenance_percent",
            field=models.CharField(
                blank=True,
                help_text="मर्मत सम्भार कोष प्रतिशत",
                max_length=20,
                null=True,
                verbose_name="Maintenance Percent",
            ),
        ),
        migrations.AddField(
            model_name="projectrevision",
            name="mu_aa_ka_percent",
            field=models.CharField(
                blank=True,
                help_text="मु आ क प्रतिशत",
                max_length=20,
                null=True,
                verbose_name="Mu Aa Ka Percent",
            ),
        ),
        migrations.AddField(
            model_name="projectrevision",
            name="public_charity_percent",
            field=models.CharField(
                blank=True,
                help_text="सार्वजनिक चारिटी प्रतिशत",
                max_length=20,
                null=True,
                verbose_name="Public Charity Percent",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="member_name",
            field=models.CharField(
                blank=True,
                help_text="सदस्यको नाम",
                max_length=255,
                null=True,
                verbose_name="Member Name",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="member_position",
            field=models.ForeignKey(
                blank=True,
                help_text="सदस्य पद",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitor_member_position",
                to="employee.position",
                verbose_name="Member Position",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="member_type",
            field=models.ForeignKey(
                blank=True,
                help_text="सदस्य प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.positionlevel",
                verbose_name="Member Type",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="phone_no",
            field=models.CharField(
                blank=True,
                help_text="फोन नं",
                max_length=15,
                null=True,
                verbose_name="Phone No.",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="present",
            field=models.BooleanField(
                default=False, help_text="उपस्थित", verbose_name="Present"
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="projectmobilization",
            name="percent",
            field=models.IntegerField(
                blank=True,
                help_text="प्रतिशत",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Percent",
            ),
        ),
        migrations.AlterField(
            model_name="projectmobilization",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना कार्यान्वयन",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_execution.projectexecution",
                verbose_name="Project Execution",
            ),
        ),
        migrations.AlterField(
            model_name="projectmobilization",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="ठेगाना",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base_model.address",
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="appropriated_amount",
            field=models.CharField(
                blank=True,
                help_text="अवस्थित रकम",
                max_length=100,
                null=True,
                verbose_name="Appropriated Amount",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="contingency",
            field=models.CharField(
                blank=True,
                help_text="आकस्मिक",
                max_length=20,
                null=True,
                verbose_name="Contingency",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="disaster_mgmt_fund",
            field=models.CharField(
                blank=True,
                help_text="पर्यावरण तथा विपद् प्रबन्धन कोष",
                max_length=100,
                null=True,
                verbose_name="Environment and Disaster Management Fund",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="fifth_year",
            field=models.IntegerField(
                blank=True, help_text="पाँचौ वर्ष", null=True, verbose_name="Fifth Year"
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="first_trimester",
            field=models.IntegerField(
                blank=True,
                help_text="प्रथम त्रैमासिक",
                null=True,
                verbose_name="First Trimester",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="first_year",
            field=models.IntegerField(
                blank=True, help_text="पहिलो वर्ष", null=True, verbose_name="First Year"
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="forth_year",
            field=models.IntegerField(
                blank=True, help_text="चौथो वर्ष", null=True, verbose_name="Forth Year"
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="fourth_trimester",
            field=models.IntegerField(
                blank=True,
                help_text="चौथो त्रैमासिक",
                null=True,
                verbose_name="Fourth Trimester",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="is_multi_year_plan",
            field=models.BooleanField(
                default=False,
                help_text="बहु वर्षीय योजना हो",
                verbose_name="Is Multi Year Plan",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="karmagat",
            field=models.IntegerField(
                blank=True, help_text="कर्मगत", null=True, verbose_name="Karmagat"
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="latitude",
            field=models.CharField(
                blank=True,
                help_text="अक्षांश",
                max_length=100,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="longitude",
            field=models.CharField(
                blank=True,
                help_text="देशान्तर",
                max_length=100,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="maintenance",
            field=models.CharField(
                blank=True,
                help_text="मर्मत सम्भार कोष",
                max_length=100,
                null=True,
                verbose_name="Maintenance Fund",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="mu_aa_ka",
            field=models.CharField(
                blank=True,
                help_text="मु आ क",
                max_length=20,
                null=True,
                verbose_name="Mu Aa Ka",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="other",
            field=models.IntegerField(
                blank=True, help_text="अन्य", null=True, verbose_name="Other"
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="overhead",
            field=models.CharField(
                blank=True,
                help_text="ओभरहेड",
                max_length=20,
                null=True,
                verbose_name="Overhead",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="priority_type",
            field=models.ForeignKey(
                blank=True,
                help_text="प्राथमिकता प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.prioritytype",
                verbose_name="Priority Type",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="process_start_ward",
            field=models.IntegerField(
                blank=True,
                help_text="प्रक्रिया सुरु वडा",
                null=True,
                verbose_name="Process Start Ward",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना कार्यान्वयन",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plan_execution.projectexecution",
                verbose_name="Project Execution",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना स्तर",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.projectlevel",
                verbose_name="Project Level",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="project_name",
            field=models.CharField(
                blank=True,
                help_text="योजना नाम",
                max_length=50,
                null=True,
                verbose_name="Project Name",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="project_name_eng",
            field=models.CharField(
                blank=True,
                help_text="योजना नाम (Eng)",
                max_length=50,
                null=True,
                verbose_name="Project Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="project_nature",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना स्वभाव",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.projectnature",
                verbose_name="Project Nature",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="project_start_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना सुरु निर्णय",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.projectstartdecision",
                verbose_name="Project Start Decision",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="project_type",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.projecttype",
                verbose_name="Project Type",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="public_charity",
            field=models.CharField(
                blank=True,
                help_text="सार्वजनिक चारिटी",
                max_length=100,
                null=True,
                verbose_name="Public Charity",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="remarks",
            field=models.CharField(
                blank=True,
                help_text="कैफियत",
                max_length=100,
                null=True,
                verbose_name="Remarks",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="revision_date",
            field=models.CharField(
                blank=True,
                help_text="संशोधन मिति",
                max_length=50,
                null=True,
                verbose_name="Revision Date",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="revision_date_eng",
            field=models.CharField(
                blank=True,
                help_text="संशोधन मिति (AD)",
                max_length=50,
                null=True,
                verbose_name="Revision Date (AD)",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="second_trimester",
            field=models.IntegerField(
                blank=True,
                help_text="दोस्रो त्रैमासिक",
                null=True,
                verbose_name="Second Trimester",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="second_year",
            field=models.IntegerField(
                blank=True,
                help_text="दोस्रो वर्ष",
                null=True,
                verbose_name="Second Year",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="self_payment",
            field=models.CharField(
                blank=True,
                help_text="स्वयं भुक्तानी",
                max_length=100,
                null=True,
                verbose_name="Self Payment",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="strategic_sign",
            field=models.ForeignKey(
                blank=True,
                help_text="रणनीतिक चिन्ह",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.strategicsign",
                verbose_name="Strategic Sign",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="subject_area",
            field=models.ForeignKey(
                blank=True,
                help_text="विषय क्षेत्र",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.subjectarea",
                verbose_name="Subject Area",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="third_trimester",
            field=models.IntegerField(
                blank=True,
                help_text="तेस्रो त्रैमासिक",
                null=True,
                verbose_name="Third Trimester",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="third_year",
            field=models.IntegerField(
                blank=True,
                help_text="तेस्रो वर्ष",
                null=True,
                verbose_name="Third Year",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="total_estimate",
            field=models.CharField(
                blank=True,
                help_text="कुल लागत अनुमान",
                max_length=100,
                null=True,
                verbose_name="Total Cost Estimate",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="work_class",
            field=models.ForeignKey(
                blank=True,
                help_text="कार्य वर्ग",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="formulate_plan.workclass",
                verbose_name="Work Class",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="work_proposer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("उपभोक्ता समिति / टोल", "उपभोक्ता समिति / टोल"),
                    ("वडा", "वडा"),
                    ("न.पा./गा.पा.", "न.पा./गा.पा."),
                    ("अन्य", "अन्य"),
                ],
                help_text="कार्य प्रस्तावक प्रकार",
                max_length=55,
                null=True,
                verbose_name="Work Proposer Type",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="amount_payable_as_per_assessment",
            field=models.IntegerField(
                blank=True,
                help_text="मूल्यांकन अनुसार भुक्तानी गर्नु पर्ने रकम",
                null=True,
                verbose_name="Amount Payable As Per Assessment",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="assessment_amount",
            field=models.IntegerField(
                blank=True,
                help_text="मूल्यांकन रकम",
                null=True,
                verbose_name="Assessment Amount",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="date",
            field=models.CharField(
                blank=True,
                help_text="मिति",
                max_length=255,
                null=True,
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="date_eng",
            field=models.CharField(
                blank=True,
                help_text="मिति (AD)",
                max_length=255,
                null=True,
                verbose_name="Date (AD)",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="meeting_address",
            field=models.CharField(
                blank=True,
                help_text="बैठकको ठेगाना",
                max_length=255,
                null=True,
                verbose_name="Meeting Address",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="monitor_committee",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्वाह समिति विवरण",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plan_execution.monitoringcommitteedetail",
                verbose_name="Monitoring Committee Detail",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="print_custom_report",
            field=models.BooleanField(
                default=False,
                help_text="कस्टम रिपोर्ट प्रिन्ट गर्नुहोस्",
                verbose_name="Custom Report Print",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="project_amount",
            field=models.IntegerField(
                blank=True,
                help_text="योजना रकम",
                null=True,
                verbose_name="Project Amount",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="proposal_1",
            field=models.CharField(
                blank=True,
                help_text="प्रस्ताव १",
                max_length=255,
                null=True,
                verbose_name="Proposal 1",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="proposal_2",
            field=models.CharField(
                blank=True,
                help_text="प्रस्ताव २",
                max_length=255,
                null=True,
                verbose_name="Proposal 2",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="proposal_3",
            field=models.CharField(
                blank=True,
                help_text="प्रस्ताव ३",
                max_length=255,
                null=True,
                verbose_name="Proposal 3",
            ),
        ),
        migrations.AlterField(
            model_name="usercommitteemonitoring",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.CreateModel(
            name="ProjectMobilizationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                (
                    "percent",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="प्रतिशत",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Percent",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        blank=True, help_text="रकम", null=True, verbose_name="Amount"
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="कैफियत",
                        max_length=200,
                        null=True,
                        verbose_name="Remarks",
                    ),
                ),
                (
                    "accounting_topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="लेखा शीर्षक",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.accountingtopic",
                        verbose_name="Accounting Topic",
                    ),
                ),
                (
                    "body",
                    models.ForeignKey(
                        blank=True,
                        help_text="निकाय",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.sourcereceipt",
                        verbose_name="Body",
                    ),
                ),
                (
                    "budget_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="बजेट स्रोत",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.budgetsource",
                        verbose_name="Budget Source",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "mobilization",
                    models.ForeignKey(
                        help_text="योजना संचालन",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="plan_execution.projectmobilization",
                        verbose_name="Project Mobilization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
