# Generated by Django 4.2.1 on 2023-11-29 06:27

from django.db import migrations, models


def remove_existing_installment_id(apps, schema_editor):
    Installment = apps.get_model("plan_execution", "Installment")
    db_alias = schema_editor.connection.alias
    Installment.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0046_remove_projectmobilization_accounting_topic_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_existing_installment_id),
    ]
