# Generated by Django 4.2.1 on 2023-11-29 06:27

from django.db import migrations, models


def remove_existing_installment_id(apps, schema_editor):
    Installment = apps.get_model("plan_execution", "Installment")
    db_alias = schema_editor.connection.alias
    Installment.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0047_remove_existing_installments"),
    ]

    operations = [
        migrations.RunPython(remove_existing_installment_id),
        migrations.RemoveField(
            model_name="installment",
            name="id",
        ),
        migrations.AlterField(
            model_name="installment",
            name="code",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
