# Generated by Django 4.2.1 on 2023-12-01 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0046_executiveagency_date_executiveagency_date_eng"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan_execution", "0049_populate_installment_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        blank=True, help_text="रकम", null=True, verbose_name="Amount"
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="कैफियत",
                        max_length=100,
                        null=True,
                        verbose_name="Remarks",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "expense_topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="खर्च शीर्षक",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.accounttitlemanagement",
                        verbose_name="Expense Topic",
                    ),
                ),
                (
                    "payment_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="प्रकार",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.collectpayment",
                        verbose_name="Type",
                    ),
                ),
                (
                    "peb",
                    models.ForeignKey(
                        blank=True,
                        help_text="भुक्तानी निस्कने बिल",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plan_execution.paymentexitbill",
                        verbose_name="Payment Exit Bill",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        help_text="श्रोत",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.sourcereceipt",
                        verbose_name="Source",
                    ),
                ),
                (
                    "subject_work_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="विषय क्षेत्र",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.subjectarea",
                        verbose_name="Subject Work Area",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
