# Generated by Django 4.2.1 on 2023-12-01 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0050_paymentdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdetail",
            name="peb",
            field=models.ForeignKey(
                blank=True,
                help_text="भुक्तानी निस्कने बिल",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_details",
                to="plan_execution.paymentexitbill",
                verbose_name="Payment Exit Bill",
            ),
        ),
    ]
