# Generated by Django 4.2.1 on 2023-12-01 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan_execution", "0051_alter_paymentdetail_peb"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Installment",
            new_name="OldBuggyFuckingInstallmentModel",
        ),
        migrations.AlterField(
            model_name="paymentexitbill",
            name="installment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="peb",
                to="plan_execution.OldBuggyFuckingInstallmentModel",
            ),
        ),
    ]
