# Generated by Django 4.2.1 on 2023-12-01 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0053_projectinstallment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installmentdetail",
            name="installment",
            field=models.ForeignKey(
                blank=True,
                help_text="किस्ता",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plan_execution.projectinstallment",
                verbose_name="Installment",
            ),
        ),
        migrations.AlterField(
            model_name="paymentexitbill",
            name="installment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="peb",
                to="plan_execution.projectinstallment",
            ),
        ),
    ]
