# Generated by Django 4.2.1 on 2023-12-01 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0055_populate_installment_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OldBuggyFuckingInstallmentModel",
        ),
    ]
