# Generated by Django 4.2.1 on 2023-12-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0056_delete_oldbuggyfuckinginstallmentmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercommitteemonitoring",
            name="monitor_committee",
        ),
        migrations.AddField(
            model_name="monitoringcommitteedetail",
            name="user_committee_monitoring",
            field=models.ForeignKey(
                blank=True,
                help_text="उपभोक्ता समिति अनुगमन",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitor_committee",
                to="plan_execution.usercommitteemonitoring",
                verbose_name="User Committee Monitoring",
            ),
        ),
    ]
