# Generated by Django 4.2.1 on 2023-12-06 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0050_consumercommitteemember_voter_start_district"),
        ("plan_execution", "0059_alter_projectexecution_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumerformulation",
            name="selected_consumer_committee",
            field=models.ForeignKey(
                blank=True,
                help_text="छनौट गरिएको उपभोक्ता समिति",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_consumer_committee",
                to="project_planning.consumercommittee",
                verbose_name="Selected Consumer Committee",
            ),
        ),
        migrations.AlterField(
            model_name="consumerformulation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="योजना कार्यान्वयन",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_consumer_formulation",
                to="plan_execution.projectexecution",
                verbose_name="Project Execution",
            ),
        ),
    ]
