# Generated by Django 4.2.1 on 2023-12-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0050_consumercommitteemember_voter_start_district"),
        ("plan_execution", "0061_alter_projectbidcollection_bail_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectmobilizationdetail",
            old_name="body",
            new_name="institution",
        ),
        migrations.RenameField(
            model_name="projectmobilizationdetail",
            old_name="percent",
            new_name="percentage",
        ),
        migrations.AlterField(
            model_name="projectmobilizationdetail",
            name="accounting_topic",
            field=models.ForeignKey(
                blank=True,
                help_text="लेखा शीर्षक",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.accounttitlemanagement",
                verbose_name="Accounting Topic",
            ),
        ),
    ]
