# Generated by Django 4.2.1 on 2023-12-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0064_remove_openingcontractaccount_building_material_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projectexecution",
            name="contingency_percent",
            field=models.CharField(
                blank=True,
                help_text="आकस्मिक प्रतिशत",
                max_length=20,
                null=True,
                verbose_name="Contingency Percent",
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="disaster_mgmt_fund_percent",
            field=models.CharField(
                blank=True,
                help_text="प्रकोप व्यवस्थापन कोष प्रतिशत",
                max_length=20,
                null=True,
                verbose_name="Disaster Management Fund Percent",
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="maintenance_percent",
            field=models.CharField(
                blank=True,
                help_text="रखरखाव प्रतिशत",
                max_length=20,
                null=True,
                verbose_name="Maintenance Percent",
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="mu_aa_ka_percent",
            field=models.CharField(
                blank=True,
                help_text="मु आ क प्रतिशत",
                max_length=20,
                null=True,
                verbose_name="Mu Aa Ka Percent",
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="public_charity_percent",
            field=models.CharField(
                blank=True,
                help_text="सार्वजनिक दान प्रतिशत",
                max_length=20,
                null=True,
                verbose_name="Public Charity Percent",
            ),
        ),
        migrations.AddField(
            model_name="projectexecution",
            name="subtotal_estimate",
            field=models.CharField(
                blank=True,
                help_text="उपयोगकर्ता अनुमान",
                max_length=100,
                null=True,
                verbose_name="Subtotal Estimate",
            ),
        ),
    ]
