# Generated by Django 4.2.1 on 2023-12-11 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0065_projectexecution_contingency_percent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="installmentdetail",
            old_name="amount",
            new_name="nikasha_total_amount",
        ),
        migrations.RenameField(
            model_name="installmentdetail",
            old_name="percent",
            new_name="public_participation_percent",
        ),
    ]
