# Generated by Django 4.2.1 on 2023-12-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0050_consumercommitteemember_voter_start_district"),
        (
            "plan_execution",
            "0066_rename_amount_installmentdetail_nikasha_total_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="member_type",
            field=models.ForeignKey(
                blank=True,
                help_text="सदस्य प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.membertype",
                verbose_name="Member Type",
            ),
        ),
    ]
