# Generated by Django 4.2.1 on 2023-12-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0017_populate_marital_status_table"),
        ("plan_execution", "0067_alter_monitoringcommitteedetail_member_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentexitbill",
            name="nikasha_total_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentexitbill",
            name="peski_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentexitbill",
            name="plan_mst_total_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentexitbill",
            name="total_remaining_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectfinishedbailreturn",
            name="approved_by_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employeesector",
            ),
        ),
        migrations.AlterField(
            model_name="projectdeadline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extensions",
                to="plan_execution.projectexecution",
            ),
        ),
    ]
