# Generated by Django 4.2.1 on 2023-12-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0071_projectexecution_total_committee_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="probabilitystudyapprove",
            name="approvers_opinion",
            field=models.TextField(
                blank=True,
                help_text="अनुमोदनको अभिप्राय",
                null=True,
                verbose_name="Approver's Opinion",
            ),
        ),
        migrations.AlterField(
            model_name="probabilitystudyapprove",
            name="consumer_benefits",
            field=models.TextField(
                blank=True,
                help_text="उपभोक्ता लाभ",
                null=True,
                verbose_name="Consumer Benefits",
            ),
        ),
        migrations.AlterField(
            model_name="probabilitystudyapprove",
            name="decision",
            field=models.TextField(
                blank=True, help_text="निर्णय", null=True, verbose_name="Decision"
            ),
        ),
        migrations.AlterField(
            model_name="probabilitystudyapprove",
            name="engineer_survey_to_start_future",
            field=models.TextField(
                blank=True,
                help_text="अभियन्ता सर्वेक्षण भविष्यमा सुरु गर्ने",
                null=True,
                verbose_name="Engineer Survey To Start Future",
            ),
        ),
        migrations.AlterField(
            model_name="probabilitystudyapprove",
            name="label",
            field=models.TextField(
                blank=True, help_text="लेबल", null=True, verbose_name="Label"
            ),
        ),
        migrations.AlterField(
            model_name="probabilitystudyapprove",
            name="recommender_opinion",
            field=models.TextField(
                blank=True,
                help_text="सिफारिसको अभिप्राय",
                null=True,
                verbose_name="Recommender's Opinion",
            ),
        ),
    ]
