# Generated by Django 4.2.1 on 2023-12-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0072_alter_probabilitystudyapprove_approvers_opinion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttender",
            name="address1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="address2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="address3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="address4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="address5",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="address6",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="representative1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="representative2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="representative3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="representative4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="representative5",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="representative6",
            field=models.TextField(blank=True, null=True),
        ),
    ]
