# Generated by Django 4.2.1 on 2023-12-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0053_consumercommitteemember_country_and_more"),
        (
            "plan_execution",
            "0075_projectexecution_purpose_projectexecution_work_area_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingmaterialdetail",
            name="material",
            field=models.ForeignKey(
                blank=True,
                help_text="सामग्री",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.constructionmaterialdescription",
                verbose_name="Material",
            ),
        ),
    ]
