# Generated by Django 4.2.1 on 2023-12-17 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0018_alter_currentworkingdetail_position_and_more"),
        ("plan_execution", "0077_remove_buildingmaterialdetail_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectagreement",
            name="office_witness_1_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_ow1",
                to="employee.employeesector",
            ),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="office_witness_2_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_ow2",
                to="employee.employeesector",
            ),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="office_witness_3_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_ow3",
                to="employee.employeesector",
            ),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="office_witness_4_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_ow4",
                to="employee.employeesector",
            ),
        ),
    ]
