# Generated by Django 4.2.1 on 2023-12-17 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0018_alter_currentworkingdetail_position_and_more"),
        ("plan_execution", "0079_populate_startpms_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentexitbill",
            name="approved_by_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="peb_approve_position",
                to="employee.employeesector",
            ),
        ),
        migrations.AlterField(
            model_name="paymentexitbill",
            name="check_pass_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employeesector",
            ),
        ),
        migrations.AlterField(
            model_name="paymentexitbill",
            name="ready_by_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="peb_ready_position",
                to="employee.employeesector",
            ),
        ),
        migrations.AlterField(
            model_name="paymentexitbill",
            name="submitted_by_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="peb_submit_position",
                to="employee.employeesector",
            ),
        ),
    ]
