# Generated by Django 4.2.1 on 2023-12-17 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_report", "0025_customreporttemplate_required_renders"),
        ("plan_execution", "0080_alter_paymentexitbill_approved_by_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectModifiedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_content", models.TextField(blank=True, null=True)),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="modified_reports/"
                    ),
                ),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_reports",
                        to="plan_execution.projectexecution",
                    ),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_reports",
                        to="project_report.reporttype",
                    ),
                ),
                (
                    "start_pms_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_reports",
                        to="plan_execution.startpmsprocess",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Modified Report",
                "verbose_name_plural": "Project Modified Reports",
            },
        ),
    ]
