# Generated by Django 4.2.1 on 2023-12-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0083_alter_consumerformulation_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringcommitteedetail",
            name="member_position",
            field=models.CharField(
                blank=True,
                help_text="सदस्य पद",
                max_length=255,
                null=True,
                verbose_name="Member Position",
            ),
        ),
    ]
