# Generated by Django 4.2.1 on 2023-12-19 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0019_alter_currentworkingdetail_status_and_more"),
        ("plan_execution", "0084_alter_monitoringcommitteedetail_member_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="openingcontractaccount",
            name="secretary_of_consumer_committee_post",
            field=models.ForeignKey(
                blank=True,
                help_text="उपभोक्ता समिति सचिव पद",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employeesector",
                verbose_name="Secretary of Consumer Committee Post",
            ),
        ),
        migrations.AddField(
            model_name="openingcontractaccount",
            name="witness_consumer_committee_post",
            field=models.ForeignKey(
                blank=True,
                help_text="साक्षी उपभोक्ता समिति पद",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="witness_consumer_committee_post_emp",
                to="employee.employeesector",
                verbose_name="Witness Consumer Committee Post",
            ),
        ),
    ]
