# Generated by Django 4.2.1 on 2023-12-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0085_openingcontractaccount_secretary_of_consumer_committee_post_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="openingcontractaccount",
            name="cost_participation_subsidy",
            field=models.CharField(
                blank=True,
                help_text="खर्च भागिदारी अनुदान",
                max_length=30,
                null=True,
                verbose_name="Cost Participation Subsidy",
            ),
        ),
        migrations.AddField(
            model_name="openingcontractaccount",
            name="public_service_labour_force",
            field=models.CharField(
                blank=True,
                help_text="सार्वजनिक सेवा श्रम बल",
                max_length=30,
                null=True,
                verbose_name="Public Service Labour Force",
            ),
        ),
    ]
