# Generated by Django 4.2.1 on 2023-12-19 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0087_psabuildingmaterial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercommitteeprojectworkcomplete",
            name="project_document",
        ),
    ]
