# Generated by Django 4.2.1 on 2023-12-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0088_remove_usercommitteeprojectworkcomplete_project_document",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttender",
            name="bids_enrollment_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="bids_open_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="bids_purchase_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="representative_send_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
