# Generated by Django 4.2.1 on 2023-12-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0089_alter_projecttender_bids_enrollment_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectbidcollection",
            name="bank_guarantee_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bid_bond", "बिड बन्ड"),
                    ("performance_bond", "पर्फरमेन्स बन्ड"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
