# Generated by Django 4.2.1 on 2023-12-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0090_alter_projectbidcollection_bank_guarantee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercommitteeprojectworkcomplete",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ups_project_complete",
                to="plan_execution.projectexecution",
            ),
        ),
    ]
