# Generated by Django 4.2.1 on 2023-12-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0091_alter_usercommitteeprojectworkcomplete_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectexecution",
            name="phase",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("initialized", "initialized"),
                    ("agreement", "agreement"),
                    ("partial-payment", "partial-payment"),
                    ("completed", "completed"),
                    ("issue", "issue"),
                ],
                default="created",
                help_text="अवस्था",
                max_length=50,
                verbose_name="Phase",
            ),
        ),
    ]
