# Generated by Django 4.2.1 on 2023-12-23 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan_execution", "0092_projectexecution_phase"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotationSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                (
                    "cha_no",
                    models.CharField(
                        blank=True,
                        help_text="चलानी नं",
                        max_length=255,
                        null=True,
                        verbose_name="Invoice Number",
                    ),
                ),
                (
                    "letter_no",
                    models.CharField(
                        blank=True,
                        help_text="पत्र नं",
                        max_length=255,
                        null=True,
                        verbose_name="Letter Number",
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True,
                        help_text="मिति",
                        max_length=255,
                        null=True,
                        verbose_name="Date",
                    ),
                ),
                (
                    "date_eng",
                    models.CharField(
                        blank=True,
                        help_text="मिति (AD)",
                        max_length=255,
                        null=True,
                        verbose_name="Date (AD)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quot_specifications",
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation: Specification",
                "verbose_name_plural": "Quotation: Specifications",
            },
        ),
    ]
