# Generated by Django 4.2.1 on 2023-12-23 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_planning", "0054_alter_accounttitlemanagement_status_and_more"),
        ("plan_execution", "0093_quotationspecification"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotationSubmissionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                (
                    "firm_no",
                    models.CharField(
                        blank=True,
                        help_text="फर्म नं",
                        max_length=255,
                        null=True,
                        verbose_name="Firm Number",
                    ),
                ),
                (
                    "registration_date",
                    models.CharField(
                        blank=True,
                        help_text="दर्ता मिति",
                        max_length=255,
                        null=True,
                        verbose_name="Registration Date",
                    ),
                ),
                (
                    "registration_date_eng",
                    models.CharField(
                        blank=True,
                        help_text="दर्ता मिति (AD)",
                        max_length=255,
                        null=True,
                        verbose_name="Registration Date (AD)",
                    ),
                ),
                (
                    "total_amount",
                    models.CharField(
                        blank=True,
                        help_text="कुल रकम",
                        max_length=255,
                        null=True,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "mu_a_tax",
                    models.CharField(
                        blank=True,
                        help_text="मु आ कर",
                        max_length=255,
                        null=True,
                        verbose_name="Mu A Tax",
                    ),
                ),
                (
                    "total_accepted_amount",
                    models.CharField(
                        blank=True,
                        help_text="कुल स्वीकृत रकम",
                        max_length=255,
                        null=True,
                        verbose_name="Total Accepted Amount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "firm_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_quots",
                        to="project_planning.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quot_submissions",
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
