# Generated by Django 4.2.1 on 2023-12-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0094_quotationsubmissionapproval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttender",
            name="info_publication_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="paper_page_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
