# Generated by Django 4.2.1 on 2023-12-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0095_alter_projecttender_info_publication_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="probabilitystudyapprove",
            name="approved_amount_percent",
            field=models.CharField(
                blank=True,
                help_text="अनुमोदित रकम प्रतिशत",
                null=True,
                verbose_name="Approved Amount Percent",
            ),
        ),
    ]
