# Generated by Django 4.2.1 on 2023-12-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0096_alter_probabilitystudyapprove_approved_amount_percent",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentexitbill",
            name="cha_no",
            field=models.CharField(
                blank=True,
                help_text="चलानी नं.",
                max_length=50,
                null=True,
                verbose_name="Invoice No.",
            ),
        ),
        migrations.AddField(
            model_name="paymentexitbill",
            name="letter_no",
            field=models.CharField(
                blank=True,
                help_text="पत्र नं.",
                max_length=50,
                null=True,
                verbose_name="Letter No.",
            ),
        ),
    ]
