# Generated by Django 4.2.1 on 2023-12-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0019_alter_currentworkingdetail_status_and_more"),
        ("plan_execution", "0097_paymentexitbill_cha_no_paymentexitbill_letter_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdarbhaubid",
            name="bid_enrollment_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projectdarbhaubid",
            name="bid_sale_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projectdarbhaubid",
            name="comment_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projectdarbhaubid",
            name="legal_bid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="bids_enrollment_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pt_beb_branch",
                to="employee.department",
            ),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="bids_purchase_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pt_bpb_branch",
                to="employee.department",
            ),
        ),
        migrations.AlterField(
            model_name="projecttender",
            name="contact_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pt_cb_branch",
                to="employee.department",
            ),
        ),
    ]
