# Generated by Django 4.2.1 on 2023-12-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0098_alter_projectdarbhaubid_bid_enrollment_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositmandate",
            name="invoice_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="depositmandate",
            name="mandate_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("from_a_specific_order", "तोक आदेशबाट"),
                    ("from_allocated_budget", "विनियोजित बजेटबाट"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depositmandate",
            name="order_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="depositmandate",
            name="work_complete_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
