# Generated by Django 4.2.1 on 2023-12-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0099_alter_depositmandate_invoice_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectexecution",
            name="work_proposer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ups", "उपभोक्ता समिति / टोल"),
                    ("ward", "वडा"),
                    ("muni", "न.पा./गा.पा."),
                    ("other", "अन्य"),
                ],
                help_text="कार्य प्रस्तावक प्रकार",
                max_length=55,
                null=True,
                verbose_name="Work Proposer Type",
            ),
        ),
        migrations.AlterField(
            model_name="projectrevision",
            name="work_proposer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ups", "उपभोक्ता समिति / टोल"),
                    ("ward", "वडा"),
                    ("muni", "न.पा./गा.पा."),
                    ("other", "अन्य"),
                ],
                help_text="कार्य प्रस्तावक प्रकार",
                max_length=55,
                null=True,
                verbose_name="Work Proposer Type",
            ),
        ),
    ]
