# Generated by Django 4.2.1 on 2023-12-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0101_alter_projectbidcollection_attached_documents_list_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectagreement",
            name="age",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="exist_bail_amount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="exist_bank_guarantee_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="exist_performance_bond_amount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="required_bail_amount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="projectagreement",
            name="required_performance_bond_amount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
