# Generated by Django 4.2.1 on 2024-01-04 05:22

import django.db.models.deletion
from django.db import migrations, models


def clear_opening_contract_account_secretary_of_consumer_committee_post(
    apps, schema_editor
):
    OpeningContractAccount = apps.get_model("plan_execution", "OpeningContractAccount")
    db_alias = schema_editor.connection.alias
    OpeningContractAccount.objects.using(db_alias).all().update(
        secretary_of_consumer_committee_post=None
    )


def clear_opening_contract_account_witness_consumer_committee_post(apps, schema_editor):
    OpeningContractAccount = apps.get_model("plan_execution", "OpeningContractAccount")
    db_alias = schema_editor.connection.alias
    OpeningContractAccount.objects.using(db_alias).all().update(
        witness_consumer_committee_post=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0054_alter_accounttitlemanagement_status_and_more"),
        ("plan_execution", "0104_alter_budgetallocationdetail_first_quarter_and_more"),
    ]

    operations = [
        migrations.RunPython(
            clear_opening_contract_account_secretary_of_consumer_committee_post,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            clear_opening_contract_account_witness_consumer_committee_post,
            migrations.RunPython.noop,
        ),
    ]
