# Generated by Django 4.2.1 on 2024-01-05 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0055_populate_membership_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "plan_execution",
            "0106_alter_openingcontractaccount_secretary_of_consumer_committee_post_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CostEstimateData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.CharField(blank=True, max_length=255, null=True)),
                ("rate", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation: Cost Estimate Data",
                "verbose_name_plural": "Quotation: Cost Estimate Data",
            },
        ),
        migrations.CreateModel(
            name="QuotationFirmDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="दर्ता नं",
                        max_length=255,
                        null=True,
                        verbose_name="Registration Number",
                    ),
                ),
                (
                    "pan_no",
                    models.CharField(
                        blank=True,
                        help_text="प्यान नं",
                        max_length=255,
                        null=True,
                        verbose_name="PAN Number",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "firm_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quot_firm_details",
                        to="project_planning.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation: Firm Details",
                "verbose_name_plural": "Quotation: Firm Details",
            },
        ),
        migrations.AlterModelOptions(
            name="quotationsubmissionapproval",
            options={
                "verbose_name": "Quotation: Submission Approval",
                "verbose_name_plural": "Quotation: Submission Approvals",
            },
        ),
        migrations.RemoveField(
            model_name="quotationsubmissionapproval",
            name="firm_name",
        ),
        migrations.RemoveField(
            model_name="quotationsubmissionapproval",
            name="firm_no",
        ),
        migrations.RemoveField(
            model_name="quotationsubmissionapproval",
            name="mu_a_tax",
        ),
        migrations.RemoveField(
            model_name="quotationsubmissionapproval",
            name="registration_date",
        ),
        migrations.RemoveField(
            model_name="quotationsubmissionapproval",
            name="registration_date_eng",
        ),
        migrations.RemoveField(
            model_name="quotationsubmissionapproval",
            name="total_accepted_amount",
        ),
        migrations.RemoveField(
            model_name="quotationsubmissionapproval",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="quotationspecification",
            name="boq_type",
            field=models.CharField(
                blank=True,
                choices=[("BOQ", "BOQ"), ("NON_BOQ", "Non BOQ")],
                help_text="बीओक्यू प्रकार",
                max_length=255,
                null=True,
                verbose_name="BOQ Type",
            ),
        ),
        migrations.AddField(
            model_name="quotationsubmissionapproval",
            name="cha_no",
            field=models.CharField(
                blank=True,
                help_text="चलानी नं",
                max_length=255,
                null=True,
                verbose_name="Invoice Number",
            ),
        ),
        migrations.AddField(
            model_name="quotationsubmissionapproval",
            name="date",
            field=models.CharField(
                blank=True,
                help_text="मिति",
                max_length=255,
                null=True,
                verbose_name="Date",
            ),
        ),
        migrations.AddField(
            model_name="quotationsubmissionapproval",
            name="date_eng",
            field=models.CharField(
                blank=True,
                help_text="मिति (AD)",
                max_length=255,
                null=True,
                verbose_name="Date (AD)",
            ),
        ),
        migrations.AddField(
            model_name="quotationsubmissionapproval",
            name="letter_no",
            field=models.CharField(
                blank=True,
                help_text="पत्र नं",
                max_length=255,
                null=True,
                verbose_name="Letter Number",
            ),
        ),
        migrations.AlterField(
            model_name="quotationspecification",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quot_specification",
                to="plan_execution.projectexecution",
            ),
        ),
        migrations.CreateModel(
            name="QuotationInvitationForProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                (
                    "letter_no",
                    models.CharField(
                        blank=True,
                        help_text="पत्र नं",
                        max_length=255,
                        null=True,
                        verbose_name="Letter Number",
                    ),
                ),
                (
                    "cha_no",
                    models.CharField(
                        blank=True,
                        help_text="चलानी नं",
                        max_length=255,
                        null=True,
                        verbose_name="Invoice Number",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "invited_firm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quot_invited_for",
                        to="plan_execution.quotationfirmdetails",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quot_firm_invitations",
                        to="plan_execution.projectexecution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="quotationfirmdetails",
            name="quot_specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specification_firm_details",
                to="plan_execution.quotationspecification",
            ),
        ),
        migrations.CreateModel(
            name="FirmQuotedCostEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                ("rate", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.CharField(blank=True, max_length=255, null=True)),
                ("is_vat_added", models.BooleanField(default=False)),
                (
                    "cost_estimate_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firm_quoted_cost_estimate",
                        to="plan_execution.costestimatedata",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimate_quoted_by",
                        to="plan_execution.quotationfirmdetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation: Firm Quoted Cost Estimate",
                "verbose_name_plural": "Quotation: Firm Quoted Cost Estimates",
            },
        ),
        migrations.AddField(
            model_name="costestimatedata",
            name="quot_specification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_estimate_data",
                to="plan_execution.quotationspecification",
            ),
        ),
        migrations.AddField(
            model_name="quotationsubmissionapproval",
            name="firm_details",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quot_submission_approval",
                to="plan_execution.quotationfirmdetails",
            ),
        ),
    ]
