# Generated by Django 4.2.1 on 2024-01-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0055_populate_membership_type"),
        ("plan_execution", "0107_costestimatedata_quotationfirmdetails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationfirmdetails",
            name="firm_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specification_firm_details",
                to="project_planning.organization",
            ),
        ),
    ]
