# Generated by Django 4.2.1 on 2024-01-06 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0056_consumercommitteedocument_code"),
        (
            "plan_execution",
            "0109_benefiteddetail_code_budgetallocationdetail_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationfirmdetails",
            name="firm_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quot_firm",
                to="project_planning.organization",
            ),
        ),
    ]
