# Generated by Django 4.2.1 on 2024-01-07 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0111_remove_quotationsubmissionapproval_firm_details_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotationinvitationforproposal",
            options={
                "verbose_name": "Quotation: Invitation For Proposal",
                "verbose_name_plural": "Quotation: Invitations For Proposal",
            },
        ),
    ]
