# Generated by Django 4.2.1 on 2024-01-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0112_alter_quotationinvitationforproposal_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentexitbill",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("pes", "Peski"), ("bhk", "Bhuktani")],
                help_text="भुक्तानी प्रकार",
                max_length=5,
                null=True,
                verbose_name="Payment Type",
            ),
        ),
    ]
