# Generated by Django 4.2.1 on 2024-01-09 05:07

from django.db import migrations

from plan_execution.models import ProjectInstallment as InstallmentModel


def update_installment_model(apps, schema_editor):
    Installment: InstallmentModel = apps.get_model(
        "plan_execution", "ProjectInstallment"
    )
    installment_data_list = [
        {
            "code": "first",
            "name": "पहिलो चलिरहेको बिल",
            "name_eng": "First Running Bill",
        },
        {
            "code": "second",
            "name": "दोस्रो चलिरहेको बिल",
            "name_eng": "Second Running Bill",
        },
        {
            "code": "third",
            "name": "तेस्रो चलिरहेको बिल",
            "name_eng": "Third Running Bill",
        },
        {
            "code": "fourth",
            "name": "चौथो चलिरहेको बिल",
            "name_eng": "Fourth Running Bill",
        },
        {
            "code": "last",
            "name": "अन्तिम चलिरहेको बिल",
            "name_eng": "Last Running Bill",
        },
    ]
    db_alias = schema_editor.connection.alias
    for installment_data in installment_data_list:
        installment_code = installment_data.pop("code")
        Installment.objects.using(db_alias).filter(code=installment_code).update(
            **installment_data
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0114_projectdeadline_cha_no_projectdeadline_letter_no_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            update_installment_model, reverse_code=migrations.RunPython.noop
        ),
    ]
