# Generated by Django 4.2.1 on 2024-01-09 05:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0115_update_installment_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentexitbill",
            old_name="payment_type",
            new_name="payment_mode",
        ),
    ]
