# Generated by Django 4.2.1 on 2024-01-09 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0118_alter_firmquotedcostestimate_firm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firmquotedcostestimate",
            options={
                "ordering": ["firm__id"],
                "verbose_name": "Quotation: Firm Quoted Cost Estimate",
                "verbose_name_plural": "Quotation: Firm Quoted Cost Estimates",
            },
        ),
    ]
