# Generated by Django 4.2.1 on 2024-01-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0119_alter_firmquotedcostestimate_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="costestimatedata",
            name="remarks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
