# Generated by Django 4.2.1 on 2024-01-12 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0120_costestimatedata_remarks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotationfirmdetails",
            options={
                "ordering": ["id"],
                "verbose_name": "Quotation: Firm Details",
                "verbose_name_plural": "Quotation: Firm Details",
            },
        ),
    ]
