# Generated by Django 4.2.1 on 2024-01-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0121_alter_quotationfirmdetails_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectinstallment",
            name="start_pms_process",
            field=models.ManyToManyField(
                blank=True,
                help_text="सञ्चालन प्रकृया",
                to="plan_execution.startpmsprocess",
                verbose_name="Operating Procedures",
            ),
        ),
    ]
