# Generated by Django 4.2.1 on 2024-01-09 05:07

from django.db import migrations

from plan_execution.models import ProjectInstallment as InstallmentModel


def update_installment_model(apps, schema_editor):
    Installment: InstallmentModel = apps.get_model(
        "plan_execution", "ProjectInstallment"
    )
    installment_data_list = [
        {
            "code": "first",
            "name": "पहिलो किस्ता",
            "name_eng": "First Installment",
        },
        {
            "code": "second",
            "name": "दोस्रो किस्ता",
            "name_eng": "Second Installment",
        },
        {
            "code": "third",
            "name": "तेस्रो किस्ता",
            "name_eng": "Third Installment",
        },
        {
            "code": "fourth",
            "name": "चौथो किस्ता",
            "name_eng": "Fourth Installment",
        },
        {
            "code": "last",
            "name": "अन्तिम किस्ता",
            "name_eng": "Last Installment",
        },
    ]
    db_alias = schema_editor.connection.alias
    for installment_data in installment_data_list:
        installment_code = installment_data.pop("code")
        Installment.objects.using(db_alias).filter(code=installment_code).update(
            **installment_data
        )


def populate_installment_model(apps, schema_editor):
    Installment = apps.get_model("plan_execution", "ProjectInstallment")
    StartPmsProcess = apps.get_model("plan_execution", "StartPmsProcess")
    installment_data_list = [
        {
            "code": "first-rb",
            "name": "पहिलो रनिङ्ग बिल",
            "name_eng": "First Running Bill",
        },
        {
            "code": "second-rb",
            "name": "दोस्रो रनिङ्ग बिल",
            "name_eng": "Second Running Bill",
        },
        {
            "code": "third-rb",
            "name": "तेस्रो रनिङ्ग बिल",
            "name_eng": "Third Running Bill",
        },
        {
            "code": "fourth-rb",
            "name": "चौथो रनिङ्ग बिल",
            "name_eng": "Fourth Running Bill",
        },
        {
            "code": "last-rb",
            "name": "अन्तिम रनिङ्ग बिल",
            "name_eng": "Last Running Bill",
        },
    ]
    db_alias = schema_editor.connection.alias
    pms_processes = StartPmsProcess.objects.using(db_alias).filter(
        code__in=["quot", "tppt"]
    )

    for data in installment_data_list:
        installment = Installment.objects.using(db_alias).create(**data)
        installment.start_pms_process.set(pms_processes)


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0122_projectinstallment_start_pms_process",
        ),
    ]

    operations = [
        migrations.RunPython(
            update_installment_model, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_installment_model, reverse_code=migrations.RunPython.noop
        ),
    ]
