# Generated by Django 4.2.1 on 2024-01-15 11:51

from django.db import migrations
from django.db.models import Q


def update_installment_objects(apps, schema_editor):
    Installment = apps.get_model("plan_execution", "ProjectInstallment")
    StartPmsProcess = apps.get_model("plan_execution", "StartPmsProcess")
    db_alias = schema_editor.connection.alias

    pms_processes = StartPmsProcess.objects.using(db_alias).filter(
        ~Q(code__in=["quot", "tppt"])
    )
    non_rb_installments = Installment.objects.using(db_alias).filter(
        ~Q(code__contains="rb")
    )

    for installment in non_rb_installments:
        installment.start_pms_process.set(pms_processes)


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0123_update_installment_model"),
    ]

    operations = [
        migrations.RunPython(update_installment_objects),
    ]
