# Generated by Django 4.2.1 on 2024-01-17 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0020_cumulativedetail_code_currentworkingdetail_code_and_more"),
        ("plan_execution", "0125_update_blank_values_in_oca_mandate_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingcontractaccount",
            name="mandate_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="बिधेयक कर्मचारी",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mandate_employee",
                to="employee.employee",
                verbose_name="Mandate Employee",
            ),
        ),
        migrations.AlterField(
            model_name="openingcontractaccount",
            name="mandate_employee_position",
            field=models.ForeignKey(
                blank=True,
                help_text="बिधेयक कर्मचारीको पद",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mandate_employee_position",
                to="employee.employeesector",
                verbose_name="Mandate Employee's Position",
            ),
        ),
    ]
