# Generated by Django 4.2.1 on 2024-01-28 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0065_alter_project_ward"),
        (
            "plan_execution",
            "0126_alter_openingcontractaccount_mandate_employee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationfirmdetails",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotation_firm_details",
                to="project.municipality",
            ),
        ),
        migrations.AddField(
            model_name="quotationfirmdetails",
            name="tole",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="quotationfirmdetails",
            name="ward",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
