# Generated by Django 4.2.1 on 2024-02-02 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0059_alter_consumercommitteemember_options"),
        ("plan_execution", "0127_quotationfirmdetails_municipality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumerformulation",
            name="monitor_committee",
            field=models.ManyToManyField(
                blank=True,
                help_text="निर्वाह समिति सदस्य",
                related_name="formulation",
                to="project_planning.monitoringcommitteemember",
                verbose_name="Monitoring Committee Member",
            ),
        ),
        migrations.AddField(
            model_name="consumerformulation",
            name="monitoring_committee",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्वाह समिति",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.monitoringcommittee",
                verbose_name="Monitoring Committee",
            ),
        ),
    ]
