# Generated by Django 4.2.1 on 2024-03-05 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0131_remove_monitoringcommitteedetail_user_committee_monitoring",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercommitteedocuments",
            old_name="document",
            new_name="document_file",
        ),
    ]
