# Generated by Django 4.2.1 on 2024-06-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan_execution", "0133_alter_accountingtopic_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingtopic",
            name="verfication_status",
            field=models.CharField(
                choices=[
                    ("na", "Not Applicable"),
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("req_revision", "Requires Revision"),
                    ("rejected", "Rejected"),
                ],
                default="na",
                help_text="सत्यापन स्थिति",
                max_length=55,
                verbose_name="Verification Status",
            ),
        ),
        migrations.AddField(
            model_name="bailtype",
            name="verfication_status",
            field=models.CharField(
                choices=[
                    ("na", "Not Applicable"),
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("req_revision", "Requires Revision"),
                    ("rejected", "Rejected"),
                ],
                default="na",
                help_text="सत्यापन स्थिति",
                max_length=55,
                verbose_name="Verification Status",
            ),
        ),
        migrations.AddField(
            model_name="planstartdecision",
            name="verfication_status",
            field=models.CharField(
                choices=[
                    ("na", "Not Applicable"),
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("req_revision", "Requires Revision"),
                    ("rejected", "Rejected"),
                ],
                default="na",
                help_text="सत्यापन स्थिति",
                max_length=55,
                verbose_name="Verification Status",
            ),
        ),
        migrations.AddField(
            model_name="projectexecutiondocument",
            name="verfication_status",
            field=models.CharField(
                choices=[
                    ("na", "Not Applicable"),
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("req_revision", "Requires Revision"),
                    ("rejected", "Rejected"),
                ],
                default="na",
                help_text="सत्यापन स्थिति",
                max_length=55,
                verbose_name="Verification Status",
            ),
        ),
        migrations.AddField(
            model_name="projectinstallment",
            name="verfication_status",
            field=models.CharField(
                choices=[
                    ("na", "Not Applicable"),
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("req_revision", "Requires Revision"),
                    ("rejected", "Rejected"),
                ],
                default="na",
                help_text="सत्यापन स्थिति",
                max_length=55,
                verbose_name="Verification Status",
            ),
        ),
        migrations.AddField(
            model_name="projectphysicaldescription",
            name="verfication_status",
            field=models.CharField(
                choices=[
                    ("na", "Not Applicable"),
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("req_revision", "Requires Revision"),
                    ("rejected", "Rejected"),
                ],
                default="na",
                help_text="सत्यापन स्थिति",
                max_length=55,
                verbose_name="Verification Status",
            ),
        ),
        migrations.AddField(
            model_name="startpmsprocess",
            name="verfication_status",
            field=models.CharField(
                choices=[
                    ("na", "Not Applicable"),
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("req_revision", "Requires Revision"),
                    ("rejected", "Rejected"),
                ],
                default="na",
                help_text="सत्यापन स्थिति",
                max_length=55,
                verbose_name="Verification Status",
            ),
        ),
        migrations.AddField(
            model_name="tenderpurchasebranch",
            name="verfication_status",
            field=models.CharField(
                choices=[
                    ("na", "Not Applicable"),
                    ("not_submitted", "Not Submitted"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("req_revision", "Requires Revision"),
                    ("rejected", "Rejected"),
                ],
                default="na",
                help_text="सत्यापन स्थिति",
                max_length=55,
                verbose_name="Verification Status",
            ),
        ),
    ]
