# Generated by Django 4.2.1 on 2023-06-24 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0025_projectproposedtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base_model", "0006_address_local_level_eng_address_ward_eng"),
        ("project", "0020_estimationrate_area"),
        ("budget_process", "0005_budgetexpensemanagement"),
        ("employee", "0007_cumulativedetail_cif_certificate_no"),
        ("formulate_plan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                ("ward", models.IntegerField()),
                (
                    "proposed_project_outcome",
                    models.CharField(
                        blank=True,
                        help_text="प्रस्थाबित योजना/कार्यक्रमको परिणाम",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "proposed_date",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "proposed_date_eng",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "estimated_start_date",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "estimated_start_date_eng",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "estimated_end_date",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "estimated_end_date_eng",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "estimated_amount",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "internal_source",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("nepal_gov", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "province_gov",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "local_level_gov",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("loan", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "public_participation",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "benefited_households",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "benefited_population",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("achievement", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "priority_approved_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "priority_approved_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "project_approved_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "project_approved_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "approved_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "approved_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=150, null=True)),
                ("kramagat", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base_model.address",
                    ),
                ),
                (
                    "approve",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="budget_process.approveprocess",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        blank=True,
                        help_text="आर्थिक बर्ष ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_year",
                        to="project.financialyear",
                    ),
                ),
                (
                    "priority_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="priority_approved_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "project_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_approved_by",
                        to="employee.employee",
                    ),
                ),
                (
                    "project_prioritization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.prioritytype",
                    ),
                ),
                (
                    "proposed_financial_year",
                    models.ForeignKey(
                        blank=True,
                        help_text="प्रस्तावित आर्थिक बर्ष ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_fy",
                        to="project.financialyear",
                    ),
                ),
                (
                    "proposed_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="योजनाको प्रस्ताबित प्रकार",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.projectproposedtype",
                    ),
                ),
                (
                    "proposed_unit_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="प्रस्थाबित योजना/कार्यक्रम को प्रकार ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.unit",
                    ),
                ),
                (
                    "user_committee",
                    models.ForeignKey(
                        blank=True,
                        help_text=" उपभोक्ता समिति",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.consumercommittee",
                    ),
                ),
                (
                    "work_class",
                    models.ForeignKey(
                        blank=True,
                        help_text="कामको वर्ग ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="formulate_plan.workclass",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="कामको प्रकार",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="formulate_plan.projectworktype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BudgetAssurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("amount", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "internal_source",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nepal_gov_source",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "province_source",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "local_level_source",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("loan_source", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "public_participation_source",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "expense_title_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "program_activity_outcome",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "past_fiscal_year_outcome",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "past_fiscal_year_expense",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "current_fy_outcome",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "current_fy_budget",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "first_quarter_outcome",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "first_quarter_budget",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "second_quarter_outcome",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "second_quarter_budget",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "third_quarter_outcome",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "third_quarter_budget",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "approved_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "approved_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_title_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.expansetype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
