# Generated by Django 4.2.1 on 2023-06-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulate_plan", "0003_projectdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="workproject",
            name="project_level",
            field=models.CharField(
                choices=[
                    ("ward", "ward"),
                    ("local_level", "local_level"),
                    ("other", "other"),
                ],
                default="local_level",
                max_length=50,
            ),
        ),
    ]
