# Generated by Django 4.2.1 on 2023-07-02 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulate_plan", "0005_workproject_budget_assurance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workproject",
            name="work_class",
            field=models.ForeignKey(
                blank=True,
                help_text="कामको वर्ग",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="formulate_plan.workclass",
            ),
        ),
    ]
