# Generated by Django 4.2.1 on 2023-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulate_plan", "0006_alter_workproject_work_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="workproject",
            name="is_approved",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="workproject",
            name="is_prioritization",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
