# Generated by Django 4.2.1 on 2023-07-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulate_plan", "0007_workproject_is_approved_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workproject",
            old_name="is_prioritization",
            new_name="is_prioritized",
        ),
    ]
