# Generated by Django 4.2.3 on 2023-08-11 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0027_alter_accounttitlemanagement_detail_and_more"),
        (
            "formulate_plan",
            "0009_alter_projectworktype_detail_alter_workclass_detail_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workproject",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.projectlevel",
            ),
        ),
    ]
