# Generated by Django 4.2.1 on 2023-10-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulate_plan", "0011_alter_budgetassurance_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workproject",
            name="ward",
            field=models.IntegerField(blank=True, help_text="वडा नं. ", null=True),
        ),
    ]
