# Generated by Django 4.2.1 on 2023-11-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulate_plan", "0012_alter_workproject_ward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workproject",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workproject",
            name="name_eng",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
