# Generated by Django 4.2.1 on 2023-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulate_plan", "0013_alter_workproject_name_alter_workproject_name_eng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workproject",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
