# Generated by Django 4.2.1 on 2023-12-10 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_address_from_project_execution(apps, schema_editor):
    ProjectExecution = apps.get_model("plan_execution", "ProjectExecution")
    WorkProject = apps.get_model("formulate_plan", "WorkProject")
    db_alias = schema_editor.connection.alias
    ProjectExecution.objects.using(db_alias).all().update(address=None)
    WorkProject.objects.using(db_alias).all().update(address=None)


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0050_consumercommitteemember_voter_start_district"),
        ("project", "0056_alter_project_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("formulate_plan", "0016_populate_work_class_model"),
    ]

    operations = [
        migrations.RunPython(
            remove_address_from_project_execution,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
