# Generated by Django 4.2.1 on 2023-12-10 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulate_plan", "0017_remove_address_from_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                (
                    "ward",
                    models.CharField(
                        blank=True,
                        help_text="वडा",
                        max_length=55,
                        null=True,
                        verbose_name="Ward",
                    ),
                ),
                (
                    "ward_eng",
                    models.CharField(
                        blank=True,
                        help_text="वडा (अंग्रेजी)",
                        max_length=55,
                        null=True,
                        verbose_name="Ward (Eng)",
                    ),
                ),
                (
                    "house_no",
                    models.CharField(
                        blank=True,
                        help_text="घर नं",
                        max_length=55,
                        null=True,
                        verbose_name="House No",
                    ),
                ),
                (
                    "tole",
                    models.CharField(
                        blank=True,
                        help_text="टोल",
                        max_length=55,
                        null=True,
                        verbose_name="Tole",
                    ),
                ),
                (
                    "tole_eng",
                    models.CharField(
                        blank=True,
                        help_text="टोल (अंग्रेजी)",
                        max_length=55,
                        null=True,
                        verbose_name="Tole (Eng)",
                    ),
                ),
                (
                    "road_name_eng",
                    models.CharField(
                        blank=True,
                        help_text="सडकको नाम (अंग्रेजी)",
                        max_length=55,
                        null=True,
                        verbose_name="Road Name (Eng)",
                    ),
                ),
                (
                    "village_name",
                    models.CharField(
                        blank=True,
                        help_text="गाउँको नाम",
                        max_length=255,
                        null=True,
                        verbose_name="Village Name",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        help_text="नगरपालिका",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.municipality",
                        verbose_name="Municipality",
                    ),
                ),
                (
                    "road_name",
                    models.ForeignKey(
                        blank=True,
                        help_text="सडकको नाम",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.road",
                        verbose_name="Road",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="workproject",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="ठेगाना",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="formulate_plan.projectaddress",
                verbose_name="Address",
            ),
        ),
    ]
