# Generated by Django 4.2.1 on 2023-12-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_model", "0013_populate_gender_table"),
        ("formulate_plan", "0018_projectaddress_alter_workproject_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="workproject",
            name="project_address",
            field=models.ForeignKey(
                blank=True,
                help_text="ठेगाना",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_projects",
                to="formulate_plan.projectaddress",
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="workproject",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="ठेगाना",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_projects",
                to="base_model.address",
                verbose_name="Address",
            ),
        ),
    ]
