# Generated by Django 4.2.1 on 2023-12-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_report", "0022_populate_report_types_models"),
        ("formulate_plan", "0019_workproject_project_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdocument",
            name="report_type",
            field=models.ForeignKey(
                blank=True,
                help_text="प्रतिवेदनको प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_report.reporttype",
                verbose_name="Report Type",
            ),
        ),
    ]
