# Generated by Django 4.2.1 on 2023-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulate_plan", "0020_projectdocument_report_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdocument",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
