# Generated by Django 4.2.1 on 2024-01-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulate_plan", "0021_alter_projectdocument_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectworktype",
            name="max_budget",
            field=models.BigIntegerField(
                blank=True,
                help_text="अधिकतम बजेट",
                null=True,
                verbose_name="Max Budget",
            ),
        ),
        migrations.AlterField(
            model_name="projectworktype",
            name="min_budget",
            field=models.BigIntegerField(
                blank=True,
                help_text="न्यूनतम बजेट",
                null=True,
                verbose_name="Min Budget",
            ),
        ),
    ]
