# Generated by Django 4.2.1 on 2023-06-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base_model", "0003_rename_toll_address_tole_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="district",
        ),
        migrations.RemoveField(
            model_name="address",
            name="local_level",
        ),
        migrations.RemoveField(
            model_name="address",
            name="provence",
        ),
    ]
