# Generated by Django 4.2.1 on 2023-06-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_model", "0005_remove_address_ward_no_address_local_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="local_level_eng",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="ward_eng",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
