# Generated by Django 4.2.3 on 2023-07-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_model", "0007_documenttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gender",
            name="detail",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
