# Generated by Django 4.2.3 on 2023-08-12 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0038_alter_project_name"),
        ("base_model", "0008_alter_gender_detail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="local_level",
        ),
        migrations.RemoveField(
            model_name="address",
            name="local_level_eng",
        ),
        migrations.AddField(
            model_name="address",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.municipality",
            ),
        ),
    ]
