# Generated by Django 4.2.1 on 2023-10-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_model", "0010_alter_address_status_alter_contactdetail_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="detail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="name_eng",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
