# Generated by Django 4.2.1 on 2023-10-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0002_notification_is_read_notification_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
