# Generated by Django 4.2.1 on 2023-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/employee/"
            ),
        ),
    ]
