# Generated by Django 4.2.1 on 2023-06-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="departmentbranch",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeesector",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeetype",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="maritalstatus",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="position",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="positionlevel",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="servicegroup",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name="department",
            table=None,
        ),
        migrations.AlterModelTable(
            name="departmentbranch",
            table=None,
        ),
        migrations.AlterModelTable(
            name="employeesector",
            table=None,
        ),
        migrations.AlterModelTable(
            name="employeetype",
            table=None,
        ),
        migrations.AlterModelTable(
            name="position",
            table=None,
        ),
        migrations.AlterModelTable(
            name="positionlevel",
            table=None,
        ),
        migrations.AlterModelTable(
            name="servicegroup",
            table=None,
        ),
    ]
