# Generated by Django 4.2.1 on 2023-06-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_department_name_departmentbranch_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maritalstatus",
            name="date_of_marriage",
        ),
        migrations.RemoveField(
            model_name="maritalstatus",
            name="date_of_marriage_en",
        ),
    ]
