# Generated by Django 4.2.1 on 2023-06-10 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_planning",
            "0004_bfi_remove_bank_bank_type_remove_bank_cheque_format_and_more",
        ),
        ("employee", "0004_remove_maritalstatus_date_of_marriage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentworkingdetail",
            name="bank_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.bfi",
            ),
        ),
    ]
