# Generated by Django 4.2.1 on 2023-06-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_model", "0005_remove_address_ward_no_address_local_level_and_more"),
        ("employee", "0005_alter_currentworkingdetail_bank_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="permanent_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emp_permanent_address",
                to="base_model.address",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="temporary_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emp_temporary_address",
                to="base_model.address",
            ),
        ),
    ]
