# Generated by Django 4.2.3 on 2023-07-12 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0025_estimate_file_alter_estimate_road_1_rate_and_more"),
        ("base_model", "0007_documenttype"),
        ("employee", "0007_cumulativedetail_cif_certificate_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaxPayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "tax_payer_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "internal_source_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tax_payer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "citizenship_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "citizenship_register_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "registration_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "permanent_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=100, null=True)),
                ("dob", models.CharField(blank=True, max_length=100, null=True)),
                ("contact_no", models.CharField(blank=True, max_length=100, null=True)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "text_payer_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "citizenship_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.district",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Religion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublicRepresentativePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublicRepresentativeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "tax_payer_type",
                    models.CharField(
                        blank=True,
                        choices=[("हालको", "हालको"), ("भू.पू.", "भू.पू.")],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "grand_father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "first_name_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "middle_name_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "last_name_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_name_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "grand_father_name_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dob", models.CharField(blank=True, max_length=100, null=True)),
                ("dob_eng", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "citizenship_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "citizenship_start_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "citizenship_start_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "citizenship_from",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("passport", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "passport_start_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "passport_start_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "passport_start_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("voter_no", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "voter_start_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "voter_start_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "permanent_acc_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "other_detail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "position_start_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "position_start_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "position_end_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "position_end_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=50, null=True)),
                ("karmagat", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contact_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base_model.contactdetail",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.language",
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.nationality",
                    ),
                ),
                (
                    "permanent_current_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pc_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "permanent_former_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pf_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.position",
                    ),
                ),
                (
                    "position_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.positionlevel",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.religion",
                    ),
                ),
                (
                    "representative_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.publicrepresentativeposition",
                    ),
                ),
                (
                    "tax_payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.taxpayer",
                    ),
                ),
                (
                    "temporary_current_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tc_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "temporary_former_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tf_address",
                        to="base_model.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
