# Generated by Django 4.2.1 on 2023-07-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_country_language_nationality_taxpayer_religion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollmentdetail",
            name="end_date",
            field=models.DateField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name="enrollmentdetail",
            name="start_date",
            field=models.DateField(blank=True, max_length=55, null=True),
        ),
    ]
