# Generated by Django 4.2.3 on 2023-07-18 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_model", "0007_documenttype"),
        ("employee", "0010_alter_enrollmentdetail_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxpayer",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base_model.gender",
            ),
        ),
    ]
