# Generated by Django 4.2.1 on 2023-08-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employeesector_allowance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionlevel',
            name='short_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
