# Generated by Django 4.2.1 on 2023-11-23 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "base_model",
            "0012_alter_address_created_by_alter_address_created_date_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_planning", "0041_alter_accounttitlemanagement_code_and_more"),
        (
            "employee",
            "0015_alter_country_status_alter_cumulativedetail_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="book_store_no",
            field=models.CharField(
                blank=True,
                help_text="पुस्तक भण्डार नं",
                max_length=55,
                null=True,
                verbose_name="Book Store No",
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="cif_certificate_no",
            field=models.CharField(
                blank=True,
                help_text="सिफ सर्टिफिकेट नं",
                max_length=55,
                null=True,
                verbose_name="CIF Certificate No",
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="citizen_investment_deduction_percent",
            field=models.CharField(
                blank=True,
                help_text="नागरिक लगानी कटौती प्रतिशत",
                max_length=55,
                null=True,
                verbose_name="Citizen Investment Deduction Percent",
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="citizen_investment_no",
            field=models.CharField(
                blank=True,
                help_text="नागरिक लगानी नं",
                max_length=55,
                null=True,
                verbose_name="Citizen Investment No",
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="employee_saving_funds_no",
            field=models.CharField(
                blank=True,
                help_text="कर्मचारी बचत कोष नं",
                max_length=55,
                null=True,
                verbose_name="Employee Saving Funds No",
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="insurance_amount",
            field=models.CharField(
                blank=True,
                help_text="बिमा रकम",
                max_length=50,
                null=True,
                verbose_name="Insurance Amount",
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="insurance_company",
            field=models.CharField(
                blank=True,
                help_text="बिमा कम्पनी",
                max_length=100,
                null=True,
                verbose_name="Insurance Company",
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="insurance_policy_no",
            field=models.CharField(
                blank=True,
                help_text="बिमा नीति नं",
                max_length=50,
                null=True,
                verbose_name="Insurance Policy No",
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="permanent_article_no",
            field=models.CharField(
                blank=True,
                help_text="स्थायी लेखा नं",
                max_length=55,
                null=True,
                verbose_name="Permanent Article No",
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="cumulativedetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="currentworkingdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="currentworkingdetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="currentworkingdetail",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="विभाग",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_department",
                to="employee.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="currentworkingdetail",
            name="department_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="विभाग शाखा",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_department_branch",
                to="employee.departmentbranch",
                verbose_name="Department Branch",
            ),
        ),
        migrations.AlterField(
            model_name="currentworkingdetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="departmentbranch",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="departmentbranch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="departmentbranch",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="departmentbranch",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="departmentbranch",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="departmentbranch",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="departmentbranch",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="departmentbranch",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=32,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="सम्पर्क नं",
                max_length=20,
                null=True,
                verbose_name="Contact Number",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="cumulative_detail",
            field=models.ForeignKey(
                blank=True,
                help_text="जम्मा विवरण",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.cumulativedetail",
                verbose_name="Cumulative Detail",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="current_working_details",
            field=models.ForeignKey(
                blank=True,
                help_text="वर्तमान कार्यालय विवरण",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.currentworkingdetail",
                verbose_name="Current Working Details",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="dob",
            field=models.CharField(
                blank=True,
                help_text="जन्म मिति",
                max_length=100,
                null=True,
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="dob_eng",
            field=models.CharField(
                blank=True,
                help_text="जन्म मिति (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Date of Birth (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.CharField(
                blank=True,
                help_text="ईमेल",
                max_length=100,
                null=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="enrollment_detail",
            field=models.ForeignKey(
                blank=True,
                help_text="नामानामाको विवरण",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.enrollmentdetail",
                verbose_name="Enrollment Detail",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="family_detail",
            field=models.ForeignKey(
                blank=True,
                help_text="परिवारको विवरण",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.familydetail",
                verbose_name="Family Detail",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="पहिलो नाम",
                max_length=100,
                null=True,
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name_eng",
            field=models.CharField(
                blank=True,
                help_text="पहिलो नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="First Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                help_text="लिङ्ग",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base_model.gender",
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="तस्बिर",
                null=True,
                upload_to="uploads/employee/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="थर",
                max_length=100,
                null=True,
                verbose_name="Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name_eng",
            field=models.CharField(
                blank=True,
                help_text="थर (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Last Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=models.ForeignKey(
                blank=True,
                help_text="वैवाहिक स्थिति",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.maritalstatus",
                verbose_name="Marital Status",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(
                blank=True,
                help_text="बीचको नाम",
                max_length=100,
                null=True,
                verbose_name="Middle Name",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="middle_name_eng",
            field=models.CharField(
                blank=True,
                help_text="बीचको नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Middle Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="permanent_address",
            field=models.ForeignKey(
                blank=True,
                help_text="स्थायी ठेगाना",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emp_permanent_address",
                to="base_model.address",
                verbose_name="Permanent Address",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="फोन नं",
                max_length=20,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="subject_area",
            field=models.ForeignKey(
                blank=True,
                help_text="विषयगत कार्यक्षेत्र",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.subjectarea",
                verbose_name="Subject Area",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="temporary_address",
            field=models.ForeignKey(
                blank=True,
                help_text="अस्थायी ठेगाना",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emp_temporary_address",
                to="base_model.address",
                verbose_name="Temporary Address",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="employeesector",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="employeesector",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="employeesector",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="employeesector",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="employeesector",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="employeesector",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="employeesector",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="employeetype",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="employeetype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="employeetype",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="employeetype",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="employeetype",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="employeetype",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="employeetype",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="employeetype",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentdetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentdetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentdetail",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="विभाग",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentdetail",
            name="end_date",
            field=models.CharField(
                blank=True,
                help_text="अन्तिम मिति",
                max_length=55,
                null=True,
                verbose_name="End Date",
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentdetail",
            name="position",
            field=models.ForeignKey(
                blank=True,
                help_text="पद",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollment_position",
                to="employee.position",
                verbose_name="Position",
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentdetail",
            name="start_date",
            field=models.CharField(
                blank=True,
                help_text="सुरु मिति",
                max_length=55,
                null=True,
                verbose_name="Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentdetail",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentdetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="father_name",
            field=models.CharField(
                blank=True,
                help_text="बाबुको नाम",
                max_length=255,
                verbose_name="Father Name",
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="father_name_eng",
            field=models.CharField(
                blank=True,
                help_text="बाबुको नाम (अंग्रेजी)",
                max_length=255,
                verbose_name="Father Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="mother_name",
            field=models.CharField(
                blank=True,
                help_text="आमाको नाम",
                max_length=255,
                verbose_name="Mother Name",
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="mother_name_eng",
            field=models.CharField(
                blank=True,
                help_text="आमाको नाम (अंग्रेजी)",
                max_length=255,
                verbose_name="Mother Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="spouse_name",
            field=models.CharField(
                blank=True,
                help_text="श्रीमानको नाम",
                max_length=255,
                verbose_name="Spouse Name",
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="spouse_name_eng",
            field=models.CharField(
                blank=True,
                help_text="श्रीमानको नाम (अंग्रेजी)",
                max_length=255,
                verbose_name="Spouse Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="wished_person_name",
            field=models.CharField(
                blank=True,
                help_text="इच्छुक व्यक्तिको नाम",
                max_length=255,
                verbose_name="Wished Person Name",
            ),
        ),
        migrations.AlterField(
            model_name="familydetail",
            name="wished_person_name_eng",
            field=models.CharField(
                blank=True,
                help_text="इच्छुक व्यक्तिको नाम (अंग्रेजी)",
                max_length=255,
                verbose_name="Wished Person Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="maritalstatus",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="nationality",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="nationality",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="nationality",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="nationality",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="nationality",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="nationality",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="nationality",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="nationality",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="adjustment_grade_rate",
            field=models.FloatField(
                blank=True,
                help_text="समायोजन ग्रेड दर",
                null=True,
                verbose_name="Adjustment Grade Rate",
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="basic_salary",
            field=models.FloatField(
                blank=True,
                help_text="आधारभूत तलब",
                null=True,
                verbose_name="Basic Salary",
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="maximum_grade_rate",
            field=models.FloatField(
                blank=True,
                help_text="अधिकतम ग्रेड रकम",
                null=True,
                verbose_name="Maximum Grade Rate",
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="position_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("प्रशासनिक", "प्रशासनिक"),
                    ("प्राविधिक", "प्राविधिक"),
                    ("लागु नहुने", "लागु नहुने"),
                ],
                help_text="पदको प्रकार",
                max_length=10,
                null=True,
                verbose_name="Position Type",
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="short_form",
            field=models.CharField(
                blank=True,
                help_text="छोटो फारम",
                max_length=50,
                null=True,
                verbose_name="Short Form",
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="positionlevel",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="publicrepresentativedetail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="publicrepresentativedetail",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="publicrepresentativedetail",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="publicrepresentativeposition",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="publicrepresentativeposition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="publicrepresentativeposition",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="publicrepresentativeposition",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="publicrepresentativeposition",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="publicrepresentativeposition",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="publicrepresentativeposition",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="publicrepresentativeposition",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="religion",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="religion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="religion",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="religion",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="religion",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="religion",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="religion",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="religion",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="servicegroup",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="servicegroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="servicegroup",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="servicegroup",
            name="detail",
            field=models.CharField(
                blank=True,
                help_text="विवरण",
                max_length=500,
                null=True,
                verbose_name="Detail",
            ),
        ),
        migrations.AlterField(
            model_name="servicegroup",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=100,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="servicegroup",
            name="name_eng",
            field=models.CharField(
                blank=True,
                help_text="नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Name (Eng)",
            ),
        ),
        migrations.AlterField(
            model_name="servicegroup",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="servicegroup",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
        migrations.AlterField(
            model_name="taxpayer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="निर्माण गर्ने",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="taxpayer",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, help_text="निर्माण मिति", verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="taxpayer",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True, help_text="अद्यावधिक मिति", verbose_name="Updated Date"
            ),
        ),
    ]
