# Generated by Django 4.2.1 on 2023-12-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0017_populate_marital_status_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentworkingdetail",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_work_area",
                to="employee.employeesector",
            ),
        ),
        migrations.AlterField(
            model_name="currentworkingdetail",
            name="work_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_department_branch",
                to="employee.position",
            ),
        ),
    ]
