# Generated by Django 4.2.1 on 2023-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0018_alter_currentworkingdetail_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentworkingdetail",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="employeesector",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicrepresentativedetail",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="taxpayer",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
