# Generated by Django 4.2.1 on 2024-01-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0019_alter_currentworkingdetail_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cumulativedetail",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AddField(
            model_name="currentworkingdetail",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentdetail",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AddField(
            model_name="familydetail",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AddField(
            model_name="publicrepresentativedetail",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
    ]
