# Generated by Django 4.2.1 on 2023-06-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("path", models.CharField(blank=True, max_length=1024, null=True)),
                ("method", models.CharField(blank=True, max_length=10, null=True)),
                ("deta", models.TextField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("referer", models.CharField(blank=True, max_length=512, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
