# Generated by Django 4.2.1 on 2023-06-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0002_accesslog_municipality_accesslog_ward"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="user_email",
            field=models.EmailField(blank=True, default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="user_id",
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
