# Generated by Django 4.2.1 on 2023-06-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0003_accesslog_username_alter_accesslog_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="user_id",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
