# Generated by Django 4.2.1 on 2023-11-11 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0006_remove_accesslog_deta_accesslog_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesslog",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Access Log",
                "verbose_name_plural": "Access Logs",
            },
        ),
    ]
