# Generated by Django 4.2.1 on 2024-01-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0010_accesslog_created_by_accesslog_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
    ]
