# Generated by Django 4.2.1 on 2023-06-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="norm",
            name="activity",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="norm",
            name="specification",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="normcomponent",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("LABOUR", "Labour"),
                    ("MATERIAL", "Material"),
                    ("EQUIPMENT", "Equipment"),
                ],
                max_length=20,
            ),
        ),
    ]
