# Generated by Django 4.2.1 on 2023-06-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0002_norm_activity_norm_specification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="norm",
            name="extra_costs",
        ),
        migrations.RemoveField(
            model_name="normextracost",
            name="municipality",
        ),
        migrations.AddField(
            model_name="normextracost",
            name="amount",
            field=models.DecimalField(decimal_places=5, default="0.0", max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="normextracost",
            name="norm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="norm.norm",
            ),
        ),
    ]
