# Generated by Django 4.2.1 on 2023-06-26 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0004_alter_normextracost_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="norm",
            name="activity",
        ),
    ]
