# Generated by Django 4.2.1 on 2023-07-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0007_activitytype_normactivity_activity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="norm",
            name="activity_no",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="norm",
            name="part",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="norm",
            name="part_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="norm",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="norm",
            name="specification_no",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="norm",
            name="sub_part",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="norm",
            name="sub_part_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="normextracost",
            name="on",
            field=models.CharField(
                choices=[
                    ("LABOUR", "Labour"),
                    ("MATERIAL", "Material"),
                    ("EQUIPMENT", "Equipment"),
                    ("TOTAL", "total"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="normextracost",
            name="on_amount",
            field=models.DecimalField(decimal_places=5, default="0.0", max_digits=20),
        ),
    ]
