# Generated by Django 4.2.1 on 2023-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0024_estimate_abstract_of_cost_estimate_district_rate_and_more"),
        ("norm", "0008_norm_activity_no_norm_part_norm_part_id_norm_remarks_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="norm",
            unique_together={
                ("municipality", "activity_no", "item_id", "part_id", "sub_part_id")
            },
        ),
        migrations.AddIndex(
            model_name="norm",
            index=models.Index(
                fields=["activity_no"], name="norm_norm_activit_54f9e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="norm",
            index=models.Index(
                fields=["specification_no"], name="norm_norm_specifi_220d3a_idx"
            ),
        ),
    ]
