# Generated by Django 4.2.1 on 2023-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0009_alter_norm_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="norm",
            name="activity_no",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="norm",
            name="part_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="norm",
            name="specification_no",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="norm",
            name="sub_part_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="norm",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
