# Generated by Django 4.2.1 on 2023-07-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0024_estimate_abstract_of_cost_estimate_district_rate_and_more"),
        ("norm", "0010_alter_norm_activity_no_alter_norm_part_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="norm",
            old_name="part",
            new_name="item_description",
        ),
        migrations.RenameField(
            model_name="norm",
            old_name="sub_part",
            new_name="subpart_description",
        ),
        migrations.AlterUniqueTogether(
            name="norm",
            unique_together={
                ("municipality", "activity_no", "part_id", "sub_part_id", "item_id")
            },
        ),
        migrations.AlterField(
            model_name="norm",
            name="unit_value",
            field=models.DecimalField(
                blank=True, decimal_places=5, default="0.0", max_digits=20
            ),
        ),
    ]
