# Generated by Django 4.2.1 on 2023-07-11 03:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0012_normcomponent_municipality_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="norm",
            unique_together=set(),
        ),
    ]
