# Generated by Django 4.2.1 on 2023-07-18 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0027_estimationrate_road_1_amount_and_more"),
        ("norm", "0013_alter_norm_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="norm",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.project",
            ),
        ),
    ]
