# Generated by Django 4.2.1 on 2023-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0014_norm_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normextracost",
            name="on",
            field=models.CharField(
                choices=[
                    ("LABOUR", "Labour"),
                    ("MATERIAL", "Material"),
                    ("EQUIPMENT", "Equipment"),
                    ("TOTAL", "total"),
                ],
                default="TOTAL",
                max_length=20,
            ),
        ),
    ]
