# Generated by Django 4.2.1 on 2023-10-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0017_norm_created_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="norm",
            name="description_eng",
            field=models.TextField(blank=True),
        ),
    ]
