# Generated by Django 4.2.1 on 2023-10-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0019_alter_activitytype_status_alter_norm_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="norm",
            name="title_eng",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="norm",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
