# Generated by Django 4.2.1 on 2023-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0021_alter_activitytype_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitytype",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="norm",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="normactivity",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="normcomponent",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="normextracost",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
