# Generated by Django 4.2.1 on 2024-06-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0026_alter_normcomponent_norm"),
    ]

    operations = [
        migrations.AddField(
            model_name="norm",
            name="item_description_eng",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="norm",
            name="subpart_description_eng",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="norm",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="norm",
            name="description_eng",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="norm",
            name="item_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="norm",
            name="remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="norm",
            name="subpart_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
