# Generated by Django 4.2.1 on 2023-06-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_planning",
            "0003_banktype_name_chequeformat_name_paymentmedium_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BFI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "full_name_eng",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "registration_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "registration_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "registration_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("office", models.CharField(blank=True, max_length=200, null=True)),
                ("detail", models.CharField(blank=True, max_length=200, null=True)),
                ("status", models.BooleanField(default=False)),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("kramagat", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="bank",
            name="bank_type",
        ),
        migrations.RemoveField(
            model_name="bank",
            name="cheque_format",
        ),
        migrations.RemoveField(
            model_name="bank",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="bank",
            name="current_address",
        ),
        migrations.RemoveField(
            model_name="bank",
            name="former_address",
        ),
    ]
