# Generated by Django 4.2.1 on 2023-06-10 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_planning",
            "0004_bfi_remove_bank_bank_type_remove_bank_cheque_format_and_more",
        ),
        ("employee", "0005_alter_currentworkingdetail_bank_name"),
        (
            "base_model",
            "0004_remove_address_district_remove_address_local_level_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bank",
        ),
        migrations.AddField(
            model_name="bfi",
            name="bank_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_type",
                to="project_planning.banktype",
            ),
        ),
        migrations.AddField(
            model_name="bfi",
            name="cheque_format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cheque_format",
                to="project_planning.chequeformat",
            ),
        ),
        migrations.AddField(
            model_name="bfi",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bfi",
            name="current_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_crr_address",
                to="base_model.address",
            ),
        ),
        migrations.AddField(
            model_name="bfi",
            name="former_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_former_address",
                to="base_model.address",
            ),
        ),
    ]
