# Generated by Django 4.2.1 on 2023-06-10 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0008_alter_bankaccount_branch_name_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="bank_nam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.bfi",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="branch_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
