# Generated by Django 4.2.1 on 2023-06-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0009_bankaccount_bank_nam_alter_bankaccount_branch_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankaccount",
            old_name="bank_nam",
            new_name="bank_name",
        ),
    ]
