# Generated by Django 4.2.1 on 2023-06-10 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "base_model",
            "0004_remove_address_district_remove_address_local_level_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_planning", "0010_rename_bank_nam_bankaccount_bank_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.BooleanField(default=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.BooleanField(default=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "is_loan",
                    models.CharField(
                        blank=True,
                        choices=[("भु. पु.", "भु. पु."), ("हालको", "हालको")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "full_name_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "register_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "register_date_bs",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "register_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("office", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "other_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                (
                    "contact_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_contact_detail",
                        to="base_model.contactdetail",
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_contact_person",
                        to="base_model.contactperson",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_current_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "former_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_former_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "organization_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_type",
                        to="project_planning.organizationtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
