# Generated by Django 4.2.1 on 2023-06-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0011_organizationtype_organization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="contact_details",
            new_name="contact_detail",
        ),
    ]
