# Generated by Django 4.2.1 on 2023-06-11 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "base_model",
            "0004_remove_address_district_remove_address_local_level_and_more",
        ),
        ("project_planning", "0012_rename_contact_details_organization_contact_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.BooleanField(default=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsumerCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.BooleanField(default=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "formation_date_bs",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "formation_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ward_no", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "bank_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("attended_no", models.CharField(blank=True, max_length=5, null=True)),
                ("witness_no", models.CharField(blank=True, max_length=5, null=True)),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "full_name_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "registration_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "registration_date_bs",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "registration_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("office", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "other_detail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.bfi",
                    ),
                ),
                (
                    "bank_account_no",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.bankaccount",
                    ),
                ),
                (
                    "contact_detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cc_contact_detail",
                        to="base_model.contactdetail",
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cc_contact_person",
                        to="base_model.contactperson",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cc_current_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "former_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cc_former_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "member_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.membertype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
