# Generated by Django 4.2.1 on 2023-06-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_planning",
            "0015_unit_targetgroupcategory_targetgroup_strategicsign_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
