# Generated by Django 4.2.1 on 2023-06-12 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_model", "0005_remove_address_ward_no_address_local_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_planning", "0016_delete_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("full_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "full_name_eng",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "registration_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "registration_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "registration_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("office", models.CharField(blank=True, max_length=200, null=True)),
                ("detail", models.CharField(blank=True, max_length=200, null=True)),
                ("status", models.BooleanField(default=False)),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("kramagat", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "contact_detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_contact_detail",
                        to="base_model.contactdetail",
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_contact_person",
                        to="base_model.contactperson",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_crr_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "former_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_former_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "organization_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.organizationtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
