# Generated by Django 4.2.1 on 2023-06-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0017_quantity"),
        (
            "project_planning",
            "0018_standinglisttype_standinglist_roadtype_roadstatus_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="drainage_exit_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="road",
            name="drainage_length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="road",
            name="drainage_length_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drainage_length_unit",
                to="project.unit",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="drainage_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drainage_type",
                to="project_planning.drainagetype",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="drainage_width",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="road",
            name="drainage_width_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drainage_width_unit",
                to="project.unit",
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="other_remarks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="road",
            name="remarks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
