# Generated by Django 4.2.1 on 2023-06-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_planning",
            "0022_subledger_sourcereceipt_sourcebearerentitytype_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subledger",
            name="karmagat",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
