# Generated by Django 4.2.1 on 2023-06-16 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0023_subledger_karmagat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcebearerentity",
            name="bearer_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_bearer_type",
                to="project_planning.sourcebearerentitytype",
            ),
        ),
    ]
