# Generated by Django 4.2.3 on 2023-07-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0025_projectproposedtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcebearerentitytype",
            name="karmagat",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
