# Generated by Django 4.2.3 on 2023-08-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0027_alter_accounttitlemanagement_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcebearerentity",
            name="karmagat",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
