# Generated by Django 4.2.3 on 2023-08-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0028_sourcebearerentity_karmagat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submodule",
            old_name="text",
            new_name="remarks",
        ),
    ]
