# Generated by Django 4.2.1 on 2023-10-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0030_submodule_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttitlemanagement",
            name="base_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accounttitlemanagement",
            name="is_transactable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accounttitlemanagement",
            name="remarks",
            field=models.TextField(blank=True, default=""),
        ),
    ]
