# Generated by Django 4.2.1 on 2023-10-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0033_alter_accounttitlemanagement_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="pan_number",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
