# Generated by Django 4.2.1 on 2023-10-17 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0034_organization_pan_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounttitlemanagement",
            options={"ordering": ("code",)},
        ),
    ]
