# Generated by Django 4.2.1 on 2023-10-18 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_model", "0011_documenttype_code_documenttype_detail_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "project_planning",
            "0036_alter_organization_pan_number_organizationmember_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="member_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_members",
                to="project_planning.membertype",
            ),
        ),
        migrations.AlterField(
            model_name="organizationdocument",
            name="document_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_documents",
                to="base_model.documenttype",
            ),
        ),
        migrations.CreateModel(
            name="ConsumerCommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=500, null=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "full_name_eng",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "position_start_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "position_start_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "position_end_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "position_end_date_eng",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("address", models.CharField(blank=True, max_length=220, null=True)),
                (
                    "consumer_committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="project_planning.consumercommittee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumer_committee_members",
                        to="project_planning.membertype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsumerCommitteeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "consumer_committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="project_planning.consumercommittee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumer_committee_documents",
                        to="base_model.documenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
