# Generated by Django 4.2.1 on 2023-10-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0039_updated_import_chart_of_accounts_script_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttitlemanagement",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="project_planning.accounttitlemanagement",
            ),
        ),
    ]
