# Generated by Django 4.2.1 on 2023-11-27 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0042_alter_budgetsource_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttype",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="अभिभावक योजना प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.projecttype",
                verbose_name="Parent Project Type",
            ),
        ),
        migrations.AlterField(
            model_name="subjectarea",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="अभिभावक विषय क्षेत्र",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.subjectarea",
                verbose_name="Parent Subject Area",
            ),
        ),
    ]
