# Generated by Django 4.2.1 on 2023-11-29 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0044_remove_existing_executiveagency_updates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executiveagency",
            name="address",
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                help_text="बैंक/वित्तीय संस्था",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.bfi",
                verbose_name="Bank/Financial Institution",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="bank_acc_no",
            field=models.CharField(
                blank=True,
                help_text="बैंक खाता नं.",
                max_length=100,
                null=True,
                verbose_name="Bank Account No.",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="bank_branch",
            field=models.CharField(
                blank=True,
                help_text="बैंक शाखा",
                max_length=100,
                null=True,
                verbose_name="Bank Branch",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="consumer_comittee_type",
            field=models.ForeignKey(
                blank=True,
                help_text="उपभोक्ता समिति प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ea_consumer_committee_type",
                to="project_planning.membertype",
                verbose_name="Consumer Committee Type",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="current_address",
            field=models.ForeignKey(
                blank=True,
                help_text="हालको ठेगाना",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ea_current_address",
                to="base_model.address",
                verbose_name="Current Address",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="former_address",
            field=models.ForeignKey(
                blank=True,
                help_text="भूतपूर्व ठेगाना",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ea_former_address",
                to="base_model.address",
                verbose_name="Former Address",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="पूरा नाम (नेपाली)",
                max_length=100,
                null=True,
                verbose_name="Full Name (Nepali)",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="full_name_eng",
            field=models.CharField(
                blank=True,
                help_text="पूरा नाम (अंग्रेजी)",
                max_length=100,
                null=True,
                verbose_name="Full Name (English)",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="kramagat",
            field=models.CharField(
                blank=True,
                help_text="क्रमागत",
                max_length=10,
                null=True,
                verbose_name="Kramagat",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="member_quantity",
            field=models.CharField(
                blank=True,
                help_text="सदस्य मात्रा",
                max_length=100,
                null=True,
                verbose_name="Member Quantity",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="office",
            field=models.CharField(
                blank=True,
                help_text="कार्यालय",
                max_length=100,
                null=True,
                verbose_name="Office",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="present_quantity",
            field=models.CharField(
                blank=True,
                help_text="वर्तमान मात्रा",
                max_length=100,
                null=True,
                verbose_name="Present Quantity",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="registration_date",
            field=models.CharField(
                blank=True,
                help_text="दर्ता मिति (बि.स.)",
                max_length=100,
                null=True,
                verbose_name="Registration Date (BS)",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="registration_date_eng",
            field=models.CharField(
                blank=True,
                help_text="दर्ता मिति (ई.स.)",
                max_length=100,
                null=True,
                verbose_name="Registration Date (AD)",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="registration_no",
            field=models.CharField(
                blank=True,
                help_text="दर्ता नं.",
                max_length=100,
                null=True,
                verbose_name="Registration No.",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="remarks",
            field=models.CharField(
                blank=True,
                help_text="कैफियत",
                max_length=255,
                null=True,
                verbose_name="Remarks",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="ward",
            field=models.CharField(
                blank=True,
                help_text="वडा नं.",
                max_length=5,
                null=True,
                verbose_name="Ward No.",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="witness",
            field=models.CharField(
                blank=True,
                help_text="साक्षी",
                max_length=100,
                null=True,
                verbose_name="Witness",
            ),
        ),
        migrations.AlterField(
            model_name="executiveagency",
            name="contact_detail",
            field=models.ForeignKey(
                blank=True,
                help_text="सम्पर्क विवरण",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ea_contact_detail",
                to="base_model.contactdetail",
                verbose_name="Contact Detail",
            ),
        ),
        migrations.AlterField(
            model_name="executiveagency",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                help_text="सम्पर्क व्यक्ति",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ea_contact_person",
                to="base_model.contactperson",
                verbose_name="Contact Person",
            ),
        ),
        migrations.AlterField(
            model_name="executiveagency",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
    ]
