# Generated by Django 4.2.1 on 2023-11-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_planning",
            "0045_remove_executiveagency_address_executiveagency_bank_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="executiveagency",
            name="date",
            field=models.CharField(
                blank=True,
                help_text="मिति (बि.स.)",
                max_length=100,
                null=True,
                verbose_name="Date (BS)",
            ),
        ),
        migrations.AddField(
            model_name="executiveagency",
            name="date_eng",
            field=models.CharField(
                blank=True,
                help_text="मिति (ई.स.)",
                max_length=100,
                null=True,
                verbose_name="Date (AD)",
            ),
        ),
    ]
