# Generated by Django 4.2.1 on 2023-12-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_model", "0013_populate_gender_table"),
        ("project_planning", "0046_executiveagency_date_executiveagency_date_eng"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consumercommittee",
            old_name="registration_date_bs",
            new_name="registration_date",
        ),
        migrations.RenameField(
            model_name="consumercommittee",
            old_name="ward_no",
            new_name="ward",
        ),
        migrations.RemoveField(
            model_name="consumercommittee",
            name="attended_no",
        ),
        migrations.RemoveField(
            model_name="consumercommittee",
            name="bank_account_no",
        ),
        migrations.RemoveField(
            model_name="consumercommittee",
            name="bank_address",
        ),
        migrations.RemoveField(
            model_name="consumercommittee",
            name="display_order",
        ),
        migrations.RemoveField(
            model_name="consumercommittee",
            name="formation_date_bs",
        ),
        migrations.RemoveField(
            model_name="consumercommittee",
            name="formation_date_eng",
        ),
        migrations.RemoveField(
            model_name="consumercommittee",
            name="member_type",
        ),
        migrations.RemoveField(
            model_name="consumercommittee",
            name="other_detail",
        ),
        migrations.RemoveField(
            model_name="consumercommittee",
            name="witness_no",
        ),
        migrations.AddField(
            model_name="consumercommittee",
            name="bank_acc_no",
            field=models.CharField(
                blank=True,
                help_text="बैंक खाता नं.",
                max_length=100,
                null=True,
                verbose_name="Bank Account No.",
            ),
        ),
        migrations.AddField(
            model_name="consumercommittee",
            name="bank_branch",
            field=models.CharField(
                blank=True,
                help_text="बैंक शाखा",
                max_length=100,
                null=True,
                verbose_name="Bank Branch",
            ),
        ),
        migrations.AddField(
            model_name="consumercommittee",
            name="consumer_comittee_type",
            field=models.ForeignKey(
                blank=True,
                help_text="उपभोक्ता समिति प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cc_consumer_committee_type",
                to="project_planning.membertype",
                verbose_name="Consumer Committee Type",
            ),
        ),
        migrations.AddField(
            model_name="consumercommittee",
            name="date",
            field=models.CharField(
                blank=True,
                help_text="मिति (बि.स.)",
                max_length=100,
                null=True,
                verbose_name="Date (BS)",
            ),
        ),
        migrations.AddField(
            model_name="consumercommittee",
            name="date_eng",
            field=models.CharField(
                blank=True,
                help_text="मिति (ई.स.)",
                max_length=100,
                null=True,
                verbose_name="Date (AD)",
            ),
        ),
        migrations.AddField(
            model_name="consumercommittee",
            name="kramagat",
            field=models.CharField(
                blank=True,
                help_text="क्रमागत",
                max_length=10,
                null=True,
                verbose_name="Kramagat",
            ),
        ),
        migrations.AddField(
            model_name="consumercommittee",
            name="member_quantity",
            field=models.CharField(
                blank=True,
                help_text="सदस्य मात्रा",
                max_length=100,
                null=True,
                verbose_name="Member Quantity",
            ),
        ),
        migrations.AddField(
            model_name="consumercommittee",
            name="present_quantity",
            field=models.CharField(
                blank=True,
                help_text="वर्तमान मात्रा",
                max_length=100,
                null=True,
                verbose_name="Present Quantity",
            ),
        ),
        migrations.AddField(
            model_name="consumercommittee",
            name="witness",
            field=models.CharField(
                blank=True,
                help_text="साक्षी",
                max_length=100,
                null=True,
                verbose_name="Witness",
            ),
        ),
        migrations.AlterField(
            model_name="consumercommittee",
            name="contact_detail",
            field=models.ForeignKey(
                blank=True,
                help_text="सम्पर्क विवरण",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cc_contact_detail",
                to="base_model.contactdetail",
                verbose_name="Contact Detail",
            ),
        ),
        migrations.AlterField(
            model_name="consumercommittee",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                help_text="सम्पर्क व्यक्ति",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cc_contact_person",
                to="base_model.contactperson",
                verbose_name="Contact Person",
            ),
        ),
        migrations.AlterField(
            model_name="consumercommittee",
            name="current_address",
            field=models.ForeignKey(
                blank=True,
                help_text="हालको ठेगाना",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cc_current_address",
                to="base_model.address",
                verbose_name="Current Address",
            ),
        ),
        migrations.AlterField(
            model_name="consumercommittee",
            name="former_address",
            field=models.ForeignKey(
                blank=True,
                help_text="भूतपूर्व ठेगाना",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cc_former_address",
                to="base_model.address",
                verbose_name="Former Address",
            ),
        ),
        migrations.AlterField(
            model_name="consumercommittee",
            name="remarks",
            field=models.CharField(
                blank=True,
                help_text="कैफियत",
                max_length=255,
                null=True,
                verbose_name="Remarks",
            ),
        ),
        migrations.AlterField(
            model_name="consumercommittee",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
    ]
