# Generated by Django 4.2.1 on 2023-12-03 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_model", "0013_populate_gender_table"),
        ("employee", "0017_populate_marital_status_table"),
        (
            "project_planning",
            "0047_rename_registration_date_bs_consumercommittee_registration_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumercommitteemember",
            name="address",
        ),
        migrations.RemoveField(
            model_name="consumercommitteemember",
            name="email",
        ),
        migrations.RemoveField(
            model_name="consumercommitteemember",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="consumercommitteemember",
            name="full_name_eng",
        ),
        migrations.RemoveField(
            model_name="consumercommitteemember",
            name="member_type",
        ),
        migrations.RemoveField(
            model_name="consumercommitteemember",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="citizenship_from",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="citizenship_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="citizenship_start_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="citizenship_start_date_eng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="contact_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm_contact_detail",
                to="base_model.contactdetail",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="dob",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="dob_eng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="ethnicity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="father_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="father_name_eng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="first_name_eng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="grand_father_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="grand_father_name_eng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="is_monitoring_team_member",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="karmagat",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="last_name_eng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="middle_name_eng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="other_detail",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="passport",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="passport_start_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="passport_start_date_eng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="passport_start_district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="permanent_acc_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="permanent_current_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm_permanent_current_address",
                to="base_model.address",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="permanent_former_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm_permanent_former_address",
                to="base_model.address",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm_position",
                to="employee.position",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="position_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm_position_level",
                to="employee.positionlevel",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="religion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="tax_payer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consumer_committee_members",
                to="employee.taxpayer",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="tax_payer_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="temporary_current_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm_temporary_current_address",
                to="base_model.address",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="temporary_former_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm_temporary_former_address",
                to="base_model.address",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="voter_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="voter_start_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="voter_start_date_eng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="consumercommittee",
            name="consumer_comittee_type",
            field=models.CharField(
                blank=True,
                help_text="उपभोक्ता समिति प्रकार",
                max_length=100,
                null=True,
                verbose_name="Consumer Committee Type",
            ),
        ),
        migrations.AlterField(
            model_name="consumercommitteemember",
            name="position_end_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="consumercommitteemember",
            name="position_end_date_eng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="consumercommitteemember",
            name="position_start_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="consumercommitteemember",
            name="position_start_date_eng",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="consumercommitteemember",
            name="remarks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="consumercommitteemember",
            name="status",
            field=models.BooleanField(
                default=True, help_text="स्थिति", verbose_name="Status"
            ),
        ),
    ]
