# Generated by Django 4.2.1 on 2023-12-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0049_remove_consumercommitteedocument_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumercommitteemember",
            name="voter_start_district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
