# Generated by Django 4.2.1 on 2023-12-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0050_consumercommitteemember_voter_start_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumercommitteemember",
            name="member_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm_members",
                to="project_planning.membertype",
            ),
        ),
    ]
