# Generated by Django 4.2.1 on 2023-12-15 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_model", "0013_populate_gender_table"),
        ("employee", "0017_populate_marital_status_table"),
        ("project_planning", "0052_remove_consumercommitteemember_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumercommitteemember",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="लिङ्ग",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm",
                to="employee.country",
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                help_text="लिङ्ग",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm",
                to="base_model.gender",
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="language",
            field=models.ForeignKey(
                blank=True,
                help_text="लिङ्ग",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm",
                to="employee.language",
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                help_text="लिङ्ग",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm",
                to="employee.nationality",
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="consumercommitteemember",
            name="religion",
            field=models.ForeignKey(
                blank=True,
                help_text="धर्म",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ccm",
                to="employee.religion",
                verbose_name="Religion",
            ),
        ),
    ]
