# Generated by Django 4.2.1 on 2024-01-13 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_model", "0016_address_code_contactdetail_code_contactperson_code"),
        ("employee", "0020_cumulativedetail_code_currentworkingdetail_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_planning", "0056_consumercommitteedocument_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="कोड",
                        max_length=55,
                        null=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="नाम",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_eng",
                    models.CharField(
                        blank=True,
                        help_text="नाम (अंग्रेजी)",
                        max_length=100,
                        null=True,
                        verbose_name="Name (Eng)",
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        help_text="विवरण",
                        max_length=500,
                        null=True,
                        verbose_name="Detail",
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True,
                        help_text="मिति (बि.स.)",
                        max_length=100,
                        null=True,
                        verbose_name="Date (BS)",
                    ),
                ),
                (
                    "date_eng",
                    models.CharField(
                        blank=True,
                        help_text="मिति (ई.स.)",
                        max_length=100,
                        null=True,
                        verbose_name="Date (AD)",
                    ),
                ),
                (
                    "ward",
                    models.CharField(
                        blank=True,
                        help_text="वडा नं.",
                        max_length=5,
                        null=True,
                        verbose_name="Ward No.",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="पूरा नाम (नेपाली)",
                        max_length=100,
                        null=True,
                        verbose_name="Full Name (Nepali)",
                    ),
                ),
                (
                    "full_name_eng",
                    models.CharField(
                        blank=True,
                        help_text="पूरा नाम (अंग्रेजी)",
                        max_length=100,
                        null=True,
                        verbose_name="Full Name (English)",
                    ),
                ),
                (
                    "bank_acc_no",
                    models.CharField(
                        blank=True,
                        help_text="बैंक खाता नं.",
                        max_length=100,
                        null=True,
                        verbose_name="Bank Account No.",
                    ),
                ),
                (
                    "bank_branch",
                    models.CharField(
                        blank=True,
                        help_text="बैंक शाखा",
                        max_length=100,
                        null=True,
                        verbose_name="Bank Branch",
                    ),
                ),
                (
                    "consumer_comittee_type",
                    models.CharField(
                        blank=True,
                        help_text="उपभोक्ता समिति प्रकार",
                        max_length=100,
                        null=True,
                        verbose_name="Consumer Committee Type",
                    ),
                ),
                (
                    "present_quantity",
                    models.CharField(
                        blank=True,
                        help_text="वर्तमान मात्रा",
                        max_length=100,
                        null=True,
                        verbose_name="Present Quantity",
                    ),
                ),
                (
                    "member_quantity",
                    models.CharField(
                        blank=True,
                        help_text="सदस्य मात्रा",
                        max_length=100,
                        null=True,
                        verbose_name="Member Quantity",
                    ),
                ),
                (
                    "witness",
                    models.CharField(
                        blank=True,
                        help_text="साक्षी",
                        max_length=100,
                        null=True,
                        verbose_name="Witness",
                    ),
                ),
                (
                    "registration_no",
                    models.CharField(
                        blank=True,
                        help_text="दर्ता नं.",
                        max_length=100,
                        null=True,
                        verbose_name="Registration No.",
                    ),
                ),
                (
                    "registration_date",
                    models.CharField(
                        blank=True,
                        help_text="दर्ता मिति (बि.स.)",
                        max_length=100,
                        null=True,
                        verbose_name="Registration Date (BS)",
                    ),
                ),
                (
                    "registration_date_eng",
                    models.CharField(
                        blank=True,
                        help_text="दर्ता मिति (ई.स.)",
                        max_length=100,
                        null=True,
                        verbose_name="Registration Date (AD)",
                    ),
                ),
                (
                    "office",
                    models.CharField(
                        blank=True,
                        help_text="कार्यालय",
                        max_length=100,
                        null=True,
                        verbose_name="Office",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="कैफियत",
                        max_length=255,
                        null=True,
                        verbose_name="Remarks",
                    ),
                ),
                (
                    "kramagat",
                    models.CharField(
                        blank=True,
                        help_text="क्रमागत",
                        max_length=10,
                        null=True,
                        verbose_name="Kramagat",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        help_text="बैंक/वित्तीय संस्था",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_planning.bfi",
                        verbose_name="Bank/Financial Institution",
                    ),
                ),
                (
                    "contact_detail",
                    models.ForeignKey(
                        blank=True,
                        help_text="सम्पर्क विवरण",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mc_contact_detail",
                        to="base_model.contactdetail",
                        verbose_name="Contact Detail",
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="सम्पर्क व्यक्ति",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mc_contact_person",
                        to="base_model.contactperson",
                        verbose_name="Contact Person",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "current_address",
                    models.ForeignKey(
                        blank=True,
                        help_text="हालको ठेगाना",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mc_current_address",
                        to="base_model.address",
                        verbose_name="Current Address",
                    ),
                ),
                (
                    "former_address",
                    models.ForeignKey(
                        blank=True,
                        help_text="भूतपूर्व ठेगाना",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mc_former_address",
                        to="base_model.address",
                        verbose_name="Former Address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonitoringCommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="कोड",
                        max_length=55,
                        null=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="नाम",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_eng",
                    models.CharField(
                        blank=True,
                        help_text="नाम (अंग्रेजी)",
                        max_length=100,
                        null=True,
                        verbose_name="Name (Eng)",
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        help_text="विवरण",
                        max_length=500,
                        null=True,
                        verbose_name="Detail",
                    ),
                ),
                ("ethnicity", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "is_monitoring_team_member",
                    models.BooleanField(blank=True, default=False),
                ),
                (
                    "tax_payer_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "grand_father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "first_name_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "middle_name_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "last_name_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_name_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "grand_father_name_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dob", models.CharField(blank=True, max_length=100, null=True)),
                ("dob_eng", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "citizenship_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "citizenship_start_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "citizenship_start_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "citizenship_from",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("passport", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "passport_start_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "passport_start_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "passport_start_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("voter_no", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "voter_start_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "voter_start_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "voter_start_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "permanent_acc_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "other_detail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "position_start_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "position_start_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "position_end_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "position_end_date_eng",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("karmagat", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "consumer_committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="project_planning.monitoringcommittee",
                    ),
                ),
                (
                    "contact_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm_contact_detail",
                        to="base_model.contactdetail",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="लिङ्ग",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm",
                        to="employee.country",
                        verbose_name="Gender",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True,
                        help_text="लिङ्ग",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm",
                        to="base_model.gender",
                        verbose_name="Gender",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="लिङ्ग",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm",
                        to="employee.language",
                        verbose_name="Gender",
                    ),
                ),
                (
                    "member_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm_members",
                        to="project_planning.membertype",
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        help_text="लिङ्ग",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm",
                        to="employee.nationality",
                        verbose_name="Gender",
                    ),
                ),
                (
                    "permanent_current_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm_permanent_current_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "permanent_former_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm_permanent_former_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm_position",
                        to="employee.position",
                    ),
                ),
                (
                    "position_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm_position_level",
                        to="employee.positionlevel",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        blank=True,
                        help_text="धर्म",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm",
                        to="employee.religion",
                        verbose_name="Religion",
                    ),
                ),
                (
                    "tax_payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_committee_members",
                        to="employee.taxpayer",
                    ),
                ),
                (
                    "temporary_current_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm_temporary_current_address",
                        to="base_model.address",
                    ),
                ),
                (
                    "temporary_former_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcm_temporary_former_address",
                        to="base_model.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonitoringCommitteeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="कोड",
                        max_length=55,
                        null=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="निर्माण मिति",
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="अद्यावधिक मिति",
                        verbose_name="Updated Date",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="स्थिति", verbose_name="Status"
                    ),
                ),
                (
                    "document",
                    models.FileField(upload_to="consumer_committee_documents/"),
                ),
                (
                    "document_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "document_size",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "consumer_committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="project_planning.monitoringcommittee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="निर्माण गर्ने",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_committee_documents",
                        to="base_model.documenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
