# Generated by Django 4.2.1 on 2024-01-21 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_planning",
            "0057_monitoringcommittee_monitoringcommitteemember_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="monitoringcommitteedocument",
            old_name="consumer_committee",
            new_name="monitoring_committee",
        ),
        migrations.RenameField(
            model_name="monitoringcommitteemember",
            old_name="consumer_committee",
            new_name="monitoring_committee",
        ),
    ]
