# Generated by Django 4.2.1 on 2024-01-28 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_planning",
            "0058_rename_consumer_committee_monitoringcommitteedocument_monitoring_committee_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consumercommitteemember",
            options={"ordering": ("member_type",)},
        ),
    ]
