# Generated by Django 4.2.1 on 2024-03-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "plan_execution",
            "0131_remove_monitoringcommitteedetail_user_committee_monitoring",
        ),
        ("project_planning", "0060_accounttitlemanagement_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringcommitteemember",
            name="user_committee_monitoring",
            field=models.ForeignKey(
                blank=True,
                help_text="उपभोक्ता समिति अनुगमन",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitor_committee",
                to="plan_execution.usercommitteemonitoring",
                verbose_name="User Committee Monitoring",
            ),
        ),
    ]
