# Generated by Django 4.2.1 on 2024-03-05 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_planning",
            "0061_monitoringcommitteemember_user_committee_monitoring",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="consumercommitteedocument",
            old_name="document",
            new_name="document_file",
        ),
        migrations.RenameField(
            model_name="monitoringcommitteedocument",
            old_name="document",
            new_name="document_file",
        ),
    ]
