# Generated by Django 4.2.1 on 2024-05-03 21:04

from django.db import migrations


def populate_collect_payment(apps, schema_editor):
    CollectPayment = apps.get_model("project_planning", "CollectPayment")
    collect_payment_data = [
        {
            "code": "bank-payment",
            "name": "बैंक भुक्तानी",
            "name_eng": "Bank Payment",
        },
        {
            "code": "cash-payment",
            "name": "नगद भुक्तानी",
            "name_eng": "Cash Payment",
        },
        {
            "code": "cheque-payment",
            "name": "चेक भुक्तानी",
            "name_eng": "Cheque Payment",
        },
    ]

    for data in collect_payment_data:
        CollectPayment.objects.get_or_create(**data)


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0063_alter_accounttitlemanagement_created_by_and_more"),
    ]

    operations = []
