CRT_MODELS_LIST = [
    {
        "app_name": "plan_execution",
        "model": "ProjectExecution",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Project Execution",
            "name": "योजना कार्यान्वयन",
            "model": {
                "name": "ProjectExecution",
                "verbose_name": "Project Execution",
                "code": "pe",
            },
            "help_text": "Project Execution",
            "code": "project_execution",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "ConsumerFormulation",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Consumer Formulation",
            "name": "उपभोक्ता छनौट/गठन",
            "model": {
                "name": "ConsumerFormulation",
                "verbose_name": "Consumer Formulation",
                "code": "cf",
            },
            "help_text": "Consumer Formulation",
            "code": "consumer_formulation",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "ProbabilityStudyApprove",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Feasibility Study Report",
            "name": "सम्भाव्यता अध्यन प्रतिबेदन",
            "model": {
                "name": "ProbabilityStudyApprove",
                "verbose_name": "Probability Study Approve",
                "code": "psa",
            },
            "help_text": "Probability Study Approve",
            "code": "probability_study_approve",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "OpeningContractAccount",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Related to Opening Contract/Account",
            "name": "सम्झौता/खाता खोलिदिन सम्बन्धि",
            "model": {
                "name": "OpeningContractAccount",
                "verbose_name": "Opening Contract Account",
                "code": "oca",
            },
            "help_text": "Opening Contract Account",
            "code": "opening_contract_account",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "UserCommitteeMonitoring",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "User Committee Monitoring",
            "name": "उपभोक्ता समिति अनुगमन",
            "model": {
                "name": "UserCommitteeMonitoring",
                "verbose_name": "User Committee Monitoring",
                "code": "ucm",
            },
            "help_text": "User Committee Monitoring",
            "code": "user_committee_monitoring",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "ProjectRevision",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Project Revision",
            "name": "योजना संशोधन",
            "model": {
                "name": "ProjectRevision",
                "verbose_name": "Project Revision",
                "code": "pr",
            },
            "help_text": "Project Revision",
            "code": "project_revision",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "ProjectMobilization",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Project Mobilization",
            "name": "मोबिलैजेशन",
            "model": {
                "name": "ProjectMobilization",
                "verbose_name": "Project Mobilization",
                "code": "pm",
            },
            "help_text": "Project Mobilization",
            "code": "project_mobilization",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "MeasuringBook",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Measuring Book",
            "name": "नापी किताब सम्बन्धि",
            "model": {
                "name": "MeasuringBook",
                "verbose_name": "Measuring Book",
                "code": "mb",
            },
            "help_text": "Measuring Book",
            "code": "measuring_book",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "ProjectDeadline",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Project Deadline",
            "name": "म्याद थप",
            "model": {
                "name": "ProjectDeadline",
                "verbose_name": "Project Deadline",
                "code": "pd",
            },
            "help_text": "Project Deadline",
            "code": "project_deadline",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "PaymentExitBill",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Payment Exit Bill",
            "name": "निकासा",
            "model": {
                "name": "PaymentExitBill",
                "verbose_name": "Payment Exit Bill",
                "code": "peb",
            },
            "help_text": "Payment Exit Bill",
            "code": "payment_exit_bill",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "UserCommitteeProjectWorkComplete",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Project Work Complete",
            "name": "उपभोक्ता समिति/अमानत कार्य सम्पन्न विवरण",
            "model": {
                "name": "UserCommitteeProjectWorkComplete",
                "verbose_name": "User Committee Project Work Complete",
                "code": "ucpwc",
            },
            "help_text": "User Committee Project Work Complete",
            "code": "user_committee_project_work_complete",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "EstimationSubmitAcceptance",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Submission/Acceptance of Estimate",
            "name": "इस्टिमेट पेश/स्वीकृत सम्बन्धि",
            "model": {
                "name": "EstimationSubmitAcceptance",
                "verbose_name": "Estimation Submit Acceptance",
                "code": "esa",
            },
            "help_text": "Estimation Submit Acceptance",
            "code": "estimation_submit_acceptance",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "ProjectTender",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Project Tender",
            "name": "टेन्डर",
            "model": {
                "name": "ProjectTender",
                "verbose_name": "Project Tender",
                "code": "pt",
            },
            "help_text": "Project Tender",
            "code": "project_tender",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "ProjectBidCollection",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Project Bid Collection",
            "name": "बोलपत्र संकलन",
            "model": {
                "name": "ProjectBidCollection",
                "verbose_name": "Project Bid Collection",
                "code": "pbc",
            },
            "help_text": "Project Bid Collection",
            "code": "project_bid_collection",
        },
    },
    {
        "app_name": "plan_execution",
        "model": "ProjectDarbhauBid",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Project Darbhau Bid",
            "name": "दरभाउ पत्र/बोलपत्र स्वीकृत",
            "model": {
                "name": "ProjectDarbhauBid",
                "verbose_name": "Project Darbhau Bid",
                "code": "pdb",
            },
            "help_text": "Project Darbhau Bid",
            "code": "project_darbhau_bid",
        },
    },
    # ProjectAgreement
    {
        "app_name": "plan_execution",
        "model": "ProjectAgreement",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Project Agreement",
            "name": "सम्झौता",
            "model": {
                "name": "ProjectAgreement",
                "verbose_name": "Project Agreement",
                "code": "pa",
            },
            "help_text": "Project Agreement",
            "code": "project_agreement",
        },
    },
    # ProjectFinishedBailReturn
    {
        "app_name": "plan_execution",
        "model": "ProjectFinishedBailReturn",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Project Finished Bail Return",
            "name": "ठेक्कापट्टा कार्य सम्पन्न विवरण",
            "model": {
                "name": "ProjectFinishedBailReturn",
                "verbose_name": "Project Finished Bail Return",
                "code": "pfbr",
            },
            "help_text": "Project Finished Bail Return",
            "code": "project_finished_bail_return",
        },
    },
    # DepositMandate
    {
        "app_name": "plan_execution",
        "model": "DepositMandate",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Deposit Mandate",
            "name": "अमानत कार्यादेश",
            "model": {
                "name": "DepositMandate",
                "verbose_name": "Deposit Mandate",
                "code": "dm",
            },
            "help_text": "Deposit Mandate",
            "code": "deposit_mandate",
        },
    },
    # InstitutionalCollaborationNominatedStaff
    {
        "app_name": "plan_execution",
        "model": "InstitutionalCollaborationNominatedStaff",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Institutional Collaboration Nominated Staff",
            "name": "संस्थागत सहकार्य मनोनित कर्मचारी",
            "model": {
                "name": "InstitutionalCollaborationNominatedStaff",
                "verbose_name": "Institutional Collaboration Nominated Staff",
                "code": "icns",
            },
            "help_text": "Institutional Collaboration Nominated Staff",
            "code": "institutional_collaboration_nominated_staff",
        },
    },
    # InstitutionalCollaborationMandate
    {
        "app_name": "plan_execution",
        "model": "InstitutionalCollaborationMandate",
        "initial_crt_field": True,
        "crt_field": {
            "related_model_names": [],
            "name_eng": "Institutional Collaboration Mandate",
            "name": "संस्थागत सहकार्य कार्यादेश",
            "model": {
                "name": "InstitutionalCollaborationMandate",
                "verbose_name": "Institutional Collaboration Mandate",
                "code": "icm",
            },
            "help_text": "Institutional Collaboration Mandate",
            "code": "institutional_collaboration_mandate",
        },
    },
]
