# Generated by Django 4.2.1 on 2023-08-07 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_execution', '0026_projecttask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=55, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_template_default', models.BooleanField(default=True)),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('orientation', models.CharField(blank=True, choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait')], max_length=10, null=True)),
                ('template_content', models.TextField(blank=True, max_length=10000, null=True)),
                ('template_info', models.CharField(blank=True, max_length=255, null=True)),
                ('client_ward', models.IntegerField(blank=True, null=True)),
                ('is_report_header_show', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('is_ward_template', models.BooleanField(default=False)),
                ('is_new_template', models.BooleanField(default=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_client', to=settings.AUTH_USER_MODEL)),
                ('plan_master_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_plan_master', to=settings.AUTH_USER_MODEL)),
                ('start_pms_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_execution.startpmsprocess')),
                ('template_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_report.reporttype')),
            ],
        ),
    ]
