# Generated by Django 4.2.3 on 2023-08-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_execution", "0026_projecttask"),
        ("project_report", "0002_reporttype_customreporttemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customreporttemplate",
            name="start_pms_process",
            field=models.ForeignKey(
                blank=True,
                help_text="सञ्चालन प्रकृया",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plan_execution.startpmsprocess",
            ),
        ),
    ]
