# Generated by Django 4.2.1 on 2023-08-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_report', '0003_alter_customreporttemplate_start_pms_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefieldmapping',
            name='rnum',
        ),
    ]
