# Generated by Django 4.2.1 on 2023-08-09 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_planning', '0027_alter_accounttitlemanagement_detail_and_more'),
        ('project_report', '0004_remove_templatefieldmapping_rnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefieldmapping',
            name='deleted_uq_code',
        ),
        migrations.AlterField(
            model_name='templatefieldmapping',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templatefieldmapping',
            name='pms_process_id',
            field=models.ForeignKey(blank=True, help_text='ससञ्चालन प्रकृया', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_planning.projectprocess'),
        ),
        migrations.AlterField(
            model_name='templatefieldmapping',
            name='remarks',
            field=models.CharField(blank=True, help_text='कैफियत', max_length=255, null=True),
        ),
    ]
