# Generated by Django 4.2.1 on 2023-10-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_report", "0008_alter_templatefieldmapping_pms_process_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customreporttemplate",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="reporttype",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="templatefieldmapping",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
