# Generated by Django 4.2.1 on 2023-11-29 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "project_report",
            "0012_alter_reporttype_code_alter_reporttype_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatefieldmapping",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="templatefieldmapping",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_template_field_mappings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="templatefieldmapping",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="templatefieldmapping",
            name="name_eng",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="templatefieldmapping",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_template_field_mappings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
