# Generated by Django 4.2.1 on 2023-12-05 10:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_report", "0016_update_and_repopulate_custom_report_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatefieldmapping",
            name="db_column_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255, null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="templatefieldmapping",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
