# Generated by Django 4.2.1 on 2023-12-10 19:49

from django.db import migrations, models

import project_report.validators


class Migration(migrations.Migration):
    dependencies = [
        ("project_report", "0017_templatefieldmapping_db_column_names_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customreporttemplate",
            name="template_content",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[project_report.validators.validate_template_content],
            ),
        ),
    ]
