# Generated by Django 4.2.1 on 2023-12-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_report", "0018_alter_customreporttemplate_template_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatefieldmapping",
            name="report_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
