# Generated by Django 4.2.1 on 2023-12-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_report", "0023_alter_reporttype_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatefieldmapping",
            name="field_type",
            field=models.CharField(
                blank=True,
                choices=[("db_col", "Database Column"), ("table_loop", "Table Loop")],
                default="db_col",
                max_length=255,
                null=True,
            ),
        ),
    ]
