# Generated by Django 4.2.1 on 2023-12-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_report", "0024_templatefieldmapping_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customreporttemplate",
            name="required_renders",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
