# Generated by Django 4.2.1 on 2023-12-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_report", "0026_alter_customreporttemplate_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customreporttemplate",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
