# Generated by Django 4.2.1 on 2024-03-05 19:32

from django.db import migrations

from project_report.models import ReportType as ReportTypeModel

report_types = [
    {
        "code": "cost_estimate_report_general",
        "name_np": "लागत अनुमान सामान्य",
        "text": "Cost Estimate General",
    },
]


def populate_report_types(apps, schema_editor):
    ReportType: ReportTypeModel = apps.get_model("project_report", "ReportType")
    DocumentType = apps.get_model("base_model", "DocumentType")
    db_alias = schema_editor.connection.alias
    for report_type in report_types:
        report_type = ReportType.objects.using(db_alias).create(
            code=report_type["code"],
            name=report_type["name_np"],
            name_eng=report_type["text"],
        )
        DocumentType.objects.using(db_alias).create(
            name=report_type.name,
            name_eng=report_type.name_eng,
            code=report_type.code,
            detail=report_type.detail,
            document_type="report_type",
        )


def reverse_report_types(apps, schema_editor):
    ReportType: ReportTypeModel = apps.get_model("project_report", "ReportType")
    DocumentType = apps.get_model("base_model", "DocumentType")
    db_alias = schema_editor.connection.alias
    report_type_codes = [report_type["code"] for report_type in report_types]
    ReportType.objects.using(db_alias).filter(code__in=report_type_codes).delete()
    DocumentType.objects.using(db_alias).filter(code__in=report_type_codes).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("project_report", "0038_customreporttemplate_updated_by_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_report_types,
            reverse_report_types,
        )
    ]
