# Generated by Django 4.2.1 on 2024-08-06 04:04

from django.db import migrations

from project_report.models import ReportType as ReportTypeModel


def populate_report_types(apps, schema_editor):
    ReportType: ReportTypeModel = apps.get_model("project_report", "ReportType")
    report_types = [
        {
            "code": "estimate_submit_report",
            "text": "Estimate Submission Report",
            "name_np": "इस्टिमेट पेश प्रतिवेदन",
        },
    ]

    db_alias = schema_editor.connection.alias
    for report_type in report_types:
        ReportType.objects.using(db_alias).create(
            code=report_type["code"],
            name=report_type["name_np"],
            name_eng=report_type["text"],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("project_report", "0041_reporttype_verfication_status_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_report_types, reverse_code=migrations.RunPython.noop
        ),
    ]
