# Generated by Django 4.2.1 on 2023-05-14 08:46
from django.db import migrations


def create_financial_years(apps, schema_editor):
    FinancialYear = apps.get_model("project", "FinancialYear")

    financial_years = [
        FinancialYear(start_year=i, end_year=i + 1) for i in range(2070, 2090)
    ]
    db_alias = schema_editor.connection.alias
    FinancialYear.objects.using(db_alias).bulk_create(financial_years)


def create_province(apps, schema_editor):
    Province = apps.get_model("project", "Province")
    provinces = [Province(province_number=i, name=f"Province {i}") for i in range(1, 8)]
    db_alias = schema_editor.connection.alias
    Province.objects.using(db_alias).bulk_create(provinces)


def create_district(apps, schema_editor):
    Province = apps.get_model("project", "Province")
    District = apps.get_model("project", "District")
    db_alias = schema_editor.connection.alias
    provinces = {
        province.province_number: province
        for province in Province.objects.using(db_alias).all()
    }
    with open("project/migrations/districts.txt") as f:
        lines = f.read().splitlines()
        districts = []
        for line in lines:
            province_no, district_name = line.strip().split("\t")
            province = provinces[province_no]
            districts.append(District(name_eng=district_name, province=province))
        District.objects.using(db_alias).bulk_create(districts)


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_initial"),
    ]

    operations = [
        # migrations.RunPython(create_province),
        # migrations.RunPython(create_district),
        migrations.RunPython(create_financial_years),
    ]
