# Generated by Django 4.2.1 on 2023-05-18 07:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_rename_assigned_muncipality_user_assigned_municipality"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0004_alter_muncipality_options_rate_muncipality_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Muncipality",
            new_name="Municipality",
        ),
        migrations.AlterModelOptions(
            name="municipality",
            options={"verbose_name_plural": "Municipalities"},
        ),
        migrations.RenameField(
            model_name="districtratefiles",
            old_name="muncipality",
            new_name="municipality",
        ),
        migrations.RenameField(
            model_name="rate",
            old_name="muncipality",
            new_name="municipality",
        ),
        migrations.RenameField(
            model_name="ward",
            old_name="muncipality",
            new_name="municipality",
        ),
    ]
