# Generated by Django 4.2.1 on 2023-05-22 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0007_project_financial_year_project_municipality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jdcomment",
            name="job_description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="project.jobdescription",
            ),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_job_descriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="jobdescription",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_descriptions",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="jobdescriptionfile",
            name="job_description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="project.jobdescription",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="financial_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.district",
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="financial_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.topic",
            ),
        ),
    ]
