# Generated by Django 4.2.1 on 2023-06-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0009_alter_jobdescription_approval_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialyear",
            name="fy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
