# Generated by Django 4.2.1 on 2023-06-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0010_financialyear_fy"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ward",
            field=models.ManyToManyField(to="project.ward"),
        ),
    ]
