# Generated by Django 4.2.1 on 2023-06-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0012_ratecategory_rate_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimationrate",
            name="road_1_distance",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estimationrate",
            name="road_2_distance",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estimationrate",
            name="road_3_distance",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
