# Generated by Django 4.2.1 on 2023-06-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0015_rate_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="road_1_rate",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estimate",
            name="road_2_rate",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estimate",
            name="road_3_rate",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
