# Generated by Django 4.2.1 on 2023-06-11 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0016_estimate_road_1_rate_estimate_road_2_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("PART", "Part"), ("SUB_PART", "Sub Part")],
                        max_length=20,
                    ),
                ),
                ("line_number", models.CharField(blank=True, max_length=250)),
                ("s_no", models.CharField(blank=True, max_length=250)),
                ("description", models.TextField(blank=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "no",
                    models.DecimalField(
                        blank=True, decimal_places=5, default="0.0", max_digits=20
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=5, default="0.0", max_digits=20
                    ),
                ),
                (
                    "breadth",
                    models.DecimalField(
                        blank=True, decimal_places=5, default="0.0", max_digits=20
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=5, default="0.0", max_digits=20
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=5, default="0.0", max_digits=20
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=5, default="0.0", max_digits=20
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimation_rates",
                        to="project.project",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.unit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
