# Generated by Django 4.2.1 on 2023-06-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0017_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="quantity",
            name="itemid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="quantity",
            name="partid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="quantity",
            name="subpartid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="type",
            field=models.CharField(
                choices=[("PART", "Part"), ("SUB_PART", "Sub Part"), ("ITEM", "Item")],
                max_length=20,
            ),
        ),
    ]
