# Generated by Django 4.2.1 on 2023-06-15 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0018_quantity_itemid_quantity_partid_quantity_subpartid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quantity",
            options={"verbose_name_plural": "Quantities"},
        ),
    ]
