# Generated by Django 4.2.1 on 2023-06-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0019_alter_quantity_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimationrate",
            name="area",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
