# Generated by Django 4.2.1 on 2023-06-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0020_estimationrate_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimationrate",
            name="estimate",
        ),
        migrations.AddField(
            model_name="estimationrate",
            name="part_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="estimationrate",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.project",
            ),
        ),
    ]
