# Generated by Django 4.2.1 on 2023-07-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0023_municipality_email_municipality_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="abstract_of_cost",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="district_rate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="rate_analysis_of_general_work",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="summary_of_project",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="summary_of_rates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="transportation_of_material",
            field=models.BooleanField(default=True),
        ),
    ]
