# Generated by Django 4.2.1 on 2023-07-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0026_unit_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimationrate",
            name="road_1_amount",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="estimationrate",
            name="road_2_amount",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="estimationrate",
            name="road_3_amount",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
