# Generated by Django 4.2.1 on 2023-07-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0028_ratesource_ratearea_rate_area_rate_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="project",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.project",
            ),
        ),
    ]
