# Generated by Django 4.2.1 on 2023-07-30 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("norm", "0014_norm_project"),
        ("project", "0030_estimationrate_norm_alter_quantity_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimationrate",
            name="norm",
        ),
        migrations.AddField(
            model_name="quantity",
            name="norm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="norm.norm",
            ),
        ),
    ]
