# Generated by Django 4.2.1 on 2023-07-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0031_remove_estimationrate_norm_quantity_norm"),
    ]

    operations = [
        migrations.AddField(
            model_name="quantity",
            name="subtopicid",
            field=models.CharField(blank=True, default="0", max_length=255),
        ),
        migrations.AddField(
            model_name="quantity",
            name="topicid",
            field=models.CharField(blank=True, default="0", max_length=255),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="itemid",
            field=models.CharField(blank=True, default="0", max_length=255),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="subpartid",
            field=models.CharField(blank=True, default="0", max_length=255),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="type",
            field=models.CharField(
                choices=[
                    ("PART", "Part"),
                    ("SUB_PART", "Sub Part"),
                    ("TOPIC", "Topic"),
                    ("SUB_TOPIC", "Sub Topic"),
                    ("ITEM", "Item"),
                    ("TOTAL", "Total"),
                ],
                max_length=20,
            ),
        ),
    ]
