# Generated by Django 4.2.1 on 2023-08-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0032_quantity_subtopicid_quantity_topicid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quantity",
            name="is_leaf",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
