# Generated by Django 4.2.1 on 2023-08-04 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0033_quantity_is_leaf"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("s_no", models.CharField(blank=True, max_length=255)),
                ("descriptoin", models.CharField(blank=True, max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=5, default="0.0", max_digits=20
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=5, default="0.0", max_digits=20
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
