# Generated by Django 4.2.1 on 2023-08-04 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0034_summaryextra"),
    ]

    operations = [
        migrations.RenameField(
            model_name="summaryextra",
            old_name="descriptoin",
            new_name="description",
        ),
    ]
