# Generated by Django 4.2.1 on 2023-08-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_rename_descriptoin_summaryextra_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryextra',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
