# Generated by Django 4.2.1 on 2023-08-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_alter_summaryextra_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project.quantity'),
        ),
    ]
