# Generated by Django 4.2.1 on 2023-08-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0039_quantity_provisional"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="detailed_quantity_calculation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="material_cost_with_transport",
            field=models.BooleanField(default=True),
        ),
    ]
