# Generated by Django 4.2.1 on 2023-09-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0040_estimate_detailed_quantity_calculation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="office_address",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="municipality",
            name="office_name",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="municipality",
            name="sub_name",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
