# Generated by Django 4.2.1 on 2023-09-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project",
            "0041_municipality_office_address_municipality_office_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="office_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="office_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="sub_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
