# Generated by Django 4.2.1 on 2023-09-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0042_alter_municipality_office_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=5, default="0.0", max_digits=20
            ),
        ),
    ]
