# Generated by Django 4.2.1 on 2023-10-08 12:23

from django.db import migrations, models

from project.models import District as DistrictModel
from utils.import_csv_data import get_addresses_from_csv


def remove_excess_districts(apps, schema_editor):
    District: DistrictModel = apps.get_model("project", "District")
    federal_addresses = get_addresses_from_csv()
    district_names = [
        district["name_en"] for district in federal_addresses["districts"]
    ]
    db_alias = schema_editor.connection.alias
    District.objects.using(db_alias).filter(name_eng__in=district_names).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0044_alter_province_province_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="province",
            options={"ordering": ("province_number",)},
        ),
        migrations.AlterField(
            model_name="municipality",
            name="number_of_wards",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
