# Generated by Django 4.2.1 on 2023-10-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0048_update_federal_address_codes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="district",
            options={"ordering": ("code",)},
        ),
        migrations.AlterModelOptions(
            name="municipality",
            options={"ordering": ("code",)},
        ),
        migrations.AlterModelOptions(
            name="province",
            options={"ordering": ("code",)},
        ),
        migrations.AddField(
            model_name="rate",
            name="description_eng",
            field=models.TextField(blank=True),
        ),
    ]
