# Generated by Django 4.2.1 on 2023-10-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0049_alter_district_options_alter_municipality_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="rate",
            name="description_eng",
        ),
        migrations.AlterField(
            model_name="rate",
            name="title",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="rate",
            name="title_eng",
            field=models.TextField(blank=True),
        ),
    ]
