# Generated by Django 4.2.1 on 2023-10-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project",
            "0051_jobdescription_status_of_model_alter_district_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="rate",
            name="title_eng",
            field=models.TextField(blank=True, default=""),
        ),
    ]
