# Generated by Django 4.2.1 on 2023-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0053_alter_topic_name_alter_topic_name_eng_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
