# Generated by Django 4.2.1 on 2023-12-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0056_alter_project_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summaryextra",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
