# Generated by Django 4.2.1 on 2023-12-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0057_alter_summaryextra_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="नाम",
                max_length=500,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ward",
            field=models.ManyToManyField(
                blank=True,
                help_text="वडा",
                null=True,
                to="project.ward",
                verbose_name="Ward",
            ),
        ),
    ]
