# Generated by Django 4.2.1 on 2023-12-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project",
            "0059_alter_districtratefiles_status_alter_estimate_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantity",
            name="area",
            field=models.DecimalField(
                blank=True, decimal_places=5, default="0.0", max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="breadth",
            field=models.DecimalField(
                blank=True, decimal_places=5, default="0.0", max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=5, default="0.0", max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="is_leaf",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="itemid",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=5, default="0.0", max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="line_number",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="no",
            field=models.DecimalField(
                blank=True, decimal_places=5, default="0.0", max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="partid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="provisional",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=5, default="0.0", max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="s_no",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="subpartid",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="subtopicid",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="topicid",
            field=models.CharField(blank=True, default="0", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="quantity",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PART", "Part"),
                    ("SUB_PART", "Sub Part"),
                    ("TOPIC", "Topic"),
                    ("SUB_TOPIC", "Sub Topic"),
                    ("ITEM", "Item"),
                    ("TOTAL", "Total"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
