# Generated by Django 4.2.1 on 2024-01-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0062_populate_federal_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="federal_type",
            field=models.ForeignKey(
                blank=True,
                help_text="संघीय प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.federaltype",
                verbose_name="Federal Type",
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="federal_type",
            field=models.ForeignKey(
                blank=True,
                help_text="संघीय प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.federaltype",
                verbose_name="Federal Type",
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="federal_type",
            field=models.ForeignKey(
                blank=True,
                help_text="संघीय प्रकार",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.federaltype",
                verbose_name="Federal Type",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
    ]
