# Generated by Django 4.2.1 on 2024-01-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0064_update_federal_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="ward",
            field=models.ManyToManyField(
                blank=True, help_text="वडा", to="project.ward", verbose_name="Ward"
            ),
        ),
    ]
