# Generated by Django 4.2.1 on 2024-03-09 18:03

from django.db import migrations

from project.models import Rate as RateModel

financial_year_with_data_id = 9
financial_year_without_data_id = 11


def swap_rate_values(apps, schema_editor):
    Rate: RateModel = apps.get_model("project", "Rate")
    rates = Rate.objects.filter(financial_year_id=financial_year_with_data_id)

    for rate_with_data in rates:
        rate_without_data = Rate.objects.filter(
            financial_year__id=financial_year_without_data_id,
            topic=rate_with_data.topic,
            category=rate_with_data.category,
        ).first()

        if rate_without_data:
            rate_with_data.amount, rate_without_data.amount = (
                rate_without_data.amount,
                rate_with_data.amount,
            )
            rate_with_data.save()
            rate_without_data.save()


def reverse_swap_rate_values(apps, schema_editor):
    Rate: RateModel = apps.get_model("project", "Rate")
    rates = Rate.objects.filter(financial_year_id=financial_year_with_data_id)

    for rate_with_data in rates:
        rate_without_data = Rate.objects.filter(
            financial_year__id=financial_year_without_data_id,
            topic=rate_with_data.topic,
            category=rate_with_data.category,
        ).first()

        if rate_without_data:
            rate_with_data.amount, rate_without_data.amount = (
                rate_without_data.amount,
                rate_with_data.amount,
            )
            rate_with_data.save()
            rate_without_data.save()


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0066_district_updated_by_districtratefiles_updated_by_and_more"),
    ]

    operations = [
        migrations.RunPython(swap_rate_values, reverse_swap_rate_values),
    ]
