# Generated by Django 4.2.1 on 2024-03-09 18:12

from django.db import migrations

from project.models import EstimationRate as EstimationRateModel


def update_existing_estimation_rates(apps, schema_editor):
    EstimationRate: EstimationRateModel = apps.get_model("project", "EstimationRate")
    rates = EstimationRate.objects.all()

    for rate in rates:
        rate.amount = (rate.rate.amount if rate.rate else 0) * 100
        rate.save()


def reverse_update_existing_estimation_rates(apps, schema_editor):
    EstimationRate: EstimationRateModel = apps.get_model("project", "EstimationRate")
    rates = EstimationRate.objects.all().update(amount=0)


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0067_swap_rate_values"),
    ]

    operations = [
        migrations.RunPython(
            update_existing_estimation_rates, reverse_update_existing_estimation_rates
        ),
    ]
