# Generated by Django 4.2.1 on 2024-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0068_update_existing_estimation_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="quantity",
            name="quantity_type",
            field=models.CharField(
                choices=[("DIAMETER", "Diameter"), ("DEFAULT", "Default")],
                default="DEFAULT",
                max_length=255,
            ),
        ),
    ]
