# Generated by Django 4.2.1 on 2023-12-05 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0056_alter_project_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettingCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        help_text="नगरपालिका",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.municipality",
                        verbose_name="Municipality",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Setting Collection",
                "verbose_name_plural": "App Setting Collections",
            },
        ),
        migrations.CreateModel(
            name="ImageAppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "setting_type",
                    models.CharField(
                        blank=True,
                        choices=[("general", "General"), ("project", "Project")],
                        help_text="सेटिङ्ग प्रकार",
                        max_length=55,
                        null=True,
                        verbose_name="Setting Type",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="कोड",
                        max_length=55,
                        null=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="नाम",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_eng",
                    models.CharField(
                        blank=True,
                        help_text="नाम (अंग्रेजी)",
                        max_length=100,
                        null=True,
                        verbose_name="Name (Eng)",
                    ),
                ),
                (
                    "use_in_report",
                    models.BooleanField(
                        default=False,
                        help_text="रिपोर्टमा प्रयोग गर्नुहोस्",
                        verbose_name="Use in Report",
                    ),
                ),
                (
                    "value",
                    models.ImageField(
                        blank=True,
                        help_text="मान",
                        null=True,
                        upload_to="",
                        verbose_name="Value",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("image", "Image"),
                            ("file", "File"),
                        ],
                        default="image",
                        editable=False,
                        help_text="मान प्रकार",
                        max_length=55,
                        verbose_name="Value Type",
                    ),
                ),
                (
                    "setting_collection",
                    models.ForeignKey(
                        help_text="सेटिङ्ग संग्रह",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_settings.appsettingcollection",
                        verbose_name="Setting Collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image App Setting",
                "verbose_name_plural": "Image App Settings",
            },
        ),
        migrations.CreateModel(
            name="BooleanAppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "setting_type",
                    models.CharField(
                        blank=True,
                        choices=[("general", "General"), ("project", "Project")],
                        help_text="सेटिङ्ग प्रकार",
                        max_length=55,
                        null=True,
                        verbose_name="Setting Type",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="कोड",
                        max_length=55,
                        null=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="नाम",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_eng",
                    models.CharField(
                        blank=True,
                        help_text="नाम (अंग्रेजी)",
                        max_length=100,
                        null=True,
                        verbose_name="Name (Eng)",
                    ),
                ),
                (
                    "use_in_report",
                    models.BooleanField(
                        default=False,
                        help_text="रिपोर्टमा प्रयोग गर्नुहोस्",
                        verbose_name="Use in Report",
                    ),
                ),
                (
                    "value",
                    models.BooleanField(
                        default=False, help_text="मान", verbose_name="Value"
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("image", "Image"),
                            ("file", "File"),
                        ],
                        default="boolean",
                        editable=False,
                        help_text="मान प्रकार",
                        max_length=55,
                        verbose_name="Value Type",
                    ),
                ),
                (
                    "setting_collection",
                    models.ForeignKey(
                        help_text="सेटिङ्ग संग्रह",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_settings.appsettingcollection",
                        verbose_name="Setting Collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boolean App Setting",
                "verbose_name_plural": "Boolean App Settings",
            },
        ),
    ]
