# Generated by Django 4.2.1 on 2023-12-06 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0002_create_app_settings_collection_for_existing_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booleanappsetting",
            name="setting_collection",
            field=models.ForeignKey(
                help_text="सेटिङ्ग संग्रह",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boolean_app_settings",
                to="app_settings.appsettingcollection",
                verbose_name="Setting Collection",
            ),
        ),
        migrations.AlterField(
            model_name="imageappsetting",
            name="setting_collection",
            field=models.ForeignKey(
                help_text="सेटिङ्ग संग्रह",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_app_settings",
                to="app_settings.appsettingcollection",
                verbose_name="Setting Collection",
            ),
        ),
    ]
