# Generated by Django 4.2.1 on 2023-12-30 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0060_alter_quantity_area_alter_quantity_breadth_and_more"),
        ("app_settings", "0004_appsettingcollection_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettingcollection",
            name="municipality",
            field=models.ForeignKey(
                help_text="नगरपालिका",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="app_setting_collections",
                to="project.municipality",
                verbose_name="Municipality",
            ),
        ),
    ]
