# Generated by Django 4.2.1 on 2024-01-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0006_alter_appsettingcollection_municipality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booleanappsetting",
            name="setting_type",
            field=models.CharField(
                choices=[("general", "General"), ("yojana", "Yojana")],
                default="general",
                help_text="सेटिङ्ग प्रकार",
                max_length=55,
                verbose_name="Setting Type",
            ),
        ),
        migrations.AlterField(
            model_name="imageappsetting",
            name="setting_type",
            field=models.CharField(
                choices=[("general", "General"), ("yojana", "Yojana")],
                default="general",
                help_text="सेटिङ्ग प्रकार",
                max_length=55,
                verbose_name="Setting Type",
            ),
        ),
        migrations.AlterField(
            model_name="integerappsetting",
            name="setting_type",
            field=models.CharField(
                choices=[("general", "General"), ("yojana", "Yojana")],
                default="general",
                help_text="सेटिङ्ग प्रकार",
                max_length=55,
                verbose_name="Setting Type",
            ),
        ),
    ]
