# Generated by Django 4.2.1 on 2024-01-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0009_alter_booleanappsetting_value_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booleanappsetting",
            name="in_app_model",
            field=models.CharField(
                blank=True,
                help_text="एप मा मोडेल",
                max_length=55,
                null=True,
                verbose_name="In App Model",
            ),
        ),
        migrations.AddField(
            model_name="booleanappsetting",
            name="in_app_model_field",
            field=models.CharField(
                blank=True,
                help_text="एप मा मोडेल फिल्ड",
                max_length=55,
                null=True,
                verbose_name="In App Model Field",
            ),
        ),
        migrations.AddField(
            model_name="booleanappsetting",
            name="in_app_municipality_field",
            field=models.CharField(
                blank=True,
                help_text="एप मा नगरपालिका फिल्ड",
                max_length=55,
                null=True,
                verbose_name="In App Municipality Field",
            ),
        ),
        migrations.AddField(
            model_name="booleanappsetting",
            name="setting_function",
            field=models.CharField(
                choices=[("local_value", "Local Value"), ("DB_value", "DB Value")],
                default="local_value",
                help_text="सेटिङ्ग कार्य",
                max_length=55,
                verbose_name="Setting Function",
            ),
        ),
        migrations.AddField(
            model_name="enumappsetting",
            name="in_app_model",
            field=models.CharField(
                blank=True,
                help_text="एप मा मोडेल",
                max_length=55,
                null=True,
                verbose_name="In App Model",
            ),
        ),
        migrations.AddField(
            model_name="enumappsetting",
            name="in_app_model_field",
            field=models.CharField(
                blank=True,
                help_text="एप मा मोडेल फिल्ड",
                max_length=55,
                null=True,
                verbose_name="In App Model Field",
            ),
        ),
        migrations.AddField(
            model_name="enumappsetting",
            name="in_app_municipality_field",
            field=models.CharField(
                blank=True,
                help_text="एप मा नगरपालिका फिल्ड",
                max_length=55,
                null=True,
                verbose_name="In App Municipality Field",
            ),
        ),
        migrations.AddField(
            model_name="enumappsetting",
            name="setting_function",
            field=models.CharField(
                choices=[("local_value", "Local Value"), ("DB_value", "DB Value")],
                default="local_value",
                help_text="सेटिङ्ग कार्य",
                max_length=55,
                verbose_name="Setting Function",
            ),
        ),
        migrations.AddField(
            model_name="imageappsetting",
            name="in_app_model",
            field=models.CharField(
                blank=True,
                help_text="एप मा मोडेल",
                max_length=55,
                null=True,
                verbose_name="In App Model",
            ),
        ),
        migrations.AddField(
            model_name="imageappsetting",
            name="in_app_model_field",
            field=models.CharField(
                blank=True,
                help_text="एप मा मोडेल फिल्ड",
                max_length=55,
                null=True,
                verbose_name="In App Model Field",
            ),
        ),
        migrations.AddField(
            model_name="imageappsetting",
            name="in_app_municipality_field",
            field=models.CharField(
                blank=True,
                help_text="एप मा नगरपालिका फिल्ड",
                max_length=55,
                null=True,
                verbose_name="In App Municipality Field",
            ),
        ),
        migrations.AddField(
            model_name="imageappsetting",
            name="setting_function",
            field=models.CharField(
                choices=[("local_value", "Local Value"), ("DB_value", "DB Value")],
                default="local_value",
                help_text="सेटिङ्ग कार्य",
                max_length=55,
                verbose_name="Setting Function",
            ),
        ),
        migrations.AddField(
            model_name="integerappsetting",
            name="in_app_model",
            field=models.CharField(
                blank=True,
                help_text="एप मा मोडेल",
                max_length=55,
                null=True,
                verbose_name="In App Model",
            ),
        ),
        migrations.AddField(
            model_name="integerappsetting",
            name="in_app_model_field",
            field=models.CharField(
                blank=True,
                help_text="एप मा मोडेल फिल्ड",
                max_length=55,
                null=True,
                verbose_name="In App Model Field",
            ),
        ),
        migrations.AddField(
            model_name="integerappsetting",
            name="in_app_municipality_field",
            field=models.CharField(
                blank=True,
                help_text="एप मा नगरपालिका फिल्ड",
                max_length=55,
                null=True,
                verbose_name="In App Municipality Field",
            ),
        ),
        migrations.AddField(
            model_name="integerappsetting",
            name="setting_function",
            field=models.CharField(
                choices=[("local_value", "Local Value"), ("DB_value", "DB Value")],
                default="local_value",
                help_text="सेटिङ्ग कार्य",
                max_length=55,
                verbose_name="Setting Function",
            ),
        ),
        migrations.AlterField(
            model_name="booleanappsetting",
            name="setting_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("yojana", "Yojana"),
                    ("report", "Report"),
                ],
                default="general",
                help_text="सेटिङ्ग प्रकार",
                max_length=55,
                verbose_name="Setting Type",
            ),
        ),
        migrations.AlterField(
            model_name="enumappsetting",
            name="setting_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("yojana", "Yojana"),
                    ("report", "Report"),
                ],
                default="general",
                help_text="सेटिङ्ग प्रकार",
                max_length=55,
                verbose_name="Setting Type",
            ),
        ),
        migrations.AlterField(
            model_name="imageappsetting",
            name="setting_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("yojana", "Yojana"),
                    ("report", "Report"),
                ],
                default="general",
                help_text="सेटिङ्ग प्रकार",
                max_length=55,
                verbose_name="Setting Type",
            ),
        ),
        migrations.AlterField(
            model_name="integerappsetting",
            name="setting_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("yojana", "Yojana"),
                    ("report", "Report"),
                ],
                default="general",
                help_text="सेटिङ्ग प्रकार",
                max_length=55,
                verbose_name="Setting Type",
            ),
        ),
    ]
