# Generated by Django 4.2.1 on 2024-01-09 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_settings", "0010_booleanappsetting_in_app_model_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booleanappsetting",
            old_name="in_app_municipality_field",
            new_name="in_app_municipality_id_field",
        ),
        migrations.RenameField(
            model_name="enumappsetting",
            old_name="in_app_municipality_field",
            new_name="in_app_municipality_id_field",
        ),
        migrations.RenameField(
            model_name="imageappsetting",
            old_name="in_app_municipality_field",
            new_name="in_app_municipality_id_field",
        ),
        migrations.RenameField(
            model_name="integerappsetting",
            old_name="in_app_municipality_field",
            new_name="in_app_municipality_id_field",
        ),
    ]
