# Generated by Django 4.2.1 on 2023-05-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_assigned_muncipality"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("province_user", "Province User"),
                    ("ward_user", "Ward User"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
