# Generated by Django 4.2.1 on 2023-05-18 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_user_user_permissions_alter_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="assigned_muncipality",
            new_name="assigned_municipality",
        ),
    ]
