# Generated by Django 4.2.1 on 2023-05-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0004_rename_assigned_muncipality_user_assigned_municipality"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verfied",
            field=models.BooleanField(default=False),
        ),
    ]
