# Generated by Django 4.2.1 on 2023-05-24 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="verfied",
            new_name="verified",
        ),
    ]
