# Generated by Django 4.2.1 on 2023-06-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_rename_verfied_user_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_picture/"
            ),
        ),
    ]
