# Generated by Django 4.2.1 on 2023-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="detail",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ip_address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
