# Generated by Django 4.2.1 on 2023-06-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_user_detail_user_ip_address_user_last_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
