# Generated by Django 4.2.1 on 2023-10-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_userrole_user_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("MUNICIPALITY_USER", "Municipality User"),
                    ("WARD_USER", "Ward User"),
                ],
                default="ADMIN",
                max_length=20,
            ),
        ),
    ]
