# Generated by Django 4.2.1 on 2023-10-02 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import user.validators


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0043_alter_rate_amount"),
        ("user", "0013_alter_user_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "data_size",
                    models.CharField(
                        choices=[("MB", "Megabyte"), ("GB", "Gigabyte")],
                        default="MB",
                        max_length=2,
                    ),
                ),
                ("data_limit", models.PositiveIntegerField(default=0)),
                ("subdomain", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "main_admin",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_properties",
                        to=settings.AUTH_USER_MODEL,
                        validators=[
                            user.validators.validate_main_admin_for_vendor_properties
                        ],
                    ),
                ),
                (
                    "municipality",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.municipality",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
