# Generated by Django 4.2.1 on 2023-10-02 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import user.validators


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="main_admin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_details",
                to=settings.AUTH_USER_MODEL,
                validators=[user.validators.validate_main_admin_for_vendor_properties],
            ),
        ),
    ]
