# Generated by Django 4.2.1 on 2023-10-05 00:31

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0016_alter_client_data_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="valid_till",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="data_limit",
            field=models.PositiveIntegerField(
                default=512,
                validators=[
                    django.core.validators.MaxValueValidator(1024),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
