# Generated by Django 4.2.1 on 2023-10-11 08:49

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0017_client_valid_till_alter_client_data_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="main_admin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_details",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="valid_till",
            field=models.DateField(default=datetime.date(2023, 10, 11)),
        ),
    ]
