# Generated by Django 4.2.1 on 2023-10-11 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0018_alter_client_main_admin_alter_client_valid_till"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="data_limit",
        ),
        migrations.RemoveField(
            model_name="client",
            name="data_size",
        ),
    ]
