# Generated by Django 4.2.1 on 2023-10-11 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0019_remove_client_data_limit_remove_client_data_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="valid_till",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
