# Generated by Django 4.2.1 on 2023-10-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0020_alter_client_valid_till"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="userrole",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
