# Generated by Django 4.2.1 on 2023-10-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0024_alter_client_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_role",
        ),
        migrations.AddField(
            model_name="user",
            name="user_role",
            field=models.ManyToManyField(related_name="users", to="user.userrole"),
        ),
    ]
