# Generated by Django 4.2.1 on 2023-10-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0026_remove_client_valid_till"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="user.userrole"
            ),
        ),
    ]
