# Generated by Django 4.2.1 on 2023-11-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0028_client_valid_till"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_active",
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
