# Generated by Django 4.2.1 on 2023-11-17 03:25

import django.db.models.deletion
from django.db import migrations, models

import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0053_alter_topic_name_alter_topic_name_eng_and_more"),
        ("user", "0029_remove_user_last_active_alter_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="digital_signature",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.digital_signature_name
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="digital_signature_verification_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_digital_signature_verified",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="municipality",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="project.municipality",
            ),
        ),
    ]
