# Generated by Django 4.2.1 on 2023-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0031_alter_client_created_by_alter_client_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
