# Generated by Django 4.2.1 on 2023-12-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0033_permission_alter_userrole_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "level",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="user.permission",
                    ),
                ),
            ],
            options={
                "ordering": ("level",),
            },
        ),
        migrations.AlterField(
            model_name="userrole",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="granted_roles", to="user.permission"
            ),
        ),
    ]
