# Generated by Django 4.2.1 on 2024-01-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0038_user_assigned_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="कोड",
                max_length=55,
                null=True,
                verbose_name="Code",
            ),
        ),
    ]
