# Generated by Django 4.2.1 on 2024-01-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0040_client_database_host_client_database_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="subdomain",
            field=models.CharField(
                default="yojana.lgerp.org", max_length=255, unique=True
            ),
        ),
    ]
