# Generated by Django 4.2.1 on 2024-02-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0041_alter_client_subdomain"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_app_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "External User",
                "verbose_name_plural": "External Users",
            },
        ),
    ]
