# Generated by Django 4.2.1 on 2024-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0042_externaluser"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="eservice_url",
            field=models.CharField(
                blank=True, default="eservice.pms.lgerp.org", max_length=255, null=True
            ),
        ),
    ]
