# Generated by Django 4.2.1 on 2024-03-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0044_client_updated_by_permission_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
