# Generated by Django 4.2.1 on 2024-03-19 04:08

from django.db import migrations

from utils.csv_import.client_details import ClientDetails


def populate_client_client_ids(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Client = apps.get_model("user", "Client")
    client_details = ClientDetails.create()
    for client in Client.objects.all():
        client_id = client_details.get_client_details_by_address_mapping_code(
            client.municipality.code
        )["client_id"].values
        if len(client_id) > 0:
            client.client_id = client_id[0]
            client.save()


def revert_client_client_ids(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Client = apps.get_model("user", "Client")
    for client in Client.objects.all():
        client.client_id = None
        client.save()


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0045_client_client_id"),
    ]

    operations = [
        migrations.RunPython(populate_client_client_ids, revert_client_client_ids),
    ]
