# Generated by Django 4.2.1 on 2024-03-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0046_update_client_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="eoffice_reference_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
