# Generated by Django 4.2.1 on 2024-03-22 18:49

from django.db import migrations

from apps_bridge.api_callers.eoffice import EOfficeApi


def populate_eoffice_reference_code(apps, schema_editor):
    User = apps.get_model("user", "User")
    db_alias = schema_editor.connection.alias
    if db_alias == "default":
        return
    try:
        eoffice_api = EOfficeApi()
    except:
        return
    for user in User.objects.using(db_alias).all():
        if not user.email:
            continue
        eoffice_api.add_user_service(user)


def reverse_populate_eoffice_reference_code(apps, schema_editor):
    User = apps.get_model("user", "User")
    db_alias = schema_editor.connection.alias
    if db_alias == "default":
        return
    User.objects.using(db_alias).all().update(eoffice_reference_code=None)


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0047_user_eoffice_reference_code"),
    ]

    operations = [
        migrations.RunPython(
            populate_eoffice_reference_code,
            reverse_populate_eoffice_reference_code,
        ),
    ]
