# Generated by Django 4.2.1 on 2024-03-27 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0049_externaluser_linked_user_alter_client_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaluser",
            name="linked_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
