# Generated by Django 4.2.1 on 2024-05-14 14:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0050_alter_externaluser_linked_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_room_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
