# Generated by Django 4.2.1 on 2024-05-14 14:04

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    User = apps.get_model("user", "User")
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        user.notification_room_id = uuid.uuid4()
        user.save()


def reverse_gen_uuid(apps, schema_editor):
    User = apps.get_model("user", "User")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).update(notification_room_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0051_user_notification_room_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=reverse_gen_uuid),
    ]
