# Generated by Django 4.2.1 on 2024-05-14 14:04
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0052_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notification_room_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
