# Generated by Django 4.2.1 on 2023-06-17 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0019_alter_quantity_options"),
        ("budget_process", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstimatedFinanceArrangement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("code", models.CharField(blank=True, max_length=55, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("name_eng", models.CharField(blank=True, max_length=100, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "income_title_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("estimated_amount", models.IntegerField(blank=True, null=True)),
                ("date", models.CharField(blank=True, max_length=100, null=True)),
                ("date_eng", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "approve_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="budget_process.approveprocess",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_range_fy",
                        to="project.financialyear",
                    ),
                ),
                (
                    "income_title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="budget_process.estimatedfinancearrangement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
