# Generated by Django 4.2.1 on 2023-06-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget_process", "0002_estimatedfinancearrangement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EstimatedFinanceArrangement",
        ),
    ]
