# Generated by Django 4.2.1 on 2023-07-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_process", "0005_budgetexpensemanagement"),
    ]

    operations = [
        migrations.AddField(
            model_name="approveprocess",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="approveprocess",
            name="is_prepared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="approveprocess",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expensebudgetrangedetermine",
            name="public_participation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
