# Generated by Django 4.2.1 on 2023-07-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_process', '0006_approveprocess_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.CharField(max_length=50)),
                ('transfer_date_eng', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
