# Generated by Django 4.2.1 on 2023-07-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_process', '0008_alter_budgettransfer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetammendment',
            name='budget_management',
            field=models.IntegerField(blank=True, help_text='बजेट व्यवस्थापन:', null=True),
        ),
    ]
