# Generated by Django 4.2.1 on 2023-07-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_process', '0010_budgetammendment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetammendment',
            name='rakam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='budgetammendment',
            name='allocation_type',
            field=models.CharField(blank=True, choices=[('Allocation', 'Allocation'), ('Revision', 'Revision'), ('Transfer-in', 'Transfer-in'), ('Transfer-out', 'Transfer-out')], max_length=15, null=True),
        ),
    ]
