# Generated by Django 4.2.1 on 2023-08-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_process', '0012_remove_expensebudgetrangedetermine_public_participation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettransfer',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
