# Generated by Django 4.2.1 on 2023-08-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_process', '0013_budgettransfer_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettransfer',
            name='allocation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
