# Generated by Django 4.2.1 on 2023-11-03 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0040_alter_accounttitlemanagement_parent"),
        ("budget_process", "0015_alter_approveprocess_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetexpensemanagement",
            name="expense_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_planning.accounttitlemanagement",
            ),
        ),
    ]
