# Generated by Django 4.2.1 on 2023-11-03 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0040_alter_accounttitlemanagement_parent"),
        ("budget_process", "0016_budgetexpensemanagement_expense_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetexpensemanagement",
            name="expense_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_expenses",
                to="project_planning.accounttitlemanagement",
            ),
        ),
    ]
