# Generated by Django 4.2.1 on 2023-11-03 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_planning", "0040_alter_accounttitlemanagement_parent"),
        ("project", "0053_alter_topic_name_alter_topic_name_eng_and_more"),
        ("budget_process", "0017_alter_budgetexpensemanagement_expense_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetexpensemanagement",
            name="parent",
        ),
        migrations.AddField(
            model_name="budgetexpensemanagement",
            name="revised_expense_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budgetexpensemanagement",
            name="revised_financial_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revised_budget_expenses",
                to="project.financialyear",
            ),
        ),
        migrations.AddField(
            model_name="budgetexpensemanagement",
            name="revised_sub_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revised_budget_expenses",
                to="project_planning.submodule",
            ),
        ),
        migrations.AddField(
            model_name="budgetexpensemanagement",
            name="revision_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="budgetexpensemanagement",
            name="budget_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_expenses",
                to="project_planning.budgetsource",
            ),
        ),
        migrations.AlterField(
            model_name="budgetexpensemanagement",
            name="sub_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_expenses",
                to="project_planning.submodule",
            ),
        ),
        migrations.AlterField(
            model_name="budgetexpensemanagement",
            name="unit",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
