# Generated by Django 4.2.1 on 2023-11-17 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0054_alter_project_name"),
        ("budget_process", "0019_alter_budgetexpensemanagement_activity_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetexpensemanagement",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_expenses",
                to="project.municipality",
            ),
        ),
    ]
