# Generated by Django 4.2.1 on 2024-01-04 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_process", "0023_budgettransfer_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetammendment",
            name="budget_management",
            field=models.ForeignKey(
                blank=True,
                help_text="बजेट व्यवस्थापन",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="budget_process.budgetmanagement",
            ),
        ),
        migrations.AlterField(
            model_name="budgetexpensemanagement",
            name="estimated_expense_amount",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetexpensemanagement",
            name="first_quarter",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetexpensemanagement",
            name="forth_quarter",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetexpensemanagement",
            name="revised_expense_amount",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetexpensemanagement",
            name="second_quarter",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetexpensemanagement",
            name="third_quarter",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgetmanagement",
            name="value",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgettransfer",
            name="display_order",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="budgettransfer",
            name="total_amount",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="estimatefinancialarrangements",
            name="estimated_amount",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expensebudgetrangedetermine",
            name="estimated_amount",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incomebudgetrangedetermine",
            name="estimated_amount",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="internal_source",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="loan",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="local_gov",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="nepal_gov",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="province_gov",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="public_participation",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
